### ISSUE TITLE
`NoSuchKey` Error Occurs When Attempting to Clean a Cached Remote File

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#10124]
## 💡 Summary

When attempting to clean a cached remote file (API: `/api/admin/drive/clean-remote-files`), a `NoSuchKey` error may occur.
This error was first observed in version 13.6.1 and is still present in version 13.8.1.

## 🥰 Expected Behavior

The operation should proceed without any errors.

## 🤬 Actual Behavior

However, the server fails to perform the clean operation and returns the following error:

```
INFO 1 [queue clean-remote-files]      Deleting cached remote files...
NoSuchKey: The specified key does not exist.
    at Request.extractError (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/misskey/node_modules/.pnpm/aws-sdk@2.1318.0/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'NoSuchKey',
  region: null,
  time: 2023-02-26T15:16:08.941Z,
  requestId: null,
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 38.68095293824161
}
```

## 📝 Steps to Reproduce

1. Send a request to the API `/api/admin/drive/clean-remote-files` with an authorized account.
2. The server log will show an error indicating that the operation failed.

## 📌 Environment

Misskey version: v13.8.1
Your OS: Server (Running Docker 23.0.1 on Oracle Linux Server 9.1)
Your browser: Microsoft Edge 111.0.1660.14 (Official build) dev (64-bit)

**Comment by saschanaz** [comment]
https://github.com/misskey-dev/misskey/blob/533fe2d60726d3f05130724568e3210300efb275/packages/backend/src/queue/processors/CleanRemoteFilesProcessorService.ts#L30-L69

It's done here but there's no try-catch at all. Perhaps NoSuchKey should be ignored as that means the file is already gone for whatever reason.

See also:

https://github.com/misskey-dev/misskey/blob/533fe2d60726d3f05130724568e3210300efb275/packages/backend/src/core/DriveService.ts#L679-L693

https://github.com/misskey-dev/misskey/blob/533fe2d60726d3f05130724568e3210300efb275/packages/backend/src/core/DriveService.ts#L726-L735

**Comment by saschanaz** [comment]
Not sure how to test, there's a mocking library https://github.com/m-radzikowski/aws-sdk-client-mock but it's for v3. Kinda blocked by #10170 (but does not strictly blocking the fix for this bug)
