### ISSUE TITLE
Cannot access abuse reports from admin console

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#10155]
## 💡 Summary

/api/admin/abuse-user-reports returns error 500

## 🥰 Expected Behavior

Abuse reports should be shown.

## 🤬 Actual Behavior

UI shows "something went wrong". Browser devtools says it's an error from abuse-user-reports, containing the following:

`{"error":{"message":"Internal error occurred. Please contact us if the error persists.","code":"INTERNAL_ERROR","id":"5d37dbcb-891e-41ca-a3d6-e690c97775ac","kind":"server","info":{"e":{"message":"Could not find any entity of type \"User\" matching: {\n    \"where\": {\n        \"id\": \"96dbibhj5z\"\n    },\n    \"relations\": {\n        \"avatar\": true,\n        \"banner\": true\n    }\n}","code":"EntityNotFoundError","stack":"EntityNotFoundError: Could not find any entity of type \"User\" matching: {\n    \"where\": {\n        \"id\": \"96dbibhj5z\"\n    },\n    \"relations\": {\n        \"avatar\": true,\n        \"banner\": true\n    }\n}\n    at /misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.9.0/node_modules/typeorm/entity-manager/EntityManager.js:604:39\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserEntityService.pack (file:///misskey/packages/backend/built/core/entities/UserEntityService.js:188:20)\n    at async Promise.all (index 8)\n    at async awaitAll (file:///misskey/packages/backend/built/misc/prelude/await-all.js:5:28)\n    at async AbuseUserReportEntityService.pack (file:///misskey/packages/backend/built/core/entities/AbuseUserReportEntityService.js:25:16)\n    at async Promise.all (index 7)\n    at async file:///misskey/packages/backend/built/server/api/endpoints/admin/abuse-user-reports.js:175:20\n    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:259:16)"}}}}`

Misskey version: 13.7.5

**Comment by ghost** [comment]
`delete from abuse_user_report where abuse_user_report."targetUserId" = '96dbibhj5z';`  - this helps but I think this behavior is better to be fixed :)

**Comment by fruitriin** [comment]
same problem here
you can avoid user suspend instead of delete

anyway it seem someting bug i thought too
