### ISSUE TITLE
[v13.10.3] リージョン未設定のオブジェクトストレージを使用しているインスタンスでファイルがアップロードできない

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10408]
## 💡 Summary
オブジェクトストレージにファイルがアップロードできない

## 🥰 Expected Behavior
オブジェクトストレージにファイルがアップロードできる

## 🤬 Actual Behavior
```
Mar 25 10:23:49 localhost.localdomain misskey[2512950]: ERR  *        [drive register]        Upload Failed: key = contents/073103bc-1b71-49d0-987a-5e586b6872fa.avif, filename = output.avif
Mar 25 10:23:49 localhost.localdomain misskey[2512950]: Error: Region is missing
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at default (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+config-resolver@3.292.0/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at /home/suser/misskey/node_modules/.pnpm/@aws-sdk+node-config-provider@3.292.0/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at /home/suser/misskey/node_modules/.pnpm/@aws-sdk+property-provider@3.292.0/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async coalesceProvider (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+property-provider@3.292.0/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async /home/suser/misskey/node_modules/.pnpm/@aws-sdk+property-provider@3.292.0/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async useFipsEndpoint (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+config-resolver@3.292.0/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig>
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async resolveParams (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+middleware-endpoint@3.292.0/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromIn>
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async getEndpointFromInstructions (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+middleware-endpoint@3.292.0/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/get>
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async /home/suser/misskey/node_modules/.pnpm/@aws-sdk+middleware-endpoint@3.292.0/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async /home/suser/misskey/node_modules/.pnpm/@aws-sdk+middleware-logger@3.292.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Promise.all (index 0)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Upload.__uploadUsingPut (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+lib-storage@3.294.0_@aws-sdk+client-s3@3.294.0/node_modules/@aws-sdk/lib-storage/dist-cjs/Uploa>
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Upload.__doConcurrentUpload (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+lib-storage@3.294.0_@aws-sdk+client-s3@3.294.0/node_modules/@aws-sdk/lib-storage/dist-cjs/U>
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Promise.all (index 0)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Upload.__doMultipartUpload (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+lib-storage@3.294.0_@aws-sdk+client-s3@3.294.0/node_modules/@aws-sdk/lib-storage/dist-cjs/Up>
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Upload.done (/home/suser/misskey/node_modules/.pnpm/@aws-sdk+lib-storage@3.294.0_@aws-sdk+client-s3@3.294.0/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:39:16)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async DriveService.upload (file:///home/suser/misskey/packages/backend/built/core/DriveService.js:269:9)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async Promise.all (index 0)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async DriveService.save (file:///home/suser/misskey/packages/backend/built/core/DriveService.js:105:13)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async DriveService.addFile (file:///home/suser/misskey/packages/backend/built/core/DriveService.js:432:20)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async file:///home/suser/misskey/packages/backend/built/server/api/endpoints/drive/files/create.js:110:35
Mar 25 10:23:49 localhost.localdomain misskey[2512950]:     at async ApiCallService.call (file:///home/suser/misskey/packages/backend/built/server/api/ApiCallService.js:262:16)
Mar 25 10:23:49 localhost.localdomain misskey[2512950]: DONE *        [drive register]        drive file has been created 9cquqvv45a

```

## 📝 Steps to Reproduce

1. v13.10.3でオブジェクトストレージを使っているインスタンスでファイルをアップロードする
2. アップロード自体は200で通るがアップロードされたファイルにアクセスしようとしても404になる
3.

## 📌 Environment

Misskey version: v13.10.3
Your OS: Rocky linux
Your browser: Firefox

**Comment by nexryai** [comment]
`Error: Region is missing`なのでリージョン未設定の環境で発生する感じかも

**Comment by acid-chicken** [comment]
Related to #10363

**Comment by GrapeApple0** [comment]
> `Error: Region is missing`なのでリージョン未設定の環境で発生する感じかも
自分も同じ状況になって、regionにus-east-1とか適当に入れたら直りました(r2使ってる)

**Comment by nexryai** [comment]
設定画面に
> 'xx-east-1'のようなregionを指定してください。使用サービスにregionの概念がない場合は、空または'us-east-1'にしてください。

とありますがMinioの場合リージョンが空でもus-east-1でも駄目でMinio側で適当なリージョンを設定してs3ForcePathStyleを有効にする必要があったので、もしMisskey側の問題でない場合はこの表記を改めた方がいいかもしれません

**Comment by yszkst** [comment]
すみません、漏れがありました。　　
`対処` の方向でよいでしょうか

## 原因

v2/v3の挙動変更を見落としていました。

1． region未指定の扱い

v3ではregionの指定または環境変数・設定ファイルがいずれも無く、判別できないときはエラーにする。    
v2はregion指定無しのときは自動で us-east-1 としていた。     

2． v3でregionを空文字列にしたときの扱い

`region: meta.objectStorageRegion ?? undefined` のとき meta設定が空文字列のときは空文字列になる。    
v3でregion指定が空文字列のときは環境変数・設定ファイルがあってもエラーになる。  

v2では未指定と同じくus-east-1になる。  

## 不明

`s3ForcePathStyle` をfalseでminioに繋いだことがない。

`s3ForcePathStyle` を true でminioの設定に関わらず適当なregion (  dummy-region-1 ) のように入れてもつながる。

## 対処

+ 説明文言を変える。
  + regionが無いときはus-east-1を入れる。
  + 空にするのは設定ファイル・環境変数を読む場合とする。  
+ 空文字列のときはundefinedにする。  


## 余談  

R2は 'auto' を例にしている。  
https://blog.cloudflare.com/ja-jp/r2-ga-ja-jp/
```
// 次に、新しいクライアントを作成します。R2にはS3互換性のためのリージョンが必要ですが、サポートされているのは「auto」のみであることに注意が必要です
const S3 = new S3Client({
  region: "auto",
```

**Comment by yszkst** [comment]
#10410 　出しました。      
regionが空のときは `us-east-1` にしてしまうのも考えましたが、空の値も意味を持っているためやらない方がよいとして、仕様変更扱いにしています。

**Comment by jojobii-arks** [comment]
Adding `" "` to the "Region" field works as a temporary fix. Using a DigitalOcean Spaces as S3 Provider.

![image](https://user-images.githubusercontent.com/78003700/227725046-6d7cf30a-ae1e-4a41-b9b1-06fce4ebf116.png)

**Comment by PYU224** [comment]
Wasabiではus-east-1及び該当regionにしてもファイルのアップロードができないんですが、どうしたら良いのでしょうか？

**Comment by nexryai** [comment]
エンドポイントがドメインのみ（httpsなどを含まない）になってるか確認してください。それでも駄目なら`s3ForcePathStyle`を変えてみてください

**Comment by PYU224** [comment]
httpsが含まれてました・・・

**Comment by nexryai** [comment]
> S3の場合は空、それ以外の場合は各サービスのendpointを指定してください。'host'または'host:port'のように指定します。

というメッセージが分かりにくいのか自分も含めて観測範囲ではそれなりの人数がスキーマを含めてコケてるので、`https://`などのスキーマを含めずドメイン名のみというのを強調した方が良いかもしれません

**Comment by acid-chicken** [comment]
> > S3の場合は空、それ以外の場合は各サービスのendpointを指定してください。'host'または'host:port'のように指定します。
>
> というメッセージが分かりにくいのか自分も含めて観測範囲ではそれなりの人数がスキーマを含めてコケてるので、`https://`などのスキーマを含めずドメイン名のみというのを強調した方が良いかもしれません

サインインフォームの [ *@*  username  *@<span></span>instance.example* ] のように入力欄にプレフィックスとして書いてしまうのが良さそう

**Comment by GrapeApple0** [comment]
![Screen Shot 2023-03-26 at 23 06 23](https://user-images.githubusercontent.com/84321396/227781251-030d0f34-8ccf-4a1b-8709-5e9da0c33069.png)
雑ですがこういう感じにするだけでもだいぶ分かりやすくなると思います

**Comment by tukiminya** [comment]
私の意見としては`<input>`に`placeholer`を指定するのが一番わかりやすいと思います。

例：
![image](https://user-images.githubusercontent.com/53429948/228877616-31a2fe94-f3f9-43d9-93ac-ac59ca8617bd.png)

**Comment by 900809** [comment]
I use R2. What worked for me was removing `https://` from endpoint and setting region to `auto`.

**Comment by nexryai** [comment]
オブジェクトストレージ設定のUI関係分かりやすくするPR書いて出しちゃっていいですかね？

**Comment by nexryai** [comment]
解決したっぽいのでCloseします
