### ISSUE TITLE
一部サーバーの画像付きノートを取得する際に、invalid image: unexpected shcema of urlというエラーで取得できない

### ISSUE THREAD

**Issue by tmorio** [syuilo/Misskey#10406]
## 💡 Summary
一部のサーバーの画像付きノートを取得する際にエラーとなり取得が取得できない事象があります。

## 🥰 Expected Behavior
エラーが発生せず、画像付きノートを正常に取得できWeb UIでノートが表示される。

## 🤬 Actual Behavior
投稿を取得する際に以下のエラーが記録され、ノート取得できない。（DBにも保存されずタイムラインに表示されない）
※相手サーバーの管理者、投稿者の方にURL掲載の許可をいただいています。
```
Mar 25 01:31:12 <Hostname> misskey[1647614]: INFO *        [remote ap]        Creating the Note: https://minazukey.uk/notes/9cqboa61tp
Mar 25 01:31:12 <Hostname> misskey[1647614]: ERR  *        [api]        Internal error occurred in ap/show: invalid image: unexpected shcema of url: http://media.minazukey.uk/data/108a6d3d-7ed3-444a-9d29-450f6e1287e0.jpeg
Mar 25 01:31:12 <Hostname> misskey[1647614]: {
Mar 25 01:31:12 <Hostname> misskey[1647614]:   ep: 'ap/show',
Mar 25 01:31:12 <Hostname> misskey[1647614]:   ps: {
Mar 25 01:31:12 <Hostname> misskey[1647614]:     uri: 'https://minazukey.uk/notes/9cqboa61tp',
Mar 25 01:31:12 <Hostname> misskey[1647614]:     i: 'hItRGOSw4eyOHOlF'
Mar 25 01:31:12 <Hostname> misskey[1647614]:   },
Mar 25 01:31:12 <Hostname> misskey[1647614]:   e: {
Mar 25 01:31:12 <Hostname> misskey[1647614]:     message: 'invalid image: unexpected shcema of url: http://media.minazukey.uk/data/108a6d3d-7ed3-444a-9d29-450f6e1287e0.jpeg',
Mar 25 01:31:12 <Hostname> misskey[1647614]:     code: 'Error',
Mar 25 01:31:12 <Hostname> misskey[1647614]:     stack: 'Error: invalid image: unexpected shcema of url: http://media.minazukey.uk/data/108a6d3d-7ed3-444a-9d29-450f6e1287e0.jpeg\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at ApImageService.createImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:45:19)\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at async ApImageService.resolveImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:79:16)\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at async Promise.all (index 0)\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at async ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:144:16)\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at async default_1.fetchAny (file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:135:141)\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:89:28\n' +
Mar 25 01:31:12 <Hostname> misskey[1647614]:       '    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:275:16)'
Mar 25 01:31:12 <Hostname> misskey[1647614]:   }
Mar 25 01:31:12 <Hostname> misskey[1647614]: }
Mar 25 01:31:12 <Hostname> misskey[1647614]: Error: invalid image: unexpected shcema of url: http://media.minazukey.uk/data/108a6d3d-7ed3-444a-9d29-450f6e1287e0.jpeg
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at ApImageService.createImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:45:19)
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at async ApImageService.resolveImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:79:16)
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at async Promise.all (index 0)
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at async ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:144:16)
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at async default_1.fetchAny (file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:135:141)
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:89:28
Mar 25 01:31:12 <Hostname> misskey[1647614]:     at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:275:16)
```

## 📝 Steps to Reproduce

1. 検索欄に `https://minazukey.uk/notes/9cqboa61tp` と入力し投稿をサーバーに取得させる
2. エラーダイアログが表示される（赤いバツマークが表示と「わかった」ボタンのみが表示される）
3. サーバーログを確認するとエラーが記録されている

## 📌 Environment

Misskey version: 13.6.1（取得先はCalckey 13.1.4.1）
Your OS: macOS 13.2.1（22D68）
Your browser: Google Chrome バージョン: 111.0.5563.64（Official Build） （arm64）

サーバー構築の際はMisskey Hubの[Ubuntu版詳細手順書](https://misskey-hub.net/docs/install/ubuntu-manual.html)を確認して構築を行なっています。
※ioサーバーにもアカウントを持っているため、検索から投稿を取得できるか確認しましたが、Google ChromeのDevTools のコンソールで同様のエラーが返ってきていました。

**Comment by saschanaz** [comment]
https://github.com/misskey-dev/misskey/blob/e7fc998459b8a24cec81e99b499263fc2ec50bf4/packages/backend/src/core/activitypub/models/ApImageService.ts#L51-L53

HTTPSじゃなかったら拒否しているらしいです

**Comment by tmorio** [comment]
ありがとうございます！無事に解決されました！
ご回答感謝です！
