### ISSUE TITLE
vitest: note.test.tsでのTypeError: Cannot read properties of undefined (reading 'write')

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10462]
```
stderr | test/url-preview.test.ts > MkMediaImage > Having a player should setup the iframe
TypeError: Cannot read properties of undefined (reading 'write')
    at /home/aqz/misskey/node_modules/.pnpm/happy-dom@8.9.0/node_modules/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElement.ts:246:32

stderr | test/url-preview.test.ts > MkMediaImage > Having a player with `allow` field should set permissions
TypeError: Cannot read properties of undefined (reading 'write')
    at /home/aqz/misskey/node_modules/.pnpm/happy-dom@8.9.0/node_modules/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElement.ts:246:32

stderr | test/url-preview.test.ts > MkMediaImage > Having a player width should keep the fixed aspect ratio
TypeError: Cannot read properties of undefined (reading 'write')
    at /home/aqz/misskey/node_modules/.pnpm/happy-dom@8.9.0/node_modules/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElement.ts:246:32

stderr | test/url-preview.test.ts > MkMediaImage > Having a player width should keep the fixed height
TypeError: Cannot read properties of undefined (reading 'write')
    at /home/aqz/misskey/node_modules/.pnpm/happy-dom@8.9.0/node_modules/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElement.ts:246:32
```

**Comment by eai04191** [comment]
現時点での依存バージョンである10.0.3では同じエラーが出力されていました

happy-domのownerはこのissueの問題に対してv10.5.1で対応をしたと述べています
https://github.com/capricorn86/happy-dom/issues/992

現時点の最新バージョンである12.10.3へfrontend, backendともに依存を更新すると出力されず、frontendのテストも全てpassすることを確認しました（backendは未確認)

依存の更新に使用したコマンド:
```bash
pnpm up happy-dom --latest --filter frontend --filter backend
```
