### ISSUE TITLE
some remote posts can't be fetched

### ISSUE THREAD

**Issue by 900809** [syuilo/Misskey#10648]
## 💡 Summary

some remote posts can't be viewed on misskey.

## 🥰 Expected Behavior

when you fetch a remote post via url, the post gets fetched and displayed

## 🤬 Actual Behavior

when you look up a remote post via the url, the post does not appear with a blank error page. in the log an error like the following can be seen:
<details>
  <summary>log error (long)</summary>

![image](https://user-images.githubusercontent.com/104532529/232273658-865e7ef3-c7fa-40b8-b1ec-fc7212e2cf09.png)

```
 ERR  *        [api]        Internal error occurred in ap/show: invalid type format
 {
   ep: 'ap/show',
   ps: {
     uri: 'https://freespeechextremist.com/notice/AUgDNcnn61Aq3xzJsu',
     i: 'A985dNAe8zDocKUw'
   },
   e: {
     message: 'invalid type format',
     code: 'RequestError',
     stack: 'RequestError: invalid type format\n' +
       '    at Request._beforeError (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:310:21)\n' +
       '    at Request._onResponse (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:769:18)\n' +
       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
       '    at parse (/home/misskey/misskey/node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/index.js:322:11)\n' +
       '    at Request.<anonymous> (file:///home/misskey/misskey/packages/backend/built/core/DownloadService.js:91:32)\n' +
       '    at Request.emit (node:events:513:28)\n' +
       '    at Request._onResponseBase (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:730:14)\n' +
       '    at Request._onResponse (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:24)\n' +
       '    at ClientRequest.<anonymous> (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:783:23)\n' +
       '    at Object.onceWrapper (node:events:628:26)\n' +
       '    at ClientRequest.emit (node:events:525:35)\n' +
       '    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:695:27)\n' +
       '    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)\n' +
       '    at TLSSocket.socketOnData (node:_http_client:536:22)\n' +
       '    at TLSSocket.emit (node:events:513:28)\n' +
       '    at addChunk (node:internal/streams/readable:324:12)\n' +
       '    at readableAddChunk (node:internal/streams/readable:297:9)\n' +
       '    at Readable.push (node:internal/streams/readable:234:10)\n' +
       '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)',
     id: 'f26d1641-231a-496f-b280-ddb012ba5b3b'
   }
 }
 RequestError: invalid type format
     at Request._beforeError (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:310:21)
     at Request._onResponse (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:769:18)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at parse (/home/misskey/misskey/node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/index.js:322:11)
     at Request.<anonymous> (file:///home/misskey/misskey/packages/backend/built/core/DownloadService.js:91:32)
     at Request.emit (node:events:513:28)
     at Request._onResponseBase (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:730:14)
     at Request._onResponse (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:24)
     at ClientRequest.<anonymous> (file:///home/misskey/misskey/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:783:23)
     at Object.onceWrapper (node:events:628:26)
     at ClientRequest.emit (node:events:525:35)
     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:695:27)
     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
     at TLSSocket.socketOnData (node:_http_client:536:22)
     at TLSSocket.emit (node:events:513:28)
     at addChunk (node:internal/streams/readable:324:12)
     at readableAddChunk (node:internal/streams/readable:297:9)
     at Readable.push (node:internal/streams/readable:234:10)
     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
   input: undefined,
   code: 'ERR_GOT_REQUEST_ERROR',
   timings: {
     start: 1681575269964,
     socket: 1681575269964,
     lookup: 1681575269964,
     connect: 1681575269964,
     secureConnect: 1681575269964,
     upload: 1681575269964,
     response: 1681575270356,
     end: undefined,
     error: 1681575300558,
     abort: 1681575300557,
     phases: {
       wait: 0,
       dns: 0,
       tcp: 0,
       tls: 0,
       request: 0,
       firstByte: 392,
       download: undefined,
       total: 30594
     }
   },
   options: {
     request: undefined,
     agent: {
       http: Agent {
         _events: [Object: null prototype],
         _eventsCount: 2,
         _maxListeners: undefined,
         defaultPort: 80,
         protocol: 'http:',
         options: [Object: null prototype],
         requests: [Object: null prototype] {},
         sockets: [Object: null prototype] {},
         freeSockets: [Object: null prototype],
         keepAliveMsecs: 30000,
         keepAlive: true,
         maxSockets: Infinity,
         maxFreeSockets: 256,
         scheduling: 'lifo',
         maxTotalSockets: Infinity,
         totalSocketCount: 2,
         [Symbol(kCapture)]: false
       },
       https: Agent {
         _events: [Object: null prototype],
         _eventsCount: 2,
         _maxListeners: undefined,
         defaultPort: 443,
         protocol: 'https:',
         options: [Object: null prototype],
         requests: [Object: null prototype] {},
         sockets: [Object: null prototype] {},
         freeSockets: [Object: null prototype],
         keepAliveMsecs: 30000,
         keepAlive: true,
         maxSockets: Infinity,
         maxFreeSockets: 256,
         scheduling: 'lifo',
         maxTotalSockets: Infinity,
         totalSocketCount: 80,
         maxCachedSessions: 100,
         _sessionCache: [Object],
         [Symbol(kCapture)]: false
       },
       http2: undefined
     },
     h2session: undefined,
     decompress: true,
     timeout: {
       connect: 30000,
       lookup: 30000,
       read: undefined,
       request: 60000,
       response: 30000,
       secureConnect: 30000,
       send: 30000,
       socket: 30000
     },
     prefixUrl: '',
     body: undefined,
     form: undefined,
     json: undefined,
     cookieJar: undefined,
     ignoreInvalidCookies: false,
     searchParams: undefined,
     dnsLookup: undefined,
     dnsCache: undefined,
     context: {},
     hooks: {
       init: [],
       beforeRequest: [],
       beforeError: [],
       beforeRedirect: [],
       beforeRetry: [],
       afterResponse: []
     },
     followRedirect: true,
     maxRedirects: 10,
     cache: undefined,
     throwHttpErrors: true,
     username: '',
     password: '',
     http2: false,
     allowGetBody: false,
     headers: {
       'user-agent': 'Misskey/13.11.3 (https://niscii.xyz)',
       'accept-encoding': 'gzip, deflate, br'
     },
     methodRewriting: false,
     dnsLookupIpVersion: undefined,
     parseJson: [Function: parse],
     stringifyJson: [Function: stringify],
     retry: {
       limit: 0,
       methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
       statusCodes: [
         408, 413, 429, 500,
         502, 503, 504, 521,
         522, 524
       ],
       errorCodes: [
         'ETIMEDOUT',
         'ECONNRESET',
         'EADDRINUSE',
         'ECONNREFUSED',
         'EPIPE',
         'ENOTFOUND',
         'ENETUNREACH',
         'EAI_AGAIN'
       ],
       maxRetryAfter: undefined,
       calculateDelay: [Function: calculateDelay],
       backoffLimit: Infinity,
       noise: 100
     },
     localAddress: undefined,
     method: 'GET',
     createConnection: undefined,
     cacheOptions: {
       shared: undefined,
       cacheHeuristic: undefined,
       immutableMinTimeToLive: undefined,
       ignoreCargoCult: undefined
     },
     https: {
       alpnProtocols: undefined,
       rejectUnauthorized: undefined,
       checkServerIdentity: undefined,
       certificateAuthority: undefined,
       key: undefined,
       certificate: undefined,
       passphrase: undefined,
       pfx: undefined,
       ciphers: undefined,
       honorCipherOrder: undefined,
       minVersion: undefined,
       maxVersion: undefined,
       signatureAlgorithms: undefined,
       tlsSessionLifetime: undefined,
       dhparam: undefined,
       ecdhCurve: undefined,
       certificateRevocationLists: undefined
     },
     encoding: undefined,
     resolveBodyOnly: false,
     isStream: true,
     responseType: 'text',
     url: URL {
       href: 'https://freespeechextremist.com/media/799e5fff-1174-4f39-814d-631a0b9f9dda/Afroman%20-%20Why%20You%20Disconnecting%20My%20Video%20Camera%20%28Official%20Music%20Video%29-d_f9R_UYrDc-480p-1657040116055.mp4?name=Afroman%20-%20Why%20You%20Disconnecting%20My%20Video%20Camera%20%28Official%20Music%20Video%29-d_f9R_UYrDc-480p-1657040116055.mp4',
       origin: 'https://freespeechextremist.com',
       protocol: 'https:',
       username: '',
       password: '',
       host: 'freespeechextremist.com',
       hostname: 'freespeechextremist.com',
       port: '',
       pathname: '/media/799e5fff-1174-4f39-814d-631a0b9f9dda/Afroman%20-%20Why%20You%20Disconnecting%20My%20Video%20Camera%20%28Official%20Music%20Video%29-d_f9R_UYrDc-480p-1657040116055.mp4',
       search: '?name=Afroman%20-%20Why%20You%20Disconnecting%20My%20Video%20Camera%20%28Official%20Music%20Video%29-d_f9R_UYrDc-480p-1657040116055.mp4',
       searchParams: URLSearchParams {
         'name' => 'Afroman - Why You Disconnecting My Video Camera (Official Music Video)-d_f9R_UYrDc-480p-1657040116055.mp4' },
       hash: ''
     },
     pagination: {
       transform: [Function: transform],
       paginate: [Function: paginate],
       filter: [Function: filter],
       shouldContinue: [Function: shouldContinue],
       countLimit: Infinity,
       backoff: 0,
       requestLimit: 10000,
       stackAllItems: false
     },
     setHost: true,
     maxHeaderSize: undefined,
     signal: undefined,
     enableUnixSockets: false
   }
 } f26d1641-231a-496f-b280-ddb012ba5b3b

```

</details>

## 📝 Steps to Reproduce

1. look up affected post with the lookup tool (an example is `https://freespeechextremist.com/notice/AUgDNcnn61Aq3xzJsu`, i can't fetch it on any misskey instance)
2. after a long time, error appears

## 📌 Environment

Misskey version: 13.11.3

**Comment by blackskye-sx** [comment]
is freespeechextremist.com saved in your hosts file?

If so, I don't think this is the same issue, but it seems related. 
https://github.com/sindresorhus/got/issues/1197

I'm having the same issue with a different server.

**Comment by NukiRaccoon** [comment]
This is still happening: tried to fetch a post from Meow.Social on Resonite.Love, couldn't get it to come over, even after boosting it from an account that could see it.  It's just not wanting to fetch the post, even though it's a normal and valid post from an account I'm following.
