### ISSUE TITLE
Default ServerRules missing!

### ISSUE THREAD

**Issue by y4my4my4m** [syuilo/Misskey#10726]
## 💡 Summary

サーバールールを追加してみると以下のエラーがでます。
ルールがなくて、そのせいでユーザー登録できません！

```
Endpoint: admin/update-meta
Info: {"e":{"message":"Cannot perform update query because update values are not defined. Call \"qb.set(...)\" method to specify updated values.","code":"UpdateValuesMissingError","id":"fa482dd9-d36a-4c2a-b1e2-42ce8144821f"}}
Date: 2023-04-27T17:39:12.397Z
```

## 🥰 Expected Behavior

serverRulesがなくても、ルールを追加と保存できるように。
または、serverRulesなくてもユーザー登録モダール使えるように。

## 🤬 Actual Behavior

AddやSaveボタン押しても、何も起きない

![image](https://user-images.githubusercontent.com/8145020/234956182-5232a9e3-3169-4034-9097-1be25a9bcc8c.png)

## 📝 Steps to Reproduce

1.  /admin/server-rules ページに行って
2. add や save　押す

## 📌 Environment

Misskey version: 13.11.3
Your OS: ubuntu
Your browser: chrome

##  :information_source: 他

手動で localStorageに serverRulesを追加しても、保存できない。
ただし、追加ボタン使えるようになりました。

![image](https://user-images.githubusercontent.com/8145020/234957175-fe94ea3b-27eb-4d90-a524-4143e1d74af9.png)

**Comment by y4my4my4m** [comment]
ちなみに、dbのmetaテーブルのserverRulesコラムに追加してもNGでした？読み込めないみたい

**Comment by y4my4my4m** [comment]
サーバーログ側は：

```
 ERR  *        [api]   Internal error occurred in admin/update-meta: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.                                                                                                                        
misskey-web-1    | {                                                                                                                                                                                                                                                                                                                  
misskey-web-1    |   ep: 'admin/update-meta',                                                                                                                                                                                                                                                                                         
misskey-web-1    |   ps: { serverRules: [ 'test', 'test2' ], i: 'jvQp812gS6RWvod3' },                                                                                                                                                                                                                                                 
misskey-web-1    |   e: {                                                                                                                                                                                                                                                                                                             
misskey-web-1    |     message: 'Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.',                                                                                                                                                                            
misskey-web-1    |     code: 'UpdateValuesMissingError',                                                                                                                                                                                                                                                                              
misskey-web-1    |     stack: 'UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.\n' +                                                                                                                                                 
misskey-web-1    |       '    at UpdateQueryBuilder.createUpdateExpression (/misskey/node_modules/.pnpm/typeorm@0.3.15_ioredis@5.3.2_pg@8.10.0/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:430:19)\n' +                                                                                                                  
misskey-web-1    |       '    at UpdateQueryBuilder.getQuery (/misskey/node_modules/.pnpm/typeorm@0.3.15_ioredis@5.3.2_pg@8.10.0/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:34:21)\n' +                                                                                                                                 
misskey-web-1    |       '    at UpdateQueryBuilder.getQueryAndParameters (/misskey/node_modules/.pnpm/typeorm@0.3.15_ioredis@5.3.2_pg@8.10.0/node_modules/typeorm/query-builder/QueryBuilder.js:274:28)\n' +
misskey-web-1    |       '    at UpdateQueryBuilder.execute (/misskey/node_modules/.pnpm/typeorm@0.3.15_ioredis@5.3.2_pg@8.10.0/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:81:50)\n' +
misskey-web-1    |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
misskey-web-1    |       '    at async file:///misskey/packages/backend/built/core/MetaService.js:85:17\n' +
misskey-web-1    |       '    at async EntityManager.transaction (/misskey/node_modules/.pnpm/typeorm@0.3.15_ioredis@5.3.2_pg@8.10.0/node_modules/typeorm/entity-manager/EntityManager.js:73:28)\n' +
misskey-web-1    |       '    at async MetaService.update (file:///misskey/packages/backend/built/core/MetaService.js:77:25)\n' +
misskey-web-1    |       '    at async file:///misskey/packages/backend/built/server/api/endpoints/admin/update-meta.js:536:13\n' +
misskey-web-1    |       '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:275:16)',
misskey-web-1    |     id: 'd7a2d369-37b4-4b49-98b0-fc2981080615'
misskey-web-1    |   }
misskey-web-1    | }
```

**Comment by y4my4my4m** [comment]
手動でlocalStorageの`instance`に`"serverRules":[]` を追加すれば登録できますが、どうしてもデフォルトに入ってこない。ちょくDB編集しても出ない。。

**Comment by tamaina** [comment]
設定から「キャッシュをクリア」してもう一度試してみてください。

**Comment by y4my4my4m** [comment]
@tamaina 
ありがとうございます
やってみたのは：

0. migration
1. 設定のcache clear
2.  `mysite.com/flush`
3. npm run clean-all && build && 再起動
4. localStorage, session Storage, indexedDB削除
5. privateブラウザーでも

すべてNG

DB:
デフォルトでは：
 ![image](https://user-images.githubusercontent.com/8145020/235079494-0dc37b77-7709-40ca-ae96-bfd1c987b77d.png)

手動編集では：　
![image](https://user-images.githubusercontent.com/8145020/235079969-0a3ea897-2179-485e-af1b-1d5727965b11.png)

どっちでも、ブラウザーのプラベートセッションでentranceページではlocalStorageのinstance JSONデータには `serverRules`が存在しない。

```json
{
    "maintainerName": "XXX秘密",
    "maintainerEmail": "XXX秘密",
    "version": "13.11.3",
    "name": "mysite",
    "uri": "https://mysite.ch",
    "description": "XXX秘密",
    "langs": [],
    "tosUrl": "",
    "repositoryUrl": "https://github.com/misskey-dev/misskey",
    "feedbackUrl": "https://github.com/misskey-dev/misskey/issues/new",
    "disableRegistration": false,
    "emailRequiredForSignup": false,
    "enableHcaptcha": true,
    "hcaptchaSiteKey": "XXX秘密",
    "enableRecaptcha": false,
    "recaptchaSiteKey": null,
    "enableTurnstile": false,
    "turnstileSiteKey": null,
    "swPublickey": "XXX秘密",
    "themeColor": "#dd0000",
    "mascotImageUrl": "https://mysite.ch/client-assets/info.png",
    "bannerUrl": "https://mysite.ch/client-assets/splash.png",
    "errorImageUrl": "https://mysite.ch/client-assets/info.png",
    "iconUrl": "https://mysite.ch/client-assets/mi-white.png",
    "backgroundImageUrl": null,
    "logoImageUrl": null,
    "maxNoteTextLength": 3000,
    "defaultLightTheme": "{ながすぎてけす｝",
    "defaultDarkTheme": "{ながすぎてけす｝",
    "ads": [],
    "enableEmail": true,
    "enableServiceWorker": true,
    "translatorAvailable": false,
    "policies": {
      "gtlAvailable": true,
      "ltlAvailable": true,
      "canPublicNote": true,
      "canInvite": true,
      "canManageCustomEmojis": false,
      "canSearchNotes": false,
      "canHideAds": false,
      "driveCapacityMb": 1024,
      "pinLimit": 5,
      "antennaLimit": 5,
      "wordMuteLimit": 200,
      "webhookLimit": 3,
      "clipLimit": 10,
      "noteEachClipsLimit": 200,
      "userListLimit": 10,
      "userEachUserListsLimit": 50,
      "rateLimitFactor": 1
    },
    "mediaProxy": "https://mysite.ch/proxy"
  }
  ```

自分で入れたら、やっとユーザー登録modal開けるなんですけど、新ユーザーにはこんなのダメですね（笑）

**Comment by tamaina** [comment]
instance metaからserverRulesが消えるという現象は私の手元の環境では再現できません…

**Comment by mattyatea** [comment]
アクセストークンなので一応消したほうが良いかもです

**Comment by usbharu** [comment]
編集しても見えるので消したほうがいいです。

**Comment by mattyatea** [comment]
編集では過去のも閲覧できるので削除したほうが良いかもしれません…

**Comment by y4my4my4m** [comment]
@mattyatea  @usbharu 
みんなありがとうございます
新しいアクセストーケンを生成することが可能でしょうか？

**Comment by usbharu** [comment]
設定 → セキュリティ → ログイントークンの再生成で出来ます。

**Comment by y4my4my4m** [comment]
Fixではないけど、`packages/frontend/src/components/MkSignupDialog.rules.vue:63` でとりあえず、こう変えました。

```ts
if (!instance.serverRules || instance.serverRules.length === 0) {
  instance.serverRules = [];
  instance.serverRules.push("Rule1", "Rule2"); // optional
}
const availableServerRules = instance.serverRules.length > 0;
```
