### ISSUE TITLE
Jestがランダムに落ちる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10802]
解決した方に報奨金を進呈

**Comment by tamaina** [comment]
ん、どれ

**Comment by syuilo** [comment]
例えば
https://github.com/misskey-dev/misskey/actions/runs/4906993811/jobs/8761818955

**Comment by Nanashia** [comment]
```
    QueryFailedError: relation "muting" does not exist
```
（再現コード書けてないけど、）BullのRepeat JobとDBの初期化がタイミング的にぶつかると不味そう？

CheckExpiredMutingsProcessorService は5分毎に実行されます。
https://github.com/misskey-dev/misskey/blob/8f36a807751f018d9422b05848ce44480e10e721/packages/backend/src/queue/QueueProcessorService.ts#L160-L164

一方でテスト環境ではPostgresはstartServer毎に中身を捨てて毎回migrationをすべて実行するようになっています。
https://github.com/misskey-dev/misskey/blob/65a597a35de824c3789d7960a2927b05650a410d/packages/backend/src/postgres.ts#L221-L223

----

類似パターンとして
https://github.com/misskey-dev/misskey/actions/runs/4915818443/jobs/8778777119
```
    QueryFailedError: relation "following" does not exist
```
みたいなのもあるけど、こっちは分針が55の時にぶつかると起きる感じ？
https://github.com/misskey-dev/misskey/blob/8f36a807751f018d9422b05848ce44480e10e721/packages/backend/src/queue/QueueProcessorService.ts#L130-L134

**Comment by syuilo** [comment]
あーーー

**Comment by syuilo** [comment]
テスト中はそれらのキュー無効化してみるか

**Comment by syuilo** [comment]
いや通常のテストではjobQueue起動しないようにすでになっている

**Comment by syuilo** [comment]
どこで呼ばれてるんだ

**Comment by syuilo** [comment]
あーAccount Moveで呼んでるな

**Comment by syuilo** [comment]
これ呼ぶ必要あるのかしら

**Comment by syuilo** [comment]
なさそう

**Comment by syuilo** [comment]
あーいや
```
await sleep(1000 * 3); // wait for jobs to finish
```
がある

**Comment by tamaina** [comment]
Account Moveはキューを多用する

**Comment by Nanashia** [comment]
https://github.com/misskey-dev/misskey/actions/runs/4923097917/jobs/8794536924
```
PASS test/e2e/api-visibility.ts (33.251 s, 740 MB heap size)
PASS test/e2e/move.ts (46.698 s, 850 MB heap size) 　　← ★★★ AccountMoveのテストでjq起動
PASS test/e2e/2fa.ts (27.001 s, 808 MB heap size)
FAIL test/e2e/fetch-resource.ts (29.898 s, 898 MB heap size　　← ★別のテストがFAIL
  ● Webリソース › /@:user/pages/:page › はGETできる。(存在しないIDでも。)

    TypeORMError: Driver not Connected

      36 | 			.innerJoinAndSelect('muting.mutee', 'mutee')
      37 | 			.getMany();
    > 38 |
         | ^
      39 | 		if (expired.length > 0) {
      40 | 			await this.userMutingService.unmute(expired);
      41 | 		}

...
      at SelectQueryBuilder.getMany (../../node_modules/.pnpm/typeorm@0.3.15_ioredis@5.3.2_pg@8.10.0/src/query-builder/SelectQueryBuilder.ts:1759:36)
      at CheckExpiredMutingsProcessorService.process (src/queue/processors/CheckExpiredMutingsProcessorService.ts:38:56)
      at Queue.<anonymous> (src/queue/SystemQueueProcessorsService.ts:43:96)　← ★★★ なぜかjqが生き残っている？？？
      at Queue.Object.<anonymous>.Queue.processJob (../../node_modules/.pnpm/bull@4.10.4/node_modules/bull/lib/queue.js:1166:22) 
```

https://github.com/misskey-dev/misskey/commit/5c54e12099035a5dad080de5ed8ad4ec4e541158 で jq.close()を呼ぶようになりましたが、このJobQueueの実体（queue:systemなどのBull.Queue）はどこからもclose()されていないので、結局停止できていない気がします。
setIntervalやRedisのようにonApplicationShutdownを使って破棄する必要があるかも？（手元で検証中）

**Comment by syuilo** [comment]
onApplicationShutdownで停止するようにした

**Comment by syuilo** [comment]
直ったかも？

**Comment by 1673beta** [comment]
ランダムにタイムアウトで落ちる時があるかも
example: https://github.com/misskey-dev/misskey/actions/runs/13389169250/job/37392725693?pr=15455

**Comment by samunohito** [comment]
```txt
test.concurrent('[withFiles: true] フォローしているユーザーのファイル付きノートのみ含まれる', async () => {
```

これは・・・
related https://github.com/misskey-dev/misskey/issues/15076

**Comment by samunohito** [comment]
https://github.com/misskey-dev/misskey/pull/16935 でvitestに移行されたためcloseします。
現状はっきりとした動きがあるのは #15076 の現象のみなので、そちらで追跡という形で…
他にも別の現象が起これば、個別で起票する形とさせていただきたく思います
