### ISSUE TITLE
PNPM : LOCKFILE_MISSING_DEPENDENCY Broken lockfile

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#11118]
## 💡 Summary

Update Misskey to 13.13.2 fail

### 🛰 Backend (for server admin)

* Misskey: v13.12.2
* Node: v18.16.1
* PostgreSQL: 15.x.x
* Redis: 5.0.14
* OS and Architecture: Debian (10) Buster Hetzner VPS CPX11

## ❌ Actual Behavior

Update stops after this command :

`NODE_OPTIONS=--max_old_space_size=3072 NODE_ENV=production pnpm install --frozen-lockfile;`

Result :

```
 WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/execa/5.1.1' in pnpm-lock.yaml

This issue is probably caused by a badly resolved merge conflict.
To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
```

I've tried 'pnpm install --no-frozen-lockfile' but that doesn't work either

```
 WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
 ERROR  /@adobe/css-tools@4.2.0 is an invalid relative dependency path

pnpm: /@adobe/css-tools@4.2.0 is an invalid relative dependency path
    at Object.parse2 [as parse] (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114178:15)
    at nameVerFromPkgSnapshot (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114287:28)
    at addPreferredVersionsFromLockfile (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:196837:89)
    at getPreferredVersionsFromLockfileAndManifests (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:196831:7)
    at _installInContext (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:197757:142)
    at async installInContext (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:198099:16)
    at async _install (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:197622:25)
    at async mutateModules (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:197344:23)
    at async recursive (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:198939:50)
    at async installDeps (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:199235:11)
```

**Comment by tamaina** [comment]
It looks like you have an older version of pnpm, how did you install Misskey and pnpm?

**Comment by kazukyakayashi** [comment]
I installed Misskey from git (a long time ago) and pnpm as indicated in the doc, and had no problems so far.

```
pnpm --version
8.5.1
```

**Comment by tamaina** [comment]
> as indicated in the doc

Which document?

**Comment by kazukyakayashi** [comment]
Misskey doc : https://misskey-hub.net/en/docs/install/manual.html

**Comment by tamaina** [comment]
So you use corepack.

It is odd that your environment is 8.5.1 while package.json specifies 8.6.0.

**Comment by kazukyakayashi** [comment]
I'm trying to update pnpm but I can't.

I can use `corepack prepare pnpm@latest --activate` but it doesn't change anything, same with `pnpm up` or `pnpm install --frozen-lockfile`.

Honestly I don't understand much about pnpm and it seems 100 more obscure than npm, I follow the documentation but nothing, I always get errors.

```
$ corepack prepare pnpm@latest --activate
Preparing pnpm@latest for immediate activation...

$ pnpm up
 WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
 WARN  Could not find preferred package /@types/gulp/4.0.10 in lockfile
 WARN  Could not find preferred package /@types/gulp-rename/2.0.1 in lockfile
 WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/5.59.8(@typescript-eslint/parser@5.59.8)(eslint@8.41.0)(typescript@5.1.3) in lockfile
 WARN  Could not find preferred package /@typescript-eslint/parser/5.59.8(eslint@8.41.0)(typescript@5.1.3) in lockfile
 ERROR  /@types/serviceworker@0.0.67 is an invalid relative dependency path

pnpm: /@types/serviceworker@0.0.67 is an invalid relative dependency path
    at Object.parse2 [as parse] (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114178:15)
    at nameVerFromPkgSnapshot (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114287:28)
    at referenceSatisfiesWantedSpec (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:183767:81)
    at getDepsToResolve (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:183722:63)
    at /home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:183366:96
    at Array.map (<anonymous>)
    at resolveDependenciesOfImporters (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:183366:55)
    at resolveRootDependencies (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:183329:80)
    at resolveDependencyTree (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:184265:105)
    at resolveDependencies (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:194566:211)
 WARN  335 other warnings
```

**Comment by kazukyakayashi** [comment]
The (pnpm) documentation tells you to do a `corepack prepare pnpm@latest --activate` but doesn't tell you that you then need to do another command, which is not `pnmp up` (update) ... but `pnpm add -g pnpm`.

But I've got another problem now ... obviously still related to pnpm.
