### ISSUE TITLE
Update Misskey to 13.13.2 fail (pnpm)

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#11120]
## 💡 Summary

Update Misskey to 13.13.2 fail

### 🛰 Backend (for server admin)

* Misskey: v13.12.2
* Node: v18.16.1
* PostgreSQL: 15.x.x
* Redis: 5.0.14
* OS and Architecture: Debian (10) Buster Hetzner VPS CPX11

## ❌ Actual Behavior

```
<13>Jul  5 09:49:50 misskey_update.sh: [INFO] Install and update dependencies 
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1491
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/misskey/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Downloading registry.npmjs.org/@tensorflow/tfjs-core/4.4.0: 6.73 MB/6.73 MB, done
Downloading registry.npmjs.org/typescript/5.1.3: 7.15 MB/7.15 MB, done
Downloading registry.npmjs.org/@tensorflow/tfjs-layers/4.4.0: 6.01 MB/6.01 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.61: 17.2 MB/17.2 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.61: 17.3 MB/17.3 MB, done
Downloading registry.npmjs.org/three/0.153.0: 6.1 MB/6.1 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.56: 17.2 MB/17.2 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.56: 17 MB/17 MB, done
Downloading registry.npmjs.org/@tensorflow/tfjs/4.4.0: 29.7 MB/29.7 MB, done
Progress: resolved 1491, reused 0, downloaded 1491, added 1491, done
node_modules/.pnpm/@nestjs+core@9.4.2_@nestjs+common@9.4.2_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core: Running postinstall script, done in 145ms
node_modules/.pnpm/bufferutil@4.0.7/node_modules/bufferutil: Running install script, done in 122ms
node_modules/.pnpm/core-js@3.29.1/node_modules/core-js: Running postinstall script, done in 67ms
node_modules/.pnpm/sharp@0.31.3/node_modules/sharp: Running install script, done in 786ms
node_modules/.pnpm/sharp@0.32.1/node_modules/sharp: Running install script, done in 704ms
node_modules/.pnpm/utf-8-validate@6.0.3/node_modules/utf-8-validate: Running install script, done in 119ms
node_modules/.pnpm/@swc+core@1.3.56/node_modules/@swc/core: Running postinstall script, done in 77ms
node_modules/.pnpm/@swc+core@1.3.61/node_modules/@swc/core: Running postinstall script, done in 92ms
node_modules/.pnpm/esbuild@0.17.18/node_modules/esbuild: Running postinstall script, done in 82ms
node_modules/.pnpm/msgpackr-extract@3.0.2/node_modules/msgpackr-extract: Running install script, done in 122ms
node_modules/.pnpm/@tensorflow+tfjs-node@4.4.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install script, done in 3.9s
node_modules/.pnpm/re2@1.19.0/node_modules/re2: Running install script...
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at spawn (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:83070:19)
    at runCmd_ (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:99304:20)
    at runCmd (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:99245:9)
    at runPackageLifecycle (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:99212:7)
    at Array.<anonymous> (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:98685:13)
    at LOOP (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:98712:18)
    at chain (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:98719:9)
    at lifecycle_ (/home/misskey/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.6/node_modules/pnpm/dist/pnpm.cjs:99186:7) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}

Node.js v18.16.1
```

**Comment by kazukyakayashi** [comment]
resolve with : `NODE_OPTIONS=--max-old-space-size=4096` ... ...
