### ISSUE TITLE
InboxのQueueにおいて、一意性のエラーが多発する

### ISSUE THREAD

**Issue by sasagar** [syuilo/Misskey#11133]
## 💡 Summary

InboxのQueueで（いかすきーにおいてはmisskey.ioのみ）ジョブキューの一意性エラーが多数発生する。
（おま環だったら申し訳ないのですが...。）

## 🥰 Expected Behavior

エラーなく処理される。

## 🤬 Actual Behavior

以下のエラーが発生する。

```
QueryFailedError: 重複したキー値は一意性制約"IDX_ad0c221b25672daf2df320a817"違反となります
    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.16_ioredis@5.3.2_pg@8.11.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/misskey/node_modules/.pnpm/typeorm@0.3.16_ioredis@5.3.2_pg@8.11.0/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async ReactionService.create (file:///misskey/packages/backend/built/core/ReactionService.js:115:13)
    at async ApInboxService.like (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:135:16)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:105:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:73:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:156:9)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@3.15.0/node_modules/bullmq/dist/cjs/classes/worker.js:352:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@3.15.0/node_modules/bullmq/dist/cjs/classes/worker.js:535:24)
```

## 📝 Steps to Reproduce

1. misskey.ioからのinboxを待つ

## 📌 Environment

CentOS Stream 9 / 6Core / 8GB RAM  
Worker x 3

### 💻 Frontend
* Model and OS of the device(s):
  MacOS Ventura / Windows 11
* Browser:
  Chrome (latest)
* Server URL:
  ikaskey.bktsk.com
* Misskey:
  13.13.2 (fork version)

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Docker compose (Misskey & Redis & Meilisearch) / Systemctl (postgresql)
* Misskey: 13.13.2 (fork version)
* Node: 18.6.0
* PostgreSQL: 15.3
* Redis: 7
* OS and Architecture: CentOS Stream 9

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/blob/c065b97140f29ad93d6499b06c59c5d98d194fc2/packages/backend/src/misc/is-duplicate-key-value-error.ts#L2
が引っかからないってどこかで見たわ。

PostgreSQLのバージョンとロケール依存？

**Comment by sasagar** [comment]
#11159 をPRしてみました👀

**Comment by mei23** [comment]
そもそも、インデックス `"IDX_ad0c221b25672daf2df320a817" ON "note_reaction" ("userId", "noteId")`
の重複が発生するのは、通常Pleromaのような1ユーザーが複数回リアクション出来る実装から来た場合なので、Misskey実装から大量に来るのはおかしいように思える。

リアクションのフォロワー配信とダイレクト配信が重複してる説
→ 同sharedInboxは配信側で重複除外しているので該当しない

リレーから来た分と重複している
→ リレーにリアクションは送らないので該当しない

ユーザーがリアクション付ける外すを乱発していてなおかつ配送受信順が狂っている
→ あまりなさそう

結局、重複リアクションが大量に飛んでくるの自体は謎
