### ISSUE TITLE
cypressが落ちる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11793]
何もしてないのに壊れた

```
> misskey@[20](https://github.com/misskey-dev/misskey/actions/runs/6106677451/job/16572187639#step:12:21)[23](https://github.com/misskey-dev/misskey/actions/runs/6106677451/job/16572187639#step:12:24).9.0-beta.3 start:test /home/runner/work/misskey/misskey
> cd packages/backend && cross-env NODE_ENV=test node ./built/boot/index.js

/home/runner/work/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/connection/Connection.js:12
class Connection extends DataSource_1.DataSource {
                                      ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/runner/work/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/connection/Connection.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1[24](https://github.com/misskey-dev/misskey/actions/runs/6106677451/job/16572187639#step:12:25)1:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1[29](https://github.com/misskey-dev/misskey/actions/runs/6106677451/job/16572187639#step:12:30)5:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:1[30](https://github.com/misskey-dev/misskey/actions/runs/6106677451/job/16572187639#step:12:31):18)
    at Object.<anonymous> (/home/runner/work/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/index.js:142:20)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```

**Comment by nafu-at** [comment]
TypeORMがNodeJS 20.6で正常に動作しない不具合があるようです。
https://github.com/typeorm/typeorm/issues/10338

**Comment by syuilo** [comment]
なるほど
でもNodeJS 20.6.0 にアップグレードした覚えがない

**Comment by syuilo** [comment]
確認しても 20.5.1 を使うようになってる
なぜ 20.6.0 が出てくるのかが謎

**Comment by nafu-at** [comment]
ログ内のActionsの事だと推測して述べると、Workflowファイルの中で20.xの形で指定されているのが要因かと思います。
```yaml
  e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
```

Actions log
```
Run actions/setup-node@v3.8.1
Attempting to download 20.x...
Acquiring 20.6.0 - x64 from...
```

**Comment by syuilo** [comment]
🙏🏻🙏🏻🙏🏻
