### ISSUE TITLE
Error during migration run

### ISSUE THREAD

**Issue by Rsplwe** [syuilo/Misskey#11794]
Command: 
```bash
pnpm run migrate
```

```

> misskey@2023.9.0-beta.4 migrate /home/misskey/misskey
> cd packages/backend && pnpm migrate


> backend@ migrate /home/misskey/misskey/packages/backend
> pnpm typeorm migration:run -d ormconfig.js

Error during migration run:
Error: Unable to open file: "/home/misskey/misskey/packages/backend/ormconfig.js". Class extends value undefined is not a constructor or null
    at CommandUtils.loadDataSource (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

```

* Misskey: 2023.9.0-beta.4
* Node: 20.6.0
* PostgreSQL: 15.4

**Comment by syuilo** [comment]
try node 20.5.1

**Comment by Rsplwe** [comment]
> try node 20.5.1

it works
