### ISSUE TITLE
Misskey installs good but does not allow to add admin user from (Unraid)

### ISSUE THREAD

**Issue by ravarkon** [syuilo/Misskey#11854]
## 💡 Summary

500 server error

## 🥰 Expected Behavior

Does not allow to make admin user.

## 🤬 Actual Behavior

I can't even access anything 

## 📌 Environment

v13.14.2 <-- as far i know.. 

### 💻 Frontend
* Model and OS of the device(s):
 Unraid 6.12.4

i think its running FreeBSD not sure..

**Comment by ravarkon** [comment]
update to: 

"error": {
        "message": "Internal error occurred. Please contact us if the error persists.",
        "code": "INTERNAL_ERROR",
        "id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
        "kind": "server",
        "info": {
            "e": {
                "message": "unrecognized id generation method",
                "code": "Error",
                "id": "52a05dd5-c5a8-4f3e-bff6-01bdeb252571"
            }

**Comment by akaregi** [comment]
I could reproduce this error.

- This error happens when the creation of the first account (i.e. administrator) is in the process.
- It seems that the frontend works good. I think backend is the problem.

Environment:
- Runs on: Oracle Cloud Infrastructure / Ampere A1
- OS: Ubuntu 22.04 (aarch64)
- Version: 13.14.2 (Docker Hub: `misskey/misskey:13.14.2`)

Note that I place Traefik in front of Misskey as the proxy.

```
misskey   | ERR  *      [api]   Internal error occurred in admin/accounts/create: unrecognized id generation method
misskey   | {
misskey   |   ep: 'admin/accounts/create',
misskey   |   ps: { username: '******', password: '******' },
misskey   |   e: {
misskey   |     message: 'unrecognized id generation method',
misskey   |     code: 'Error',
misskey   |     stack: 'Error: unrecognized id generation method\n' +
misskey   |       '    at IdService.genId (file:///misskey/packages/backend/built/core/IdService.js:45:23)\n' +
misskey   |       '    at file:///misskey/packages/backend/built/core/SignupService.js:122:36\n' +
misskey   |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
misskey   |       '    at async EntityManager.transaction (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.1/node_modules/typeorm/entity-manager/EntityManager.js:73:28)\n' +
misskey   |       '    at async SignupService.signup (file:///misskey/packages/backend/built/core/SignupService.js:115:9)\n' +
misskey   |       '    at async file:///misskey/packages/backend/built/server/api/endpoints/admin/accounts/create.js:64:41\n' +
misskey   |       '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:313:16)',
misskey   |     id: 'ae7d05d1-27fd-4725-8b31-ea6dd507d92f'
misskey   |   }
misskey   | }
misskey   | Error: unrecognized id generation method
misskey   |     at IdService.genId (file:///misskey/packages/backend/built/core/IdService.js:45:23)
misskey   |     at file:///misskey/packages/backend/built/core/SignupService.js:122:36
misskey   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
misskey   |     at async EntityManager.transaction (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.1/node_modules/typeorm/entity-manager/EntityManager.js:73:28)
misskey   |     at async SignupService.signup (file:///misskey/packages/backend/built/core/SignupService.js:115:9)
misskey   |     at async file:///misskey/packages/backend/built/server/api/endpoints/admin/accounts/create.js:64:41
misskey   |     at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:313:16) ae7d05d1-27fd-4725-8b31-ea6dd507d92f
```

**Comment by akaregi** [comment]
Also I found the solution for this. Use the alternative ID-generation method instead of `aidx`. 

Assuming that you use the configuration below (`default.yml`),

```yml
#   ┌───────────────┐
#───┘ ID generation └───────────────────────────────────────────

# You can select the ID generation method.
# You don't usually need to change this setting, but you can
# change it according to your preferences.

# Available methods:
# aid ... Short, Millisecond accuracy
# aidx ... Millisecond accuracy
# meid ... Similar to ObjectID, Millisecond accuracy
# ulid ... Millisecond accuracy
# objectid ... This is left for backward compatibility

# ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE
# ID SETTINGS AFTER THAT!

id: "aidx"
```

rewrite `id: "aidx"` to other one, like:

```yml
id: "ulid"
```

This fixes the error in my situation. Please note that this is not the direct fix of the problem but the mitigation.

**Comment by syuilo** [comment]
aidx will be added starting with v2023.9.0 and is not yet available.

**Comment by ravarkon** [comment]
alright i will check into this one and thank you :)
