### ISSUE TITLE
Support request. - how to admin + user

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#11942]
Since https://forum.misskey.io/settings ain't working, 

![image](https://github.com/misskey-dev/misskey/assets/44526987/b9d47fac-522a-43e4-b5bc-378bdd921fda)

Yes I did sign up for an account, but have never received the confirmation mail, despite requesting it numerous times, so here we go.

----------------------

First of I would say I agree with this post https://forum.misskey.io/d/15-more-federation-moderation-and-security-features

----------------------

Next I have more than one request for which I have been unable to find any manual/documentation for, and unfortunately most of the written stuff out there is in non english.

1. How do I increase a users drive space?
2. How do I configure misskey + meilisearch to interact with each other?
3. How do I reset a users password? `https://matrix.rocks/admin/user/userID` => "Reset Password" do not send a mail to the user, even I have been modifying the mail + confirmed in the database. (Mailserver setup is tested to verify it can send mail to user mail address) - Should it be possible to have admin choose a password for a user?
4. When trying to use the "lost password" from login screen, the same as described above happens, no mail are received (send)
5. How do I change the HTML based mail to safe txt based mail? (I do not open html)
6. If a user is deleted or suspended, would it be possible to have a feature that deletes all the users posts asap?
7. Where might the admistrators documentations be located, in english?
8. Bot protection, request you are scripting your own, as nobody ever should be using any of `hcapcha`, `reCaptcha` or `Turnstile` as they all are privacy invasive and unsafe to use. Which leaves any misskey installations without any "Bot" protection. Mastodon, Pleroma and akkoma have solved this already.

User based questions
1. How do you avoid all msg to be collapsed if somebody have marked it nsfw?
2. If I mark a user as muted/block, the users posts is still visible, is there are way to make them disappear asap?
3. timeline, how do I stop my own actions from like boosting from appear as new msg in the top? I already know I boosted(Renote) it or added a emoji(Action)!!!!

Misskey is installed with the bash script

**Comment by spirillen** [comment]
once you have filled out the search field, it  would be nice if you could just hit the enter to start the search vs you have to move the mouse

https://matrix.rocks/search

**Comment by kakkokari-gtyih** [comment]
> Since https://forum.misskey.io/settings ain't working,

Misskey Forum is already out of service at the end of November 2022.

https://forum.misskey.io/d/112-misskey-forum-to-end-service-at-the-end-of-this-month

**Comment by spirillen** [comment]
Any one who have a suggestion for fixing the `Error code: meta_fetch` for not logged in users, while I as preciously logged in, have a full functional instance??

![image](https://github.com/misskey-dev/misskey/assets/44526987/5e326bbc-af3a-4598-8dc6-064d041c8f42)

![image](https://github.com/misskey-dev/misskey/assets/44526987/0e99442e-fc01-4d19-8e85-c685e7ebcce2)

Log output

```
Oct 01 18:31:39 ns3109441 "matrix.rocks"[1574]: WARN 1        [queue inbox]        failed(UnrecoverableError: skip: failed to resolve user) id=487697 attempts=1/8 age=9ms activity=https://mastodonapp.uk/users/jayesstoo/statuses/111161186596356672/activity
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]: ERR  *        [api]        Internal error occurred in meta: JSON5: invalid character 'M' at 1:1
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]: {
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:   ep: 'meta',
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:   ps: { detail: true },
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:   e: {
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     message: "JSON5: invalid character 'M' at 1:1",
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     code: 'SyntaxError',
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     stack: "SyntaxError: JSON5: invalid character 'M' at 1:1\n" +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at syntaxError (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1110:17)\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at invalidChar (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1055:12)\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at Object.value (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:309:15)\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at lex (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:100:42)\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at Object.parse (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:25:17)\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/meta.js:374:86\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:       '    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:316:16)',
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     id: '68063bb0-ff56-461d-a23d-f86f2308140a'
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:   }
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]: }
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]: SyntaxError: JSON5: invalid character 'M' at 1:1
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at syntaxError (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1110:17)
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at invalidChar (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1055:12)
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at Object.value (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:309:15)
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at lex (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:100:42)
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at Object.parse (/home/misskey/misskey/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:25:17)
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/meta.js:374:86
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:     at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:316:16) {
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:   lineNumber: 1,
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]:   columnNumber: 1
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1325]: } 68063bb0-ff56-461d-a23d-f86f2308140a
Oct 01 18:31:40 ns3109441 "matrix.rocks"[1574]: WARN 1        [queue inbox]        failed(UnrecoverableError: skip: failed to resolve user) id=487698 attempts=1/8 age=8ms activity=https://mastodonapp.uk/users/jayesstoo/statuses/111161186596356672/activity
Oct 01 18:31:42 ns3109441 "matrix.rocks"[1574]: INFO 1        [remote ap]        Create: https://phpc.social/users/davidbisset/statuses/111161180498544144/activity
Oct 01 18:31:42 ns3109441 "matrix.rocks"[1574]: INFO 1        [remote ap]        Creating the Note: https://phpc.social/users/davidbisset/statuses/111161180498544144
Oct 01 18:31:42 ns3109441 "matrix.rocks"[1574]: INFO 1        [remote ap]        Creating the Image: https://media.phpc.social/media_attachments/files/111/161/174/478/152/050/original/e7affa5d74776ea7.png
Oct 01 18:31:42 ns3109441 "matrix.rocks"[1574]: INFO 1        [download]        Downloading https://media.phpc.social/media_attachments/files/111/161/174/478/152/050/original/e7affa5d74776ea7.png to /tmp/tmp-1574-1q5zBwbmQ6bX ...
Oct 01 18:31:42 ns3109441 "matrix.rocks"[1574]: DONE 1        [download]        Download finished: https://media.phpc.social/media_attachments/files/111/161/174/478/152/050/original/e7affa5d74776ea7.png
Oct 01 18:31:43 ns3109441 "matrix.rocks"[1574]: INFO 1        [drive register]        {"size":359939,"md5":"9934d88af0562911e6c539189b512adf","type":{"mime":"image/png","ext":"png"},"width":1755,"height":1152,"blurhash":"e04LRR%300xut6%M-;f8%MWBInR%-;xtRj%MRQxuxuM{9F%Mt7xbof","sensitive":false,"porn":false,"warnings":[]}
```
