### ISSUE TITLE
docker compose can't install 2023.10.0.b1

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#11959]
## 💡 Summary
I ran `sudo docker compose run --rm web pnpm run init`

## 🥰 Expected Behavior

Running migrations 

## 🤬 Actual Behavior

```bash
[+] Creating 2/0
 ✔ Container beta-mk-db-1     Running                                                                                 0.0s 
 ✔ Container beta-mk-redis-1  Running                                                                                 0.0s 

> misskey@2023.10.0-beta.1 init /misskey
> pnpm migrate


> misskey@2023.10.0-beta.1 migrate /misskey
> cd packages/backend && pnpm migrate


> backend@ migrate /misskey/packages/backend
> pnpm typeorm migration:run -d ormconfig.js

Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". ENOENT: no such file or directory, open '/misskey/.config/default.yml'
    at CommandUtils.loadDataSource (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

## 📝 Steps to Reproduce

1. git checkout develop
2. create docker configs
3. build containers
4. run init migrations

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service:  docker compose / develop
* Misskey: 2023.10.0-b1

**Comment by tassoman** [comment]
Wrong configuration
