### ISSUE TITLE
13.14.2→2023.9.3 migrate が通らない

### ISSUE THREAD

**Issue by mendakon** [syuilo/Misskey#11968]
## 💡 Summary

pnpm run migrateがコケる
**query failed: CREATE UNIQUE INDEX "IDX_c71faf11f0a28a5c0bb506203c" ON "channel_favorite" ("userId", "channelId")
→　error: could not create unique index "IDX_c71faf11f0a28a5c0bb506203c"
query: ROLLBACK**

## 🥰 Expected Behavior

migrateが正常に成功する

## 🤬 Actual Behavior

エラーが出てmigrateできず終了する

## 📝 Steps to Reproduce

1.
2.
3.

### 🛰 Backend (for server admin)
  misskey@localhost:~/misskey$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

* Misskey:
  13.14.2→2023.9.3

* Node: v20.5.1
* PostgreSQL: psql (PostgreSQL) 15.4 (Ubuntu 15.4-0ubuntu0.23.04.1)

### エラー
~~~
query failed: CREATE UNIQUE INDEX "IDX_c71faf11f0a28a5c0bb506203c" ON "channel_favorite" ("userId", "channelId")
error: error: could not create unique index "IDX_c71faf11f0a28a5c0bb506203c"
query: ROLLBACK
Error during migration run:
QueryFailedError: could not create unique index "IDX_c71faf11f0a28a5c0bb506203c"
    at PostgresQueryRunner.query (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Fix1690417561187.up (file:///home/misskey/misskey/packages/backend/migration/1690417561187-Fix.js:28:9)
    at async MigrationExecutor.executePendingMigrations (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async Object.handler (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/commands/MigrationRunCommand.js:68:13) {
  query: 'CREATE UNIQUE INDEX "IDX_c71faf11f0a28a5c0bb506203c" ON "channel_favorite" ("userId", "channelId") ',
  parameters: undefined,
  driverError: error: could not create unique index "IDX_c71faf11f0a28a5c0bb506203c"
      at /home/misskey/misskey/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
      at async Fix1690417561187.up (file:///home/misskey/misskey/packages/backend/migration/1690417561187-Fix.js:28:9)
      at async MigrationExecutor.executePendingMigrations (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/data-source/DataSource.js:260:35)
      at async Object.handler (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/commands/MigrationRunCommand.js:68:13) {
    length: 260,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("userId", "channelId")=(9bvm3yk4dn, 9d9h037eo9) is duplicated.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'channel_favorite',
    column: undefined,
    dataType: undefined,
    constraint: 'IDX_c71faf11f0a28a5c0bb506203c',
    file: 'tuplesort.c',
    line: '4423',
    routine: 'comparetup_index_btree'
  },
  length: 260,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("userId", "channelId")=(9bvm3yk4dn, 9d9h037eo9) is duplicated.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'channel_favorite',
  column: undefined,
  dataType: undefined,
  constraint: 'IDX_c71faf11f0a28a5c0bb506203c',
  file: 'tuplesort.c',
  line: '4423',
  routine: 'comparetup_index_btree'
}
?ELIFECYCLE? Command failed with exit code 1.
?ELIFECYCLE? Command failed with exit code 1.
~~~

### \di
~~~~
public | IDX_735a5544f9249d412255f47f95 | index | misskey  | channel_favorite
~~~~

**Comment by mendakon** [comment]
mk1=# SELECT * FROM channel_favorite WHERE "userId" = '9d8csiy1up' AND "channelId" = '9d9h037eo9';
     id     |         createdAt          | channelId  |   userId
------------+----------------------------+------------+------------
 9du4at4rbd | 2023-04-21 12:54:15.291+00 | 9d9h037eo9 | 9d8csiy1up
(1 row)

**Comment by mendakon** [comment]
解決しました
データが重複してたのが原因でした
手作業で片方消したら通りました
なんか5,6データ重複してたのですが、理由は謎です
（一時期サーバー自体がptptしたり、何度も再起動したりしてたりで重複してSQL走っちゃったりとかあるのかな？謎）
