### ISSUE TITLE
ダイレクト投稿をRNできる

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11969]
(オリジナルは niri-la/misskey.niri.la#56 by @KisaragiEffective)

Originally ダイレクト投稿なRNを削除すると500エラーになる

## 💡 Summary

投稿範囲をダイレクトにしたノートをRNし、そのRNを取り消すとステータスコードが500のレスポンスとエラーが返ってくる

(※おそらく [misskey-dev#10127](https://github.com/misskey-dev/misskey/issues/10127) と同根のバグだと思われるが、upstreamで発生するか検証していないため一旦このリポジトリに記録)

anatawa12追記: そもそもダイレクト投稿がrenoteできるのが誤りでないかとも思っています

## 🥰 Expected Behavior

200などで正常に消去される

## 🤬 Actual Behavior

消去はされているように見えるが、レスポンスでエラーが返ってくる

## 📝 Steps to Reproduce

1. 投稿範囲をダイレクトにしたノートをする
2. そのノートをリノートする
3. リノートを取り消す

### 💻 Frontend
* Model and OS of the device(s):macOS 14.0 23A344 arm64
  
* Browser:firefox 118.0.1 (64 ビット
  
* Server URL: misskey.niri.la
  
* Misskey:2023.9.3-kinel.2

### 🛰 Backend (for server admin)

同上環境の開発環境でも確認しました。

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by anatawa12** [comment]
```
Error: renderAnnounce: cannot render non-public note
    at ApRendererService.renderAnnounce (file:///Users/anatawa12/IdeaProjects/misskey/packages/backend/built/core/activitypub/ApRendererService.js:93:19)
    at NoteCreateService.renderNoteOrRenoteActivity (file:///Users/anatawa12/IdeaProjects/misskey/packages/backend/built/core/NoteCreateService.js:662:38)
    at file:///Users/anatawa12/IdeaProjects/misskey/packages/backend/built/core/NoteCreateService.js:546:53
    at NoteCreateService.postNoteCreated (file:///Users/anatawa12/IdeaProjects/misskey/packages/backend/built/core/NoteCreateService.js:572:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by syuilo** [comment]
> そもそもダイレクト投稿がrenoteできるのが誤りでないかとも思っています

👍
