### ISSUE TITLE
Password reset by/for user not working

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#12038]
## 💡 Summary

I have a some point created or changed my password for my primary account, and now I can't reset it as no email or any other form of links are reveling how to reset the password or generating a new one.

## 🥰 Expected Behavior

Receiving a mail in the users mail account with a link to reset their password

## 🤬 Actual Behavior

When you as user clicks the `Forgot password` on the login screen, or as admin from the admin interface clicks `Reset password` no further instructions is provided.

## 📝 Steps to Reproduce

1. forget your password
2. Click `forgot password`
3. as admin `reset password`
4. ?? where is the link with reset instructions??

## 📌 Environment
2023.10.1

### 💻 Frontend
* Model and OS of the device(s):
  `5.15.0-86-generic`
* Browser:
  FireFox + Tor
* Server URL:
  [](https://matrix.rocks/about)
* Misskey:
  2023.10.1 (This is the second location you ask for this!!)

### 🛰 Backend (for server admin)
`5.15.0-86-generic`

* Installation Method or Hosting Service: "Misskey install shell script"
* Misskey: 2023.10.1 (This is the third location you ask for this!!)
* Node: v20.5.1
* PostgreSQL: 15.4-2.pgdg22.04+1
* Redis: 7.2.1 build=95712a67f5005c28
* OS and Architecture: Ubuntu 22.04 LTS x86_64

**Comment by spirillen** [comment]
Any update to this issue?? I for sure is missing access to my account https://matrix.rocks/@jerry

**Comment by spirillen** [comment]
Anyone who have a suggestion to how I can obtain a reset link for the user account?

**Comment by spirillen** [comment]
This issue reappears, once I click `Really reset your password?` the popup are closing, and nothing else are happening... what have been changed, or what is needed? the user have a confirmed and valid mailaddress, and I recall it, as the popup showed the new password?

<img width="628" height="313" alt="Image" src="https://github.com/user-attachments/assets/277e5f2c-5f55-47a2-8e68-2d38187eae73" />

This is all I see after confirming

<img width="644" height="311" alt="Image" src="https://github.com/user-attachments/assets/b5001ddc-5b38-4d4a-a430-abbd7e73f848" />

The reset email, ain't working either... and it is even giving the impression when you type a wrong mail, that everything is fine

<img width="373" height="393" alt="Image" src="https://github.com/user-attachments/assets/64508a86-7ecd-447c-865d-ae3218ab4877" />

**Comment by spirillen** [comment]
Found this in my log

```log
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]: ERR  *        [api]        Internal error occurred in admin/reset-password: cannot reset password of root {
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:   ep: 'admin/reset-password',
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:   ps: { userId: 'a6lzp3eh2i', i: 'b5s6KW8JQqxkZe1n' },
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:   e: {
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:     message: 'cannot reset password of root',
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:     code: 'Error',
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:     stack: 'Error: cannot reset password of root\n' +
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:       '    at file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/admin/reset-password.js:72:23\n' +
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)\n' +
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:       '    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:389:20)',
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:     id: '92a6c96b-8dcd-4a2e-9819-06eb872cb710'
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]:   }
Dec 12 15:32:25 ns3197353 "matrix.rocks"[372459]: }

```

**Comment by spirillen** [comment]
And for the mail to password reset, I do know that this is caused by the very very short text of reset password

```
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]: ERR  *        [email]        Error: Message failed: 554 5.7.1 Spam message rejected {
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:   e: Error: Message failed: 554 5.7.1 Spam message rejected
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at SMTPConnection._formatError (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at SMTPConnection._actionSMTPStream (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:1737:34)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at SMTPConnection.<anonymous> (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:1198:22)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at SMTPConnection._processResponse (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at SMTPConnection._onData (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at SMTPConnection._onSocketData (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at TLSSocket.emit (node:events:508:28)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at addChunk (node:internal/streams/readable:559:12)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at Readable.push (node:internal/streams/readable:390:5)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:       at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23) {
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     code: 'EMESSAGE',
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     response: '554 5.7.1 Spam message rejected',
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     responseCode: 554,
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     command: 'DATA'
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:   }
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]: }
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]: Error: Message failed: 554 5.7.1 Spam message rejected
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at SMTPConnection._formatError (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at SMTPConnection._actionSMTPStream (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:1737:34)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at SMTPConnection.<anonymous> (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:1198:22)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at SMTPConnection._processResponse (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at SMTPConnection._onData (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at SMTPConnection._onSocketData (/home/misskey/misskey/node_modules/.pnpm/nodemailer@7.0.11/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at TLSSocket.emit (node:events:508:28)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at addChunk (node:internal/streams/readable:559:12)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at Readable.push (node:internal/streams/readable:390:5)
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23) {
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:   code: 'EMESSAGE',
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:   response: '554 5.7.1 Spam message rejected',
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:   responseCode: 554,
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]:   command: 'DATA'
Dec 12 15:36:18 ns3197353 "matrix.rocks"[372459]: }
```
