### ISSUE TITLE
Misskey 2023.10.2 is running abnormally

### ISSUE THREAD

**Issue by MomentQYC** [syuilo/Misskey#12104]
## 💡 Summary

Numerous errors were reported and the timeline was not working

## 🥰 Expected Behavior

Normal use after upgrade

## 🤬 Actual Behavior

A large number of errors are reported, examples of which are as follows
```
misskey-web-1  | WARN 1 [queue inbox]   failed(UnrecoverableError: skip: failed to resolve user) id=797327 attempts=1/8 age=8ms activity=https://(Post)
misskey-web-1  | WARN 2 [queue inbox]   failed(UnrecoverableError: skip: failed to resolve user) id=797328 attempts=1/8 age=7ms activity=https://(Post)
misskey-web-1  | WARN 1 [queue inbox]   failed(UnrecoverableError: skip: failed to resolve user) id=797329 attempts=1/8 age=7ms activity=https://(Post)
misskey-web-1  | INFO 2 [queue check-expired-mutings]   Checking expired mutings...
misskey-web-1  | WARN 2 [queue system]  failed(QueryFailedError: column muting.createdAt does not exist) id=repeat:e456d804f4cee04d9f14f9d6867a8dcf:1697883900000
misskey-web-1  | WARN 1 [queue inbox]   failed(QueryFailedError: column MiUser.createdAt does not exist) id=797146 attempts=3/8 age=4m activity=https://(Post)
```

## 📝 Steps to Reproduce

1. `docker compose up -d --build`
2. Not working properly

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2023.10.2
* Node: 20.8.1
* PostgreSQL: 16
* Redis: 7.0.11
* OS and Architecture:  Ubuntu 22.04.3 amd64

**Comment by MomentQYC** [comment]
Accessing `/queue` gives the following error
```
{"error":"Internal server error","message":"column MiUser.createdAt does not exist","details":"QueryFailedError: column MiUser.createdAt does not exist\n
    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)\n
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n
    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)\n
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2034:26)\n
    at async SelectQueryBuilder.getRawAndEntities (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)\n
    at async SelectQueryBuilder.getOne (/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)\n
    at async Object.<anonymous> (file:///misskey/packages/backend/built/server/web/ClientServerService.js:200:30)"}
```

**Comment by Candinya** [comment]
Caused by this commit I think 1fa1d316969de15d6aaef1dbf0a0b95aec30e377

**Comment by MomentQYC** [comment]
This problem was solved by running `npm start` manually for me, so if you're using Docker as well, check out my solution to this problem.

**Comment by Candinya** [comment]
Not reproduced on NyaOne (running on Docker), might be an occasional error?

**Comment by sasagar** [comment]
I'm facing this issue now, updating from 2023.9.3 to 2023.11.0.

**Comment by hikalium** [comment]
Here is another instance affected by this issue 🙌  (In my case, it happened when updating misskey from `2023.9.0` to `2023.12.0`)

And I think I found a workaround 😉 - TL; DR
```
# cd /path/to/misskey
rm -rf packages/backend/built
sudo docker-compose stop
sudo docker-compose rm
sudo docker-compose build --no-cache --force-rm
sudo docker-compose run --rm web pnpm run init
sudo docker-compose up -d
```

It looks like the issue happens when the backend server is not built from the updated source since there are cached artifacts in `packages/backend/built` (I think this cache is generated when I tried building the Misskey server without Docker before switching to the Docker-based workflow). So removing them and rebuilding the container images cleanly with docker-compose fixes the problem.

Although I'm not sure if it is the right way, I hope it helps!
