### ISSUE TITLE
Unable to Register Physical Security Key

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#12115]
## 💡 Summary

When trying to register a **Physical Security Key** in the account security settings, an error occurs in the API, causing the registration to fail. Registering a **Passkey** is working fine.

## 🥰 Expected Behavior

You can register a physical security key for your account without any errors.

## 🤬 Actual Behavior

<details>
<summary>api request `i/2fa/register-key`</summary>

Payload
```
{"password":"[redacted]","token":"490804","i":"[redacted]"}
```

Respones
```
{
    "challenge": "rF0[redacted]ZR4",
    "rp": {
        "name": "local",
        "id": "misskey.local"
    },
    "user": {
        "id": "9l2d2hq423",
        "name": "test",
        "displayName": "test"
    },
    "pubKeyCredParams": [
        {
            "alg": -8,
            "type": "public-key"
        },
        {
            "alg": -7,
            "type": "public-key"
        },
        {
            "alg": -257,
            "type": "public-key"
        }
    ],
    "timeout": 60000,
    "attestation": "indirect",
    "excludeCredentials": [
        {
            "id": "reb[redacted]NeA",
            "type": "public-key"
        }
    ],
    "authenticatorSelection": {
        "residentKey": "required",
        "userVerification": "preferred",
        "requireResidentKey": true
    },
    "extensions": {
        "credProps": true
    }
}
```
</details>

<details>
<summary>api request `i/2fa/key-done`</summary>

Payload
```
{"password":"[redacted]","token":"490804","name":"TEST","credential":{"type":"public-key","id":"6DReq[redacted]tyZ_0","rawId":"6DReq[redacted]tyZ_0","authenticatorAttachment":"cross-platform","response":{"clientDataJSON":"eyJ0e[redacted]HNlfQ","attestationObject":"o2Nmb[redacted]CRult","transports":[]},"clientExtensionResults":{"credProps":{"rk":true}}},"i":"[redacted]"}
```

Respones
```
{
    "error": {
        "message": "Internal error occurred. Please contact us if the error persists.",
        "code": "INTERNAL_ERROR",
        "id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
        "kind": "server",
        "info": {
            "e": {
                "message": "verification failed",
                "code": "Error",
                "id": "1ff379f5-9911-47c8-af71-20c97d84c7e4"
            }
        }
    }
}
```
</details>

<details>
<summary>server log</summary>

```
Error: Certificate not good after "Sun Oct 22 2023 00:43:10 GMT+0000 (Coordinated Universal Time)" (Packed|Full)
    at verifyAttestationPacked (file:///node_modules/.pnpm/@simplewebauthn+server@8.3.2/node_modules/@simplewebauthn/server/esm/registration/verifications/verifyAttestationPacked.js:55:19)
    at verifyRegistrationResponse (file:///node_modules/.pnpm/@simplewebauthn+server@8.3.2/node_modules/@simplewebauthn/server/esm/registration/verifyRegistrationResponse.js:164:26)
    at async WebAuthnService.verifyRegistration (file:///packages/backend/built/core/WebAuthnService.js:80:28)
    at async file:///packages/backend/built/server/api/endpoints/i/2fa/key-done.js:99:29
    at async ApiCallService.call (file:///packages/backend/built/server/api/ApiCallService.js:317:16)
ERR  *  [api]   Internal error occurred in i/2fa/key-done: verification failed
{
  ep: 'i/2fa/key-done',
  ps: {
    password: '[redacted]',
    token: '490804',
    name: 'TEST',
    credential: {
      type: 'public-key',
      id: '6DReq[redacted]tyZ_0',
      rawId: '6DReq[redacted]tyZ_0',
      authenticatorAttachment: 'cross-platform',
      response: [Object],
      clientExtensionResults: [Object]
    },
    i: '[redacted]'
  },
  e: {
    message: 'verification failed',
    code: 'Error',
    stack: 'Error: verification failed\n' +
      '    at WebAuthnService.verifyRegistration (file:///packages/backend/built/core/WebAuthnService.js:89:19)\n' +
      '    at async file:///packages/backend/built/server/api/endpoints/i/2fa/key-done.js:99:29\n' +
      '    at async ApiCallService.call (file:///packages/backend/built/server/api/ApiCallService.js:317:16)',
    id: '1ff379f5-9911-47c8-af71-20c97d84c7e4'
  }
}
IdentifiableError: verification failed
    at WebAuthnService.verifyRegistration (file:///packages/backend/built/core/WebAuthnService.js:89:19)
    at async file:///packages/backend/built/server/api/endpoints/i/2fa/key-done.js:99:29
    at async ApiCallService.call (file:///packages/backend/built/server/api/ApiCallService.js:317:16) {
  id: '5c1446f8-8ca7-4d31-9f39-656afe9c5d87'
} 1ff379f5-9911-47c8-af71-20c97d84c7e4
```
</details>

## 📝 Steps to Reproduce

1. Attempt to register a physical security key in `/settings/security`
2. Error

### 💻 Frontend
* Model and OS of the device(s):
  Windows 11 Pro Insider Preview 23550.1000
* Browser:
  Chrome 118.0.5993.89 (Official build) dev (64-bit)
* Server URL:
  local and two other servers
* Misskey:
  Verified in `2023.9.1` ~ `2023.11.0-beta.2`

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: docker compose, k8s/docker, dev env
* Misskey: Verified in `2023.9.1` ~ `2023.11.0-beta.2`
* Node: 20.5.1
* PostgreSQL: 15
* Redis: 7
* OS and Architecture: Docker (debian bullseye)

**Comment by tamaina** [comment]
It has been inactive for a long time so I will close it. Please reopen if the problem has not yet been resolved.
