### ISSUE TITLE
Internal Error on hashtags/trend

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#12144]
## 💡 Summary

hashtags/trendでエラー
```
ERR  *  [api]   Internal error occurred in hashtags/trend: Cannot read properties of undefined (reading 'length')
{
  ep: 'hashtags/trend',
  ps: {},
  e: {
    message: "Cannot read properties of undefined (reading 'length')",
    code: 'TypeError',
    stack: "TypeError: Cannot read properties of undefined (reading 'length')\n" +
      '    at FeaturedService.getRankingOf (file:///home/taichan/misskey/packages/backend/built/core/FeaturedService.js:48:50)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async file:///home/taichan/misskey/packages/backend/built/server/api/endpoints/hashtags/trend.js:60:29\n' +
      '    at async ApiCallService.call (file:///home/taichan/misskey/packages/backend/built/server/api/ApiCallService.js:328:16)',
    id: '1e84049d-03d1-451a-971e-b1aeed08142b'
  }
}
TypeError: Cannot read properties of undefined (reading 'length')
    at FeaturedService.getRankingOf (file:///home/taichan/misskey/packages/backend/built/core/FeaturedService.js:48:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/taichan/misskey/packages/backend/built/server/api/endpoints/hashtags/trend.js:60:29
    at async ApiCallService.call (file:///home/taichan/misskey/packages/backend/built/server/api/ApiCallService.js:328:16) 1e84049d-03d1-451a-971e-b1aeed08142b
```

## 🥰 Expected Behavior

エラーが起きない

## 🤬 Actual Behavior

エラーが起きる（実際にトレンド欄がずっとローディング中表示になる）

## 📝 Steps to Reproduce

1. MisskeyをPullしてきて開始する
2. ログにエラーが出る

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  2023.11.0-beta3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: v2023.11.0-beta.3
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by tai-cha** [comment]
修正かけてるのでPushする
