### ISSUE TITLE
Failed to create drive file: RequestError: ipaddr: cannot match ipv6 address with non-ipv6 one

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#12335]
### 💡 Summary

When this happens, the entire inbox import stalls.

```bash
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: WARN 1        [queue inbox]        failed(UnrecoverableError: Blocked request: mastodon.hongkongers.net) id=5086227 attempts=1/8 age=471m activity=https://mastodon.hongkongers.net/users/ctvbc_mirror/statuses/111409954078897199/activity
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: INFO 1        [download]        Downloading https://media.misskey.cloud/files/66182368-f8c0-4d4a-bb13-f0cb9c57802f.png to /tmp/tmp-9552-us3uzTLVQd4P ...
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: INFO 1        [remote ap]        Creating the Note: https://koliosky.com/notes/9m253lvwi9
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: INFO 1        [download]        Downloading https://media.misskey.cloud/files/8c2c7275-d907-46a3-8a3b-f34edb63fd72.webp to /tmp/tmp-9552-90C2EkE45vJM ...
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: DONE 1        [download]        Download finished: https://equestria.social/system/media_attachments/files/111/409/951/033/884/857/original/bc5d7670437ff1fe.png
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: INFO 1        [drive register]        {"size":1135049,"md5":"8486a2a428162caab65b680729faea09","type":{"mime":"image/png","ext":"png"},"width":1991,"height":1642,"blurhash":"eXS63=ob?^x^RP%gofe.axRjxwkDSbadV[tQaeR6bItRocoza#V@t7","sensitive":false,"porn":false,"warnings":[]}
Nov 15 00:47:30 ns3109441 "matrix.rocks"[9552]: INFO 1        [drive register]        web image not created (original satisfies webpublic)
Nov 15 00:47:31 ns3109441 "matrix.rocks"[9552]: INFO 1        [drive register]        thumbnail stored: thumbnail-f26450fc-9cd4-4724-a4ba-fee66a355dd2
Nov 15 00:47:31 ns3109441 "matrix.rocks"[9552]: DONE 1        [drive register]        drive file has been created 9m2lxehtnb
Nov 15 00:47:31 ns3109441 "matrix.rocks"[9552]: DONE 1        [drive downloader]        Got: 9m2lxehtnb
Nov 15 00:47:31 ns3109441 "matrix.rocks"[9552]: INFO 1        [remote ap]        Creating the Note: https://vmst.io/users/Phangurl/statuses/111409953429189159
Nov 15 00:47:31 ns3109441 "matrix.rocks"[9552]: INFO 1        [remote ap]        Creating the (Re)Note: https://relay.publicsquare.global/activity/707e06dc-0e34-464f-ae62-cb12e01cb043
Nov 15 00:47:31 ns3109441 "matrix.rocks"[9552]: INFO 1        [remote ap]        Creating the (Re)Note: https://rel.re/activity/449c4b01-754b-4676-a1c1-ee93521fa3ac
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]: ERR  1        [drive downloader]        Failed to create drive file: RequestError: ipaddr: cannot match ipv6 address with non-ipv6 one
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:   url: 'https://media.misskey.cloud/files/8c2c7275-d907-46a3-8a3b-f34edb63fd72.webp',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:   e: RequestError: ipaddr: cannot match ipv6 address with non-ipv6 one
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Request._beforeError (file:///home/misskey/misskey/node_modules/.pnpm/got@13.0.0/node_modules/got/dist/source/core/index.js:310:21)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Request._onResponse (file:///home/misskey/misskey/node_modules/.pnpm/got@13.0.0/node_modules/got/dist/source/core/index.js:772:18)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at ipaddr.IPv6.IPv6.match (/home/misskey/misskey/node_modules/.pnpm/ipaddr.js@2.1.0/node_modules/ipaddr.js/lib/ipaddr.js:578:23)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at DownloadService.isPrivateIp (file:///home/misskey/misskey/packages/backend/built/core/DownloadService.js:135:26)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Request.<anonymous> (file:///home/misskey/misskey/packages/backend/built/core/DownloadService.js:73:26)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Request.emit (node:events:514:28)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Request._onResponseBase (file:///home/misskey/misskey/node_modules/.pnpm/got@13.0.0/node_modules/got/dist/source/core/index.js:730:14)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Request._onResponse (file:///home/misskey/misskey/node_modules/.pnpm/got@13.0.0/node_modules/got/dist/source/core/index.js:768:24)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at ClientRequest.<anonymous> (file:///home/misskey/misskey/node_modules/.pnpm/got@13.0.0/node_modules/got/dist/source/core/index.js:786:23)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Object.onceWrapper (node:events:629:26)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at ClientRequest.emit (node:events:526:35)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at TLSSocket.socketOnData (node:_http_client:535:22)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at TLSSocket.emit (node:events:514:28)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at addChunk (node:internal/streams/readable:343:12)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at readableAddChunk (node:internal/streams/readable:316:9)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at Readable.push (node:internal/streams/readable:253:10)
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:     input: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:     code: 'ERR_GOT_REQUEST_ERROR',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:     timings: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       start: 1700009250888,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       socket: 1700009250888,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       lookup: 1700009250911,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       connect: 1700009251418,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       secureConnect: 1700009251938,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       upload: 1700009251938,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       response: 1700009252525,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       end: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       error: 1700009282784,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       abort: 1700009282783,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       phases: [Object]
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:     },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:     options: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       request: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       agent: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         http: Agent {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _events: [Object: null prototype],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _eventsCount: 2,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _maxListeners: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           defaultPort: 80,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           protocol: 'http:',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           options: [Object: null prototype],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           requests: [Object: null prototype] {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           sockets: [Object: null prototype] {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           freeSockets: [Object: null prototype] {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           keepAliveMsecs: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           keepAlive: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxSockets: Infinity,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxFreeSockets: 256,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           scheduling: 'lifo',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxTotalSockets: Infinity,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           totalSocketCount: 0,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           [Symbol(kCapture)]: false
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         https: Agent {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _events: [Object: null prototype],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _eventsCount: 2,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _maxListeners: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           defaultPort: 443,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           protocol: 'https:',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           options: [Object: null prototype],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           requests: [Object: null prototype] {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           sockets: [Object: null prototype] {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           freeSockets: [Object: null prototype],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           keepAliveMsecs: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           keepAlive: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxSockets: Infinity,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxFreeSockets: 256,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           scheduling: 'lifo',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxTotalSockets: Infinity,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           totalSocketCount: 18,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           maxCachedSessions: 100,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           _sessionCache: [Object],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           [Symbol(kCapture)]: false
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         http2: undefined
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       h2session: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       decompress: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       timeout: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         connect: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         lookup: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         read: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         request: 60000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         response: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         secureConnect: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         send: 30000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         socket: 30000
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       prefixUrl: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       body: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       form: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       json: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       cookieJar: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       ignoreInvalidCookies: false,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       searchParams: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       dnsLookup: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       dnsCache: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       context: {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       hooks: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         init: [],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         beforeRequest: [],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         beforeError: [],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         beforeRedirect: [],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         beforeRetry: [],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         afterResponse: []
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       followRedirect: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       maxRedirects: 10,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       cache: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       throwHttpErrors: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       username: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       password: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       http2: false,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       allowGetBody: false,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       headers: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         'user-agent': 'Misskey/2023.11.0 (https://matrix.rocks)',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         'accept-encoding': 'gzip, deflate, br'
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       methodRewriting: false,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       dnsLookupIpVersion: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       parseJson: [Function: parse],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       stringifyJson: [Function: stringify],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       retry: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         limit: 0,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         statusCodes: [
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           408, 413, 429, 500,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           502, 503, 504, 521,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           522, 524
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         ],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         errorCodes: [
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'ETIMEDOUT',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'ECONNRESET',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'EADDRINUSE',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'ECONNREFUSED',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'EPIPE',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'ENOTFOUND',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'ENETUNREACH',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:           'EAI_AGAIN'
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         ],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         maxRetryAfter: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         calculateDelay: [Function: calculateDelay],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         backoffLimit: Infinity,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         noise: 100
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       localAddress: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       method: 'GET',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       createConnection: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       cacheOptions: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         shared: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         cacheHeuristic: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         immutableMinTimeToLive: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         ignoreCargoCult: undefined
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       https: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         alpnProtocols: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         rejectUnauthorized: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         checkServerIdentity: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         certificateAuthority: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         key: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         certificate: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         passphrase: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         pfx: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         ciphers: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         honorCipherOrder: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         minVersion: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         maxVersion: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         signatureAlgorithms: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         tlsSessionLifetime: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         dhparam: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         ecdhCurve: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         certificateRevocationLists: undefined
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       encoding: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       resolveBodyOnly: false,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       isStream: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       responseType: 'text',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       url: URL {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         href: 'https://media.misskey.cloud/files/8c2c7275-d907-46a3-8a3b-f34edb63fd72.webp',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         origin: 'https://media.misskey.cloud',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         protocol: 'https:',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         username: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         password: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         host: 'media.misskey.cloud',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         hostname: 'media.misskey.cloud',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         port: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         pathname: '/files/8c2c7275-d907-46a3-8a3b-f34edb63fd72.webp',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         search: '',
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         searchParams: URLSearchParams {},
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         hash: ''
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       pagination: {
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         transform: [Function: transform],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         paginate: [Function: paginate],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         filter: [Function: filter],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         shouldContinue: [Function: shouldContinue],
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         countLimit: Infinity,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         backoff: 0,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         requestLimit: 10000,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:         stackAllItems: false
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       },
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       setHost: true,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       maxHeaderSize: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       signal: undefined,
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:       enableUnixSockets: false
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:     }
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]:   }
Nov 15 00:48:02 ns3109441 "matrix.rocks"[9552]: }
Nov 15 00:48:29 ns3109441 "matrix.rocks"[9552]: WARN 1        [queue inbox]        stalled id=5086192
```

### 🥰 Expected Behavior

stick to ipv4 when ipv4 is served | same for ipv6

### 🤬 Actual Behavior

See log above... trying to use ipv4 as ipv6

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: matrix.rocks
* Misskey: v2023.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: bash script
* Misskey: v2023.11.0
* Node: 20 
* PostgreSQL: 15 
* Redis: 7
* OS and Architecture: ubuntu 22.04
```

**Comment by skid9000** [comment]
I have that same error but in the other way : RequestError: ipaddr: cannot match ipv4 address with non-ipv4 one

**Comment by skid9000** [comment]
The problem seems to have appeared in the ipaddr.js module update from 1.9.1 to 2.1.0.

https://github.com/whitequark/ipaddr.js/issues/165
