### ISSUE TITLE
[Misskey 2023.12.0-beta.1] 設定のテーマを開くと永遠にローディングする

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [syuilo/Misskey#12547]
### 💡 Summary

#12536 ( #12528 ) の修正で、パスの呼び先を`__dirname`に変えましたが、ブラウザで設定のテーマを開くと永遠にローディングする状態となっているようです。
Chromeの開発者コンソールで動作を確認すると、下記のエラーが表示されていました。

```
theme.ts:47 Uncaught (in promise) ReferenceError: __dirname is not defined
    at theme.ts:47:35
    at Array.map (<anonymous>)
    at getBuiltinThemes (theme.ts:47:4)
    at getBuiltinThemesRef (theme.ts:52:2)
    at setup (theme.vue:93:23)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7323:25)
    at setupComponent (runtime-core.esm-bundler.js:7284:36)
    at mountComponent (runtime-core.esm-bundler.js:5679:7)
    at processComponent (runtime-core.esm-bundler.js:5645:9)
```

### 🥰 Expected Behavior

設定のテーマ画面が開く

### 🤬 Actual Behavior

設定のテーマ画面が開かない

### 📝 Steps to Reproduce

1. `pnpm dev`でMisskeyを起動する
2. 設定のテーマを開く

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): macOS Ventura 13.5.1
* Browser: Chrome 119.0
* Server URL: localhost
* Misskey: 2023.12.0-beta.1 (developブランチ)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: development environment (devcontainer)
* Misskey: 2023.12.0-beta.1 (developブランチの12/1時点)
* Node: v20.10.0
* PostgreSQL:
* Redis:
* OS and Architecture: macOS Ventura 13.5.1
```

**Comment by samunohito** [comment]
pnpm startで起動した場合も再現しました。確認します
