### ISSUE TITLE
非標準httpsポートのサーバ追加中継失敗

### ISSUE THREAD

**Issue by rushfly** [syuilo/Misskey#12645]
### 💡 Summary

中継を追加した時彼らはずっと“承認待ち”状態でした。
Bull Dashboardからコピーされたエラー情報：

```
AbortError: The operation was aborted.
    at abort (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:70:18)
    at EventTarget.abortAndFinalize (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:89:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at EventTarget.dispatchEvent (node:internal/event_target:749:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Timeout._onTimeout (file:///misskey/packages/backend/built/core/HttpRequestService.js:118:24)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
AbortError: The operation was aborted.
    at abort (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:70:18)
    at EventTarget.abortAndFinalize (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:89:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at EventTarget.dispatchEvent (node:internal/event_target:749:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Timeout._onTimeout (file:///misskey/packages/backend/built/core/HttpRequestService.js:118:24)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
AbortError: The operation was aborted.
    at abort (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:70:18)
    at EventTarget.abortAndFinalize (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:89:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at EventTarget.dispatchEvent (node:internal/event_target:749:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Timeout._onTimeout (file:///misskey/packages/backend/built/core/HttpRequestService.js:118:24)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
FetchError: request to https://relay.isle.moe/inbox failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:526:35)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
AbortError: The operation was aborted.
    at abort (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:70:18)
    at EventTarget.abortAndFinalize (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:89:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at EventTarget.dispatchEvent (node:internal/event_target:749:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Timeout._onTimeout (file:///misskey/packages/backend/built/core/HttpRequestService.js:118:24)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
AbortError: The operation was aborted.
    at abort (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:70:18)
    at EventTarget.abortAndFinalize (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:89:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at EventTarget.dispatchEvent (node:internal/event_target:749:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Timeout._onTimeout (file:///misskey/packages/backend/built/core/HttpRequestService.js:118:24)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
AbortError: The operation was aborted.
    at abort (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:70:18)
    at EventTarget.abortAndFinalize (file:///misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:89:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at EventTarget.dispatchEvent (node:internal/event_target:749:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Timeout._onTimeout (file:///misskey/packages/backend/built/core/HttpRequestService.js:118:24)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
私のリバースプロキシが非標準httpsポート(443ではありません)を使用しているのかもしれませんが、解決策はありますか？
すみませんが翻訳機が私の意味を正確に表現できないかもしれません。

### 🥰 Expected Behavior

非標準ポートのサーバは中継を正常に追加することができる

### 🤬 Actual Behavior

中継は“承認待ち”状態であり，様々な中継を試みたが，情報を交換することはできなかった.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:Edge 120.0.2210.61 (64bit)
* Server URL: 
* Misskey:2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:  docker compose
* Misskey:2023.11.1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture: Synology NAS D918+
```

**Comment by ryanho** [comment]
你的問題基本無解，因為relay要做follow back，misskey只能跟對方說要連的網域，沒辦法指定port。這算是標準的作法，換成mastodon也會有相同的問題。
而且你的設置會造成其他實例的用戶跟你的實例用戶無法互相追隨。
