### ISSUE TITLE
Threadsのアカウントを照会するとエラーが出る

### ISSUE THREAD

**Issue by Soli0222** [syuilo/Misskey#12665]
### 💡 Summary

Threadsの特定のアカウント (例: https://www.threads.net/@mosseri)  が制限付きでActivityPubに接続され、これにより観測が可能になりました。しかし、Misskeyを使用して照会を試みると、``FetchError: content size over limit: 262144``というエラーが発生し、ユーザーページを開くことができません。

私が運営している``mi.soli0222.com``で確認したのと同時に、他のサーバー``misskey.cloud`` ``misskey.systems`` ``misskey.backspace.fm``でも同様のエラーが発生するのを確認しています。(``misskey.io``は何故か連合できていました)

運営しているサーバーでのエラーは以下の通りです。
```
Dec 14 22:46:21 misskey-host misskey[10299]: ERR  *        [api]        Internal error occurred in ap/show: content size at https://www.threads.net/@mosseri over limit: 262144
Dec 14 22:46:21 misskey-host misskey[10299]: {
Dec 14 22:46:21 misskey-host misskey[10299]:   ep: 'ap/show',
Dec 14 22:46:21 misskey-host misskey[10299]:   ps: { uri: 'https://www.threads.net/@mosseri', i: ‘xxxxxxxxxxxxxxxx’ },
Dec 14 22:46:21 misskey-host misskey[10299]:   e: {
Dec 14 22:46:21 misskey-host misskey[10299]:     message: 'content size at https://www.threads.net/@mosseri over limit: 262144',
Dec 14 22:46:21 misskey-host misskey[10299]:     code: 'FetchError',
Dec 14 22:46:21 misskey-host misskey[10299]:     stack: 'FetchError: content size at https://www.threads.net/@mosseri over limit: 262144\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at consumeBody (file:///home/misskey/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/body.js:225:19)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async Response.text (file:///home/misskey/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/body.js:158:18)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async Response.json (file:///home/misskey/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/body.js:148:16)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async HttpRequestService.getJson (file:///home/misskey/misskey/packages/backend/built/core/HttpRequestService.js:100:16)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async Resolver.resolve (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApResolverService.js:108:94)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async _$class.fetchAny (file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:140:24)\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:111:28\n' +
Dec 14 22:46:21 misskey-host misskey[10299]:       '    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:16)',
Dec 14 22:46:21 misskey-host misskey[10299]:     id: '86033414-9148-4642-94e4-53d121dfbff1'
Dec 14 22:46:21 misskey-host misskey[10299]:   }
Dec 14 22:46:21 misskey-host misskey[10299]: }
Dec 14 22:46:21 misskey-host misskey[10299]: FetchError: content size at https://www.threads.net/@mosseri over limit: 262144
Dec 14 22:46:21 misskey-host misskey[10299]:     at consumeBody (file:///home/misskey/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/body.js:225:19)
Dec 14 22:46:21 misskey-host misskey[10299]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 14 22:46:21 misskey-host misskey[10299]:     at async Response.text (file:///home/misskey/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/body.js:158:18)
Dec 14 22:46:21 misskey-host misskey[10299]:     at async Response.json (file:///home/misskey/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/body.js:148:16)
Dec 14 22:46:21 misskey-host misskey[10299]:     at async HttpRequestService.getJson (file:///home/misskey/misskey/packages/backend/built/core/HttpRequestService.js:100:16)
Dec 14 22:46:21 misskey-host misskey[10299]:     at async Resolver.resolve (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApResolverService.js:108:94)
Dec 14 22:46:21 misskey-host misskey[10299]:     at async _$class.fetchAny (file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:140:24)
Dec 14 22:46:21 misskey-host misskey[10299]:     at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:111:28
Dec 14 22:46:21 misskey-host misskey[10299]:     at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:16) {
Dec 14 22:46:21 misskey-host misskey[10299]:   type: 'max-size'
Dec 14 22:46:21 misskey-host misskey[10299]: } 86033414-9148-4642-94e4-53d121dfbff1
```

### 🥰 Expected Behavior

他のActivityPubが実装されたサーバー同様に、照会を行うとユーザーページが作成される

### 🤬 Actual Behavior

``FetchError: content size at https://www.threads.net/@mosseri over limit: 262144`` となり、失敗する

### 📝 Steps to Reproduce

1. 照会に ``https://www.threads.net/@mosseri`` と入力してOK (もしくはap/showにて同様のURLを入力しリクエストを行う)
2. エラーが出る

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): M2 MacBook Air macOS 14.2
* Browser: Google Chrome 120.0.6099.71（Official Build） 
* Server URL: mi.soli0222.com
* Misskey: 2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd / Xserver VPS
* Misskey: 2023.11.1
* Node: v20.5.1
* PostgreSQL: psql (PostgreSQL) 15.5 (Ubuntu 15.5-1.pgdg22.04+1)
* Redis: redis-cli 7.2.3
* OS and Architecture: Ubuntu 22.04.3 LTS
```

**Comment by CyberRex0** [comment]
HTMLが返ってきているからだと思います

**Comment by kakkokari-gtyih** [comment]
Threads側の実装が不完全なのでそっちの修正を待ったほうが良いかも

**Comment by Soli0222** [comment]
無限にcurlで送ってもHTMLしか返ってこないかつ、そんな感じの投稿もいくつか見かけたので一旦閉じます。
