### ISSUE TITLE
Can't process Accept activity after Follow when `activity.actor` doesn't exist

### ISSUE THREAD

**Issue by pfefferle** [syuilo/Misskey#12720]
### 💡 Summary

I am the maintainer of the WordPress ActivityPub plugin: https://wordpress.org/plugins/activitypub/

I tried to follow my Blogs User Account and the process stucks "In progress". The Blog receives the Follow Request and also sends the Accept response and Misskey seem to be fine with the Accept:

```
[status_code] => 202
[protocol_version] => 1.1
[success] => 1
[redirects] => 0
[url] => https://misskey.io/inbox
[history] => Array()
```

When I try to refresh the profile I receive the following error:

```
Endpoint: federation/update-remote-user
Info: {"e":{"message":"Cannot perform update query because update values are not defined. Call \"qb.set(...)\" method to specify updated values.","code":"UpdateValuesMissingError","id":"636723f6-a119-4a1e-b824-346150f611bb"}}
Date: 2023-12-19T17:17:23.482Z
```

I already experimented with Misskey some 4 month ago without issues:

<img width="319" alt="Screenshot 2023-12-19 at 19 48 38" src="https://github.com/misskey-dev/misskey/assets/2373/ee4d3d30-668c-4b15-95ce-ed39e5ff47ab">

The IDs I tried are:
* @pfefferle@notiz.blog or https://notiz.blog/author/matthias-pfefferle/ (Person)
* @notiz.blog@notiz.blog or https://notiz.blog/@notiz.blog (Group)

### 🥰 Expected Behavior

It should be possible to follow a User on a WordPress Blog and to refresh the profile informations.

### 🤬 Actual Behavior

See summary.

### 📝 Steps to Reproduce

1. Go to a misskey instance
2. search for `@pfefferle@notiz.blog`
3. Press "Follow" button
4. Try to refresh the profile

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Mac OS X
* Browser: Firefox
* Server URL: https://misskey.io/
* Misskey: v2023.11.1-io.5a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: misskey.io
* Misskey: v2023.11.1-io.5a
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by saschanaz** [comment]
>Info: {"e":{"message":"Cannot perform update query because update values are not defined. Call \"qb.set(...)\" method to specify updated values.","code":"UpdateValuesMissingError","id":"636723f6-a119-4a1e-b824-346150f611bb"}}

That's definitely a TypeORM error 🤔

**Comment by saschanaz** [comment]
The server side log says:

>WARN 1  [queue inbox]   failed(TypeError: Cannot read properties of undefined (reading 'id')) id=288775 attempts=1/8 age=12ms activity=https://notiz.blog/author/matthias-pfefferle/#follow-sekai.social/users/9ke0mh0ps3ln0008-1703082733

`id` is undefined? 🤔🤔🤔🤔

**Comment by saschanaz** [comment]
The server side log says:

>WARN 1  [queue inbox]   failed(TypeError: Cannot read properties of undefined (reading 'id')) id=288775 attempts=1/8 age=12ms activity=https://notiz.blog/author/matthias-pfefferle/...

`id` is undefined? 🤔🤔🤔🤔

**Comment by pfefferle** [comment]
So the ID-URI needs to be publicly Accessible even for an `Accept`?

**Comment by saschanaz** [comment]
I'll have to dig more as I'm not very familiar with typeorm and the log doesn't say the line number, but the error should be from somewhere here or below:

https://github.com/misskey-dev/misskey/blob/10d4ae107bef82f988d39c40aa528c720612209a/packages/backend/src/core/activitypub/models/ApPersonService.ts#L488-L496

Since the actor information is already fetched, the function just loads it from the local data, which should include the ID:

https://github.com/misskey-dev/misskey/blob/10d4ae107bef82f988d39c40aa528c720612209a/packages/backend/src/core/activitypub/models/ApPersonService.ts#L417-L418

> So the ID-URI needs to be publicly accessible even for an `Accept`?

Per the above I would say no. Maybe the initial fetch for the actor goes wrong?

**Comment by saschanaz** [comment]
> The server side log says:
> 
> > WARN 1  [queue inbox]   failed(TypeError: Cannot read properties of undefined (reading 'id')) id=288775 attempts=1/8 age=12ms activity=https://notiz.blog/author/matthias-pfefferle/...
> 
> `id` is undefined? 🤔🤔🤔🤔

Hmm, that one actually seems more like a general JS error. Can `exist` be `undefined`, when the code checks only `null`? (`== null` is generally better IMO.)

**Comment by saschanaz** [comment]
> When I try to refresh the profile I receive the following error:
> 
> ```
> Endpoint: federation/update-remote-user
> Info: {"e":{"message":"Cannot perform update query because update values are not defined. Call \"qb.set(...)\" method to specify updated values.","code":"UpdateValuesMissingError","id":"636723f6-a119-4a1e-b824-346150f611bb"}}
> Date: 2023-12-19T17:17:23.482Z
> ```

For this part, how did you trigger that endpoint? It's an admin-only endpoint that is hidden by bbef2a953ebf2f7f063641e6764ec8571cd78b75 (🤔 cc @syuilo), are you manually creating the API request?

Anyway, I did the manual request and got the stack:

```
  e: {
    message: 'Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.',
    code: 'UpdateValuesMissingError',
    stack: 'UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.\n' +
      '    at UpdateQueryBuilder.createUpdateExpression (C:\\Users\\Kagami\\Documents\\GitHub\\hitoriskey\\node_modules\\.pnpm\\typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3\\node_modules\\typeorm\\query-builder\\UpdateQueryBuilder.js:430:19)\n' +
      '    at UpdateQueryBuilder.getQuery (C:\\Users\\Kagami\\Documents\\GitHub\\hitoriskey\\node_modules\\.pnpm\\typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3\\node_modules\\typeorm\\query-builder\\UpdateQueryBuilder.js:34:21)\n' +
      '    at UpdateQueryBuilder.getQueryAndParameters (C:\\Users\\Kagami\\Documents\\GitHub\\hitoriskey\\node_modules\\.pnpm\\typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3\\node_modules\\typeorm\\query-builder\\QueryBuilder.js:274:28)\n' +
      '    at UpdateQueryBuilder.execute (C:\\Users\\Kagami\\Documents\\GitHub\\hitoriskey\\node_modules\\.pnpm\\typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3\\node_modules\\typeorm\\query-builder\\UpdateQueryBuilder.js:81:50)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async ApPersonService.updatePerson (file:///C:/Users/Kagami/Documents/GitHub/hitoriskey/packages/backend/built/core/activitypub/models/ApPersonService.js:412:9)\n' +
      '    at async file:///C:/Users/Kagami/Documents/GitHub/hitoriskey/packages/backend/built/server/api/endpoints/federation/update-remote-user.js:41:13\n' +
      '    at async ApiCallService.call (file:///C:/Users/Kagami/Documents/GitHub/hitoriskey/packages/backend/built/server/api/ApiCallService.js:316:16)',
    id: '52ae54be-ed51-45f8-a18c-71bbe31534fa'
  }
```

**Comment by saschanaz** [comment]
`curl -H 'Accept: application/activity+json'  https://notiz.blog/author/matthias-pfefferle/` gives no sharedInbox indeed, which seems the cause.

**Comment by saschanaz** [comment]
https://w3c.github.io/activitypub/#actor-objects

>sharedInbox
>    An optional endpoint [used for wide delivery of publicly addressed activities and activities sent to followers](https://w3c.github.io/activitypub/#shared-inbox-delivery). sharedInbox endpoints SHOULD also be publicly readable OrderedCollection objects containing objects addressed to the [Public](https://w3c.github.io/activitypub/#public-addressing) special collection. Reading from the sharedInbox endpoint MUST NOT present objects which are not addressed to the Public endpoint.

So it should be optional.

**Comment by saschanaz** [comment]
With #12727 I get:

```
WARN 1  [queue inbox]   failed(TypeError: Cannot read properties of undefined (reading 'id')
    at getApId (file:///misskey/packages/backend/built/core/activitypub/type.js:23:22)
    at ApDbResolverService.parseUri (file:///misskey/packages/backend/built/core/activitypub/ApDbResolverService.js:46:29)
    at ApDbResolverService.getUserFromApId (file:///misskey/packages/backend/built/core/activitypub/ApDbResolverService.js:77:29)
    at ApInboxService.acceptFollow (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:202:57)
    at ApInboxService.accept (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:197:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:141:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:119:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:167:9)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@4.11.4/node_modules/bullmq/dist/cjs/classes/worker.js:350:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@4.11.4/node_modules/bullmq/dist/cjs/classes/worker.js:535:24)) id=289285 attempts=1/8 age=12ms activity=https://notiz.blog/author/matthias-pfefferle/#follow-sekai.social/users/9ke0mh0ps3ln0008-1703112007
```

**Comment by pfefferle** [comment]
> For this part, how did you trigger that endpoint?

I used the "Update remote user information" feature.

<img width="750" alt="Screenshot 2023-12-21 at 10 50 14" src="https://github.com/misskey-dev/misskey/assets/2373/e521f470-a8e9-4276-9ee2-55f8a5afafbc">

> (sharedInbox) So it should be optional.

Yes it is optional and even if it makes sense for bigger instances with a lot of users, it does not make sense for small WordPress instances with only some few users.

**Comment by pfefferle** [comment]
I experimented with a shared inbox and then I can at least run "Update remote user information" without issues, but following is still a problem.

I use the same URL for the Actor-ID and Actor-URL, could that be an issue for Misskey?

**Comment by saschanaz** [comment]
I think the following and update-remote thing is technically separate issues, but we'll see...

**Comment by saschanaz** [comment]
> I use the same URL for the Actor-ID and Actor-URL, could that be an issue for Misskey?

That should be okay IMO. Can you check how the data look like for the Accept activity? Does it have `actor` field? I don't think this is required [per the spec](https://www.w3.org/TR/activitypub/#accept-activity-inbox), though.

**Comment by pfefferle** [comment]
Here is an `Accept` example:

```JSON
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "PropertyValue": "schema:PropertyValue",
      "schema": "http://schema.org#",
      "pt": "https://joinpeertube.org/ns#",
      "toot": "http://joinmastodon.org/ns#",
      "webfinger": "https://webfinger.net/#",
      "litepub": "http://litepub.social/ns#",
      "lemmy": "https://join-lemmy.org/ns#",
      "value": "schema:value",
      "Hashtag": "as:Hashtag",
      "featured": {
        "@id": "toot:featured",
        "@type": "@id"
      },
      "featuredTags": {
        "@id": "toot:featuredTags",
        "@type": "@id"
      },
      "alsoKnownAs": {
        "@id": "as:alsoKnownAs",
        "@type": "@id"
      },
      "moderators": {
        "@id": "lemmy:moderators",
        "@type": "@id"
      },
      "postingRestrictedToMods": "lemmy:postingRestrictedToMods",
      "discoverable": "toot:discoverable",
      "indexable": "toot:indexable",
      "sensitive": "as:sensitive",
      "resource": "webfinger:resource"
    }
  ],
  "id": "https://pfefferle.org/author/pfefferle/#follow/1703174869",
  "type": "Accept",
  "object": {
    "id": "https://misskey.io/follows/9niynkoa4zjm0021",
    "type": "Follow"
  },
  "actor": "https://pfefferle.org/author/pfefferle/",
  "to": "https://misskey.io/users/7xgdnovq9y"
}
```

**Comment by pfefferle** [comment]
oh, it seems to miss the actor in the object... will check why this!

**Comment by saschanaz** [comment]
Technically Misskey should be able to infer the actor from the id `https://misskey.io/follows/9niynkoa4zjm0021`, but it seems the implementation totally ignores it as acceptFollow doesn't use it at all. 👀

**Comment by pfefferle** [comment]
@saschanaz You saved my day and my christmas holidays!!! I found the issue in the code that strips the actor and the object!

I will fix it asap and release a new update!

So the follow issue is solved, sorry for keeping you busy and thanks a lot for your help debugging this issue!

**Comment by saschanaz** [comment]
Congrats! 🎉

(Let's keep this issue to track supporting implementations without those fields)

**Comment by pfefferle** [comment]
> (Let's keep this issue to track supporting implementations without those fields)

Besides of that, should I keep this issue open because of the `sharedInbox` problem?

**Comment by saschanaz** [comment]
Yup, but ideally we should have two separate issues for each.

**Comment by pfefferle** [comment]
Ok, I will file a separate issue for the `sharedInbox` issue.
