### ISSUE TITLE
一度も`pnpm run build`してないと`pnpm run build-misskey-js-with-types`が落ちる

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12774]
### 💡 Summary

`pnpm run build-misskey-js-with-types`の中では`pnpm --filter backend build`があるので事前ビルド無しで実行されることを想定してるように見えるのですが、事前に`pnpm run build`していないと`pnpm run build-misskey-js-with-types`が落ちます

### 🥰 Expected Behavior

多分エラーしない

### 🤬 Actual Behavior

```
 $ pnpm run build-misskey-js-with-types

> misskey@2023.12.0 build-misskey-js-with-types /Users/anatawa12/misskey-2
> pnpm --filter backend build && pnpm --filter backend generate-api-json && ncp packages/backend/built/api.json packages/misskey-js/generator/api.json && pnpm --filter misskey-js update-autogen-code && pnpm --filter misskey-js build


> backend@ build /Users/anatawa12/misskey-2/packages/backend
> swc src -d built -D

Successfully compiled: 780 files, copied 26 files with swc (332.52ms)

> backend@ generate-api-json /Users/anatawa12/misskey-2/packages/backend
> node ./generate_api_json.js

node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/Users/anatawa12/misskey-2/packages/backend/built/../../../built/meta.json'
    at Module.readFileSync (node:fs:453:20)
    at loadConfig (file:///Users/anatawa12/misskey-2/packages/backend/built/config.js:17:32)
    at file:///Users/anatawa12/misskey-2/packages/backend/generate_api_json.js:5:16
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/anatawa12/misskey-2/packages/backend/built/../../../built/meta.json'
}

Node.js v20.10.0
/Users/anatawa12/misskey-2/packages/backend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  backend@ generate-api-json: `node ./generate_api_json.js`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
 ```

### 📝 Steps to Reproduce

1. 新たにクローンする
2. `pnpm i`
3. `pnpm run build-misskey-js-with-types`

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 0b5228f3cd48c51cb74f62244d937f9c6182df85
* Node: v20.10.0
* PostgreSQL: N/A
* Redis: N/A
* OS and Architecture: macOS 14.1.2 23B92 arm64
```

**Comment by anatawa12** [comment]
そもそも `build-misskey-js-with-types` がどこにもドキュメント化されてないのか...

**Comment by samunohito** [comment]
> path: '/Users/anatawa12/misskey-2/packages/backend/built/../../../built/meta.json'

これが`pnpm build-pre`によってしか生成されないためです…

`build-misskey-js-with-types`を用いた手順については、MisskeyHubあたりにページを生やす必要がありますね

**Comment by fruitriin** [comment]
misskey-js を事前にビルドするフックを pnpm install等色々なタイミングで入れてやるのがよい気がしている
（いまは pnpm installしたあとpnpm devしてもmisskey-jsがビルドされていないので起動しない等がある
