### ISSUE TITLE
退会したユーザーがいると通知欄が表示されなくなる

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#12929]
### 💡 Summary

通知欄の全てを開くと「問題が発生しました」と表示され通知一覧が表示されない。

syslogには以下のようなメッセージが出ている。
```
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]: ERR  *#011[api]#011Internal error occurred in i/notifications-grouped: Could not find any entity of type "MiUser" matching: {
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     "id": "9iy2zdgivv"
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]: }
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]: {
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:   ep: 'i/notifications-grouped',
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:   ps: {
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     limit: 20,
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     allowPartial: true,
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     i: 'TJd6cZ6n9DhdZRbN',
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     markAsRead: true
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:   },
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:   e: {
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     message: 'Could not find any entity of type "MiUser" matching: {\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    "id": "9iy2zdgivv"\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '}',
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     code: 'EntityNotFoundError',
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     stack: 'EntityNotFoundError: Could not find any entity of type "MiUser" matching: {\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    "id": "9iy2zdgivv"\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '}\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at /home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/entity-manager/EntityManager.js:651:39\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async UserEntityService.pack (file:///home/misskey/misskey/packages/backend/built/core/entities/UserEntityService.js:231:54)\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async Promise.all (index 8)\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async NotificationEntityService.packGrouped (file:///home/misskey/misskey/packages/backend/built/core/entities/NotificationEntityService.js:194:27)\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async Promise.all (index 4)\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async NotificationEntityService.packGroupedMany (file:///home/misskey/misskey/packages/backend/built/core/entities/NotificationEntityService.js:297:16)\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/i/notifications-grouped.js:196:20\n' +
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:       '    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:16)',
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     id: 'e3d1b1c0-abd8-4ce3-a09e-bbe2c7e868c1'
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:   }
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]: }
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]: EntityNotFoundError: Could not find any entity of type "MiUser" matching: {
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     "id": "9iy2zdgivv"
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]: }
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at /home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.3/node_modules/typeorm/entity-manager/EntityManager.js:651:39
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async UserEntityService.pack (file:///home/misskey/misskey/packages/backend/built/core/entities/UserEntityService.js:231:54)
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async Promise.all (index 8)
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async NotificationEntityService.packGrouped (file:///home/misskey/misskey/packages/backend/built/core/entities/NotificationEntityService.js:194:27)
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async Promise.all (index 4)
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async NotificationEntityService.packGroupedMany (file:///home/misskey/misskey/packages/backend/built/core/entities/NotificationEntityService.js:297:16)
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/i/notifications-grouped.js:196:20
Jan  7 01:30:23 sv1-mikn1 misskey[3509881]:     at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:16) e3d1b1c0-abd8-4ce3-a09e-bbe2c7e868c1
```

### 🥰 Expected Behavior

通知一覧が表示される。

### 🤬 Actual Behavior

通知一覧が表示されない。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): macOS 14.2.1
* Browser: Safari 17.2.1
* Server URL: https://misskey.7ka.org
* Misskey: v2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: v2023.12.2
* Node: v20.10.0
* PostgreSQL: 16.1(Ubuntu 16.1-1.pgdg22.04+1)
* Redis: 7.2.3
* OS and Architecture: Ubuntu 22.04
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by nakkaa** [comment]
確認してないですがあれから見かけてないのでクローズで良いと思います。
