### ISSUE TITLE
 Publish Docker image に失敗する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13268]
### 💡 Summary

Update deps (https://github.com/misskey-dev/misskey/commit/7fc1d77893631f7bc792c7d6d5398aba65a331c9) 後から、 Publish Docker imageのCheckが落ちているので多分何かやらかしている

### 🥰 Expected Behavior

通る

### 🤬 Actual Behavior

通らない

### 📝 Steps to Reproduce

N/A

### 💻 Frontend Environment

```markdown
N/A
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/actions/runs/7866659964

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.312.0/_diag/Worker_20240212-024054-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.312.0/_diag/Worker_20240212-024054-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.312.0/_diag/Worker_20240212-024054-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
```

なんかシンプルにログが長すぎるとかにも見える

**Comment by anatawa12** [comment]
actions/runner#1807 多分類似issue

**Comment by anatawa12** [comment]
> You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 95 MB

95Mって 150Gからしたら結構小さい気がするけどでもinodeなのかな

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/blob/b95e25004f87cf0743f4a363cd5ed4a7720ad27d/.github/workflows/docker-develop.yml#L21
https://github.com/misskey-dev/misskey/blob/b95e25004f87cf0743f4a363cd5ed4a7720ad27d/.github/workflows/docker-develop.yml#L38

いまarm64とx64を同時にビルドしてるけど、これを別途やるだけでも当面は解決しそう。

**Comment by tamaina** [comment]
一旦max-parallel: 1を試してみたさがある

https://docs.github.com/ja/actions/using-jobs/using-a-matrix-for-your-jobs#defining-the-maximum-number-of-concurrent-jobs

**Comment by tamaina** [comment]
あっそもそもmatrixじゃない？

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/pull/9927#issuecomment-1429156634 はぁ

**Comment by tamaina** [comment]
つまり https://github.com/misskey-dev/misskey/pull/13269 をマージしたら同じ問題が起きるのか？

**Comment by anatawa12** [comment]
そういう実装なのか...だとすると #13269 マージするとダメそうですね

**Comment by tamaina** [comment]
https://github.com/docker/build-push-action/issues/846

**Comment by anatawa12** [comment]
https://docs.docker.com/build/ci/github-actions/multi-platform/
https://github.com/docker/docs/issues/19339

https://github.com/docker/build-push-action/issues/1051

**Comment by anatawa12** [comment]
https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
にあるようにマージするstepを追加すればいいらしい？

**Comment by anatawa12** [comment]
別のプロジェクトに忙しいのでそこまで複雑な変更はできるヒマがないので修正はどなたかやっていただきたいです

**Comment by anatawa12** [comment]
- #13327
- https://github.com/misskey-dev/misskey/pull/13325#discussion_r1492018724

**Comment by tamaina** [comment]
なおった
