### ISSUE TITLE
LemmyがLikeをAnnounceしてくる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13552]
### 💡 Summary

LemmyがAnnounceのobjectにLikeを含んでくるが、MisskeyはNoteであることが前提でプログラムされているため対応していない

### 🥰 Expected Behavior

Note以外は弾く (エラーにせずInboxにためない)

### 🤬 Actual Behavior

ErrorになるためInbox Queueが大量に貯まる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey: 2024.3.1 とか
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tassoman** [comment]
Got this
```log
Error: invalid Note: invalid object type Like
    at ApNoteService.validateNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:90:20)
    at ApNoteService.createNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApNoteService.resolveNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:326:20)
    at async ApInboxService.announceNote (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:264:26)
    at async ApInboxService.announce (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:244:9)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:155:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
Error: invalid Note: invalid object type Like
    at ApNoteService.validateNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:90:20)
    at ApNoteService.createNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApNoteService.resolveNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:326:20)
    at async ApInboxService.announceNote (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:264:26)
    at async ApInboxService.announce (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:244:9)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:155:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
Error: invalid Note: invalid object type Like
    at ApNoteService.validateNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:90:20)
    at ApNoteService.createNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApNoteService.resolveNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:326:20)
    at async ApInboxService.announceNote (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:264:26)
    at async ApInboxService.announce (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:244:9)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:155:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
Error: invalid Note: invalid object type Like
    at ApNoteService.validateNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:90:20)
    at ApNoteService.createNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApNoteService.resolveNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:326:20)
    at async ApInboxService.announceNote (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:264:26)
    at async ApInboxService.announce (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:244:9)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:155:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
```

**Comment by tassoman** [comment]
This problem is because Lemmy notes are really invalid, or because Misskey 2024.3.1 is unable to deal with it?

**Comment by tassoman** [comment]
@tamaina I only get errors from Lemmy instances, mostly `lemmy.world` and `lemmy.ml`.   
Env: Docker master build. How do I can debug further? 🤔 

```log
Error: invalid note
    at ApNoteService.createNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:127:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApNoteService.resolveNote (file:///misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:326:20)
    at async ApInboxService.announceNote (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:264:26)
    at async ApInboxService.announce (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:244:9)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:155:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
```

**Comment by tassoman** [comment]
> web-1  | WARN 1 [queue inbox]   inbox activity ignored (maybe): id=https://lemmy.world/activities/announce/like/033c343e-c694-46c0-89a9-1b3848d3690b reason=skip: unknown object type Like

Confirmed in docker develop branch build! GRAZIE TANTE!
