### ISSUE TITLE
`/@` にアクセスするとサーバーエラーが発生する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13704]
### 💡 Summary

書いてあるとおり

Forwarded from https://activitypub.software/TransFem-org/Sharkey/-/issues/485

### 🥰 Expected Behavior

フロントエンドの「ページが見つかりません」ページが見えてほしい

### 🤬 Actual Behavior

サーバーエラー

![image](https://github.com/misskey-dev/misskey/assets/67428053/2cbe7014-6bb9-42fb-a42b-7866d8bfd3d4)

（エラーコードが毎回変わるが、これはハンドルされていないエラーのため）

```
ERR  *  [client]        Internal error occurred in /@:user.atom: Cannot read properties of undefined (reading 'startsWith') {
  path: '/@:user.atom',
  params: { user: undefined },
  query: {},
  code: 'TypeError',
  stack: "TypeError: Cannot read properties of undefined (reading 'startsWith')\n" +
    '    at Module.parse (file:///home/user/misskey/packages/backend/built/misc/acct.js:5:14)\n' +
    '    at getFeed (file:///home/user/misskey/packages/backend/built/server/web/ClientServerService.js:418:45)\n' +
    '    at Object.<anonymous> (file:///home/user/misskey/packages/backend/built/server/web/ClientServerService.js:428:32)\n' +
    '    at preHandlerCallback (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:137:37)\n' +
    '    at validationCompleted (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:121:5)\n' +
    '    at preValidationCallback (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:98:5)\n' +
    '    at handler (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:75:7)\n' +
    '    at handleRequest (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:24:5)\n' +
    '    at runPreParsing (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/route.js:593:5)\n' +
    '    at next (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/hooks.js:237:9)\n' +
    '    at Object.<anonymous> (file:///home/user/misskey/packages/backend/built/server/web/ClientServerService.js:259:13)\n' +
    '    at hookIterator (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/hooks.js:409:10)\n' +
    '    at next (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/hooks.js:243:18)\n' +
    '    at Object.<anonymous> (/home/user/misskey/node_modules/.pnpm/@fastify+view@8.2.0/node_modules/@fastify/view/index.js:134:7)\n' +
    '    at hookIterator (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/hooks.js:409:10)\n' +
    '    at next (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/hooks.js:243:18)\n' +
    '    at handleResolve (/home/user/misskey/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/hooks.js:254:7)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  id: 'df7f01a8-74bc-484e-909b-3ca02a26a10b'
}
```

### 📝 Steps to Reproduce

1. `/@` にアクセスする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 23H2
* Browser: Chrome 123.0.6312.106 (Official Build) （64 ビット） (cohort: Stable) 
* Server URL: (local)
* Misskey: (develop branch)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
強火？
