### ISSUE TITLE
[2024.5.0-beta1]ノートを配送できない [ERR_INVALID_CHAR]: Invalid character in header content ["User-Agent"]

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#13802]
### 💡 Summary

ノートを配送できない、デリバーキューがたまり続ける

おま環かも

### 🥰 Expected Behavior

ノートが配送できる

### 🤬 Actual Behavior

```
May 07 11:28:22 MisskeySystems misskey[3815550]: WARN 2        [queue deliver]        failed(TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["User-Agent"]
May 07 11:28:22 MisskeySystems misskey[3815550]:     at file:///root/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/headers.js:101:6
May 07 11:28:22 MisskeySystems misskey[3815550]:     at Array.map (<anonymous>)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at new Headers (file:///root/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/headers.js:99:12)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at new Request (file:///root/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:88:19)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at file:///root/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:51:19
May 07 11:28:22 MisskeySystems misskey[3815550]:     at new Promise (<anonymous>)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at fetch (file:///root/misskey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:49:9)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at HttpRequestService.send (file:///root/misskey/packages/backend/built/core/HttpRequestService.js:138:27)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at ApRequestService.signedPost (file:///root/misskey/packages/backend/built/core/activitypub/ApRequestService.js:145:39)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at async DeliverProcessorService.process (file:///root/misskey/packages/backend/built/queue/processors/DeliverProcessorService.js:82:13)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at async Worker.processJob (/root/misskey/node_modules/.pnpm/bullmq@5.7.8/node_modules/bullmq/dist/cjs/classes/worker.js:441:28)
May 07 11:28:22 MisskeySystems misskey[3815550]:     at async Worker.retryIfFailed (/root/misskey/node_modules/.pnpm/bullmq@5.7.8/node_modules/bullmq/dist/cjs/classes/worker.js:630:24)) id=14935039 attempts=1/12 age=144ms to=https://misskey.yukineko.me/inbox
```

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2024.5.0-beta1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by fruitriin** [comment]
参考
https://github.com/misskey-dev/misskey/assets/18308639/35baf512-1e81-4de2-8294-5fc3a8bf87f9

**Comment by fruitriin** [comment]
（たぶん）おま環でした
pnpm clean-all して installとbuildをやりなおしたらしれっと直った模様？
よくわからず

**Comment by fruitriin** [comment]
顛末：
package.jsonのversionがAP配送のUserAgentとして採用されるため、全角文字を入れるとInvalid Characterとしてすべて配送できない　かも
