### ISSUE TITLE
meilisearch fetch error 500

### ISSUE THREAD

**Issue by sao-coding** [syuilo/Misskey#13871]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/58339015/6804decc-8422-4852-a2db-5bad4ce5c118)
Search posts cannot be used

### 🥰 Expected Behavior

Search posts can be used

### 🤬 Actual Behavior

Search posts can be used

## docker-compose.yml

```yml
  meilisearch:
    restart: always
    image: getmeili/meilisearch:v1.3.4
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    env_file:
      - .config/meilisearch.env
    # ports:
    #   - "7700:7700" #ポート番号を設定する
    networks:
      - internal_network
      # - external_network #外部ネットワークを有効にする
    volumes:
      - ./meili_data:/meili_data
```

## default.yml
```yml
meilisearch:
  host: meilisearch
  port: 7700
  apiKey: "df571c70-e9bb-4302-b5a1-d10179c5e441"
  ssl: true
  index: "misskey"
  scope: local
  ```
  
  ```env
  MEILI_MASTER_KEY=df571c70-e9bb-4302-b5a1-d10179c5e441
  ```
  
  ## misskey-web docker log
  ```
      name: '',
    data: { activity: [Object], signature: [Object] },
    opts: {
      attempts: 8,
      delay: 0,
      backoff: [Object],
      removeOnFail: true,
      removeOnComplete: true
    },
    id: '635',
    progress: 0,
    returnvalue: null,
    stacktrace: [
      'UnrecoverableError: skip: failed to resolve user\n' +
        '    at InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:98:19)\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
        '    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)\n' +
        '    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)'
    ],
    attemptsStarted: 1,
    attemptsMade: 1,
    delay: 0,
    repeatJobKey: undefined,
    timestamp: 1716463221650,
    parentKey: undefined,
    parent: undefined,
    toKey: [Function: bound ],
    scripts: Scripts { queue: [Worker], moveToFinishedKeys: [Array] },
    queueQualifiedName: 'misskey.sao-x.com:queue:inbox:inbox',
    processedOn: 1716463221652,
    failedReason: 'skip: failed to resolve user',
    token: '547b76d7-ac9c-47a7-966e-991945f64214:99',
    finishedOn: 1716463221658
  },
  e: {
    stack: 'UnrecoverableError: skip: failed to resolve user\n' +
      '    at InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:98:19)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)\n' +
      '    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)',
    message: 'skip: failed to resolve user',
    name: 'UnrecoverableError'
  }
}
ERR  *	[api]	Internal error occurred in notes/search: fetch failed {
  ep: 'notes/search',
  ps: {
    query: '安',
    userId: null,
    limit: 10,
    allowPartial: true,
    i: 'Mzy8OGVSfMl6F3aB',
    offset: 0,
    channelId: null
  },
  e: {
    message: 'fetch failed',
    code: 'MeiliSearchCommunicationError',
    stack: 'MeiliSearchCommunicationError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    id: '1b572612-e28b-47a5-854a-033793fdf372'
  }
}
MeiliSearchCommunicationError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: undefined,
  code: undefined
} 1b572612-e28b-47a5-854a-033793fdf372
```

## misskey-meilisearch docker log
```
Config file path:	"none"
Database path:		"./data.ms"
Server listening on:	"http://0.0.0.0:7700"
Environment:		"production"
Commit SHA:		"8822ca234e8bc7bceb3a6f6c246fb9aa24a16a9c"
Commit date:		"2023-09-12T13:34:39+00:00"
Package version:	"1.3.4"
Anonymous telemetry:	"Disabled"
A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.
Check out Meilisearch Cloud!	https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=engine&utm_medium=cli
Documentation:			https://www.meilisearch.com/docs
Source code:			https://github.com/meilisearch/meilisearch
Discord:			https://discord.meilisearch.com
[2024-05-23T11:02:16Z INFO  actix_server::builder] starting 2 workers
[2024-05-23T11:02:16Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2024-05-23T11:13:11Z ERROR actix_http::h1::dispatcher] stream error: Request parse error: Invalid Header provided
[2024-05-23T11:13:25Z ERROR actix_http::h1::dispatcher] stream error: Request parse error: Invalid Header provided
[2024-05-23T11:15:04Z ERROR actix_http::h1::dispatcher] stream error: Request parse error: Invalid Header provided
[2024-05-23T11:20:26Z ERROR actix_http::h1::dispatcher] stream error: Request parse error: Invalid Header provided
```

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: edge 125.0.2535.51
* Server URL: https://misskey.sao-x.com
* Misskey: v2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker compose
* Misskey: v2024.3.1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by nakkaa** [comment]
.config/meilisearch.env に `MEILI_MASTER_KEY=` を設定しましたか？

ref: https://misskey-doc.7ka.org/ja/misskey/enable-meilisearch

**Comment by oluceps** [comment]
Same issue encountered.

**Comment by MikuMikuMe** [comment]
A quick work around for me is just disable ssl, since it's a local service there's no need for me to enable ssl.
