### ISSUE TITLE
type: Annouceがcannot detect typeになる

### ISSUE THREAD

**Issue by 1673beta** [syuilo/Misskey#14356]
### 💡 Summary

まだそのサーバーで観測されてないサーバーをブロックしている場合、Announceが配送されるとError: cannot detect typeでinboxが詰まります。

ref: https://github.com/1673beta/cherrypick/issues/47
ref?: https://github.com/misskey-dev/misskey/issues/14239

### 🥰 Expected Behavior

Announceが正常に処理されて、inboxがつまらない

### 🤬 Actual Behavior

inboxが詰まる

### 📝 Steps to Reproduce

1. まだ観測されていないサーバーをサーバーブロックリストに入れる
2. どこかと連合して、そのブロックしたサーバーのユーザーのノートをリノートする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: https://1722686269.virtualcat.net
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker
* Misskey: 2024.7.0
* Node: 20
* PostgreSQL: 15
* Redis: 7.2.4
* OS and Architecture: Ubuntu 24.04
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kozakura913** [comment]
一切ブロックしてない環境でも発生してる

**Comment by fruitriin** [comment]
うちではよくわからないけどとにかく大量に出る

**Comment by 1673beta** [comment]
2024.5.0になったあたりから起きるようになったっぽい？

**Comment by fruitriin** [comment]
<summaly>log
<details>

```
ul 31 05:20:44 MisskeySystems misskey[3600368]:     failedReason: 'cannot detect type',
Jul 31 05:20:44 MisskeySystems misskey[3600368]:     token: '********'
Jul 31 05:20:44 MisskeySystems misskey[3600368]:   },
Jul 31 05:20:44 MisskeySystems misskey[3600368]:   e: {
Jul 31 05:20:44 MisskeySystems misskey[3600368]:     stack: 'Error: cannot detect type\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at getApType (file:///root/misskey/packages/backend/built/core/activitypub/type.js:31:11)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at isPost (file:///root/misskey/packages/backend/built/core/activitypub/type.js:53:52)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at ApInboxService.announce (file:///root/misskey/packages/backend/built/core/activitypub/ApInboxService.js:261:13)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at async ApInboxService.performOneActivity (file:///root/misskey/packages/backend/built/core/activitypub/ApInboxService.js:165:20)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at async ApInboxService.performActivity (file:///root/misskey/packages/backend/built/core/activitypub/ApInboxService.js:134:22)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at async InboxProcessorService.process (file:///root/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:187:28)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at async Worker.processJob (/root/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:445:28)\n' +
Jul 31 05:20:44 MisskeySystems misskey[3600368]:       '    at async Worker.retryIfFailed (/root/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:634:24)',
Jul 31 05:20:44 MisskeySystems misskey[3600368]:     message: 'cannot detect type',
Jul 31 05:20:44 MisskeySystems misskey[3600368]:     name: 'Error'
Jul 31 05:20:44 MisskeySystems misskey[3600368]:   }
Jul 31 05:20:44 MisskeySystems misskey[3600368]: }
```
</details>
</summaly>
