### ISSUE TITLE
Can't clear cached remote files

### ISSUE THREAD

**Issue by vlnst** [syuilo/Misskey#14715]
### 💡 Summary

I can't clear cached remote files

### 🥰 Expected Behavior

I can clear cached remote files

### 🤬 Actual Behavior

The clear action fails with this log:
```node
INFO 1	[queue clean-remote-files]	Deleting cached remote files...
...
ERR  1	[queue objectStorage]	failed(QueryFailedError: canceling statement due to statement timeout
    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
    at async SelectQueryBuilder.getRawAndEntities (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async CleanRemoteFilesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteFilesProcessorService.js:40:27)
    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:445:28)
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:634:24)) id=41 {
  job: Job {
    queue: Worker {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      name: 'objectStorage',
      opts: [Object],
      closed: false,
      connection: [RedisConnection],
      qualifiedName: 'shitpost.poridge.club:queue:objectStorage:objectStorage',
      keys: [Object],
      toKey: [Function (anonymous)],
      scripts: [Scripts],
      abortDelayController: null,
      blockUntil: 0,
      drained: true,
      extendLocksTimer: Timeout {
        _idleTimeout: 7500,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 748694312,
        _onTimeout: [AsyncFunction (anonymous)],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 142965676,
        [Symbol(triggerId)]: 142963869
      },
      limitUntil: 0,
      waiting: [Promise],
      running: true,
      id: 'fad28a33-e6f1-4abe-b2c1-2113e1d4aec7',
      processFn: [Function (anonymous)],
      blockingConnection: [RedisConnection],
      stalledCheckTimer: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [Timeout],
        _idleNext: [Timeout],
        _idleStart: 748670411,
        _onTimeout: [AsyncFunction (anonymous)],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 142962897,
        [Symbol(triggerId)]: 0
      },
      asyncFifoQueue: [AsyncFifoQueue],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    name: 'cleanRemoteFiles',
    data: {},
    opts: {
      attempts: 0,
      delay: 0,
      removeOnFail: true,
      removeOnComplete: true,
      backoff: undefined
    },
    id: '41',
    progress: 0,
    returnvalue: null,
    stacktrace: [
      'QueryFailedError: canceling statement due to statement timeout\n' +
        '    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
        '    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)\n' +
        '    at async SelectQueryBuilder.executeEntitiesAndRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)\n' +
        '    at async SelectQueryBuilder.getRawAndEntities (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)\n' +
        '    at async SelectQueryBuilder.getMany (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)\n' +
        '    at async CleanRemoteFilesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteFilesProcessorService.js:40:27)\n' +
        '    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:445:28)\n' +
        '    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:634:24)'
    ],
    attemptsStarted: 1,
    attemptsMade: 1,
    delay: 0,
    repeatJobKey: undefined,
    timestamp: 1725793449948,
    parentKey: undefined,
    parent: undefined,
    toKey: [Function: bound ],
    scripts: Scripts { queue: [Worker], moveToFinishedKeys: [Array] },
    queueQualifiedName: 'shitpost.poridge.club:queue:objectStorage:objectStorage',
    processedOn: 1725793449949,
    failedReason: 'canceling statement due to statement timeout',
    token: 'fad28a33-e6f1-4abe-b2c1-2113e1d4aec7:148194',
    finishedOn: 1725793459953
  },
  e: {
    stack: 'QueryFailedError: canceling statement due to statement timeout\n' +
      '    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)\n' +
      '    at async SelectQueryBuilder.executeEntitiesAndRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)\n' +
      '    at async SelectQueryBuilder.getRawAndEntities (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)\n' +
      '    at async SelectQueryBuilder.getMany (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.12.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)\n' +
      '    at async CleanRemoteFilesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteFilesProcessorService.js:40:27)\n' +
      '    at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:445:28)\n' +
      '    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:634:24)',
    message: 'canceling statement due to statement timeout',
    name: 'QueryFailedError'
  }
}
```
And in PostgreSQL:
```sql
2024-09-08 10:59:31.040 UTC [1245943] ERROR:  canceling statement due to statement timeout
2024-09-08 10:59:31.040 UTC [1245943] STATEMENT:  SELECT "MiDriveFile"."id" AS "MiDriveFile_id", "MiDriveFile"."userId" AS "MiDriveFile_userId", "MiDriveFile"."userHost" AS "MiDriveFile_userHost", "MiDriveFile"."md5" AS "MiDriveFile_md5", "MiDriveFile"."name" AS "MiDriveFile_name", "MiDriveFile"."type" AS "MiDriveFile_type", "MiDriveFile"."size" AS "MiDriveFile_size", "MiDriveFile"."comment" AS "MiDriveFile_comment", "MiDriveFile"."blurhash" AS "MiDriveFile_blurhash", "MiDriveFile"."properties" AS "MiDriveFile_properties", "MiDriveFile"."storedInternal" AS "MiDriveFile_storedInternal", "MiDriveFile"."url" AS "MiDriveFile_url", "MiDriveFile"."thumbnailUrl" AS "MiDriveFile_thumbnailUrl", "MiDriveFile"."webpublicUrl" AS "MiDriveFile_webpublicUrl", "MiDriveFile"."webpublicType" AS "MiDriveFile_webpublicType", "MiDriveFile"."accessKey" AS "MiDriveFile_accessKey", "MiDriveFile"."thumbnailAccessKey" AS "MiDriveFile_thumbnailAccessKey", "MiDriveFile"."webpublicAccessKey" AS "MiDriveFile_webpublicAccessKey", "MiDriveFile"."uri" AS "MiDriveFile_uri", "MiDriveFile"."src" AS "MiDriveFile_src", "MiDriveFile"."folderId" AS "MiDriveFile_folderId", "MiDriveFile"."isSensitive" AS "MiDriveFile_isSensitive", "MiDriveFile"."maybeSensitive" AS "MiDriveFile_maybeSensitive", "MiDriveFile"."maybePorn" AS "MiDriveFile_maybePorn", "MiDriveFile"."isLink" AS "MiDriveFile_isLink", "MiDriveFile"."requestHeaders" AS "MiDriveFile_requestHeaders", "MiDriveFile"."requestIp" AS "MiDriveFile_requestIp" FROM "drive_file" "MiDriveFile" WHERE ((NOT("MiDriveFile"."userHost" IS NULL)) AND ("MiDriveFile"."isLink" = $1)) ORDER BY "MiDriveFile"."id" ASC LIMIT 8
```
I've tried removing the statement timeout from postgres.ts https://github.com/misskey-dev/misskey/blob/8d23122fd664564dc069ca8e8e337f4d4a1727fc/packages/backend/src/postgres.ts#L215
but it didn't help much. Now It says it cleared the cache in logs but in reality it is not:
```sql
INFO 1	[queue clean-remote-files]	Deleting cached remote files...
```
```sql
query is slow: SELECT "MiDriveFile"."id" AS "MiDriveFile_id", "MiDriveFile"."userId" AS "MiDriveFile_userId", "MiDriveFile"."userHost" AS "MiDriveFile_userHost", "MiDriveFile"."md5" AS "MiDriveFile_md5", "MiDriveFile"."name" AS "MiDriveFile_name", "MiDriveFile"."type" AS "MiDriveFile_type", "MiDriveFile"."size" AS "MiDriveFile_size", "MiDriveFile"."comment" AS "MiDriveFile_comment", "MiDriveFile"."blurhash" AS "MiDriveFile_blurhash", "MiDriveFile"."properties" AS "MiDriveFile_properties", "MiDriveFile"."storedInternal" AS "MiDriveFile_storedInternal", "MiDriveFile"."url" AS "MiDriveFile_url", "MiDriveFile"."thumbnailUrl" AS "MiDriveFile_thumbnailUrl", "MiDriveFile"."webpublicUrl" AS "MiDriveFile_webpublicUrl", "MiDriveFile"."webpublicType" AS "MiDriveFile_webpublicType", "MiDriveFile"."accessKey" AS "MiDriveFile_accessKey", "MiDriveFile"."thumbnailAccessKey" AS "MiDriveFile_thumbnailAccessKey", "MiDriveFile"."webpublicAccessKey" AS "MiDriveFile_webpublicAccessKey", "MiDriveFile"."uri" AS "MiDriveFile_uri", "MiDriveFile"."src" AS "MiDriveFile_src", "MiDriveFile"."folderId" AS "MiDriveFile_folderId", "MiDriveFile"."isSensitive" AS "MiDriveFile_isSensitive", "MiDriveFile"."maybeSensitive" AS "MiDriveFile_maybeSensitive", "MiDriveFile"."maybePorn" AS "MiDriveFile_maybePorn", "MiDriveFile"."isLink" AS "MiDriveFile_isLink", "MiDriveFile"."requestHeaders" AS "MiDriveFile_requestHeaders", "MiDriveFile"."requestIp" AS "MiDriveFile_requestIp" FROM "drive_file" "MiDriveFile" WHERE ((NOT("MiDriveFile"."userHost" IS NULL)) AND ("MiDriveFile"."isLink" = $1)) ORDER BY "MiDriveFile"."id" ASC LIMIT 8 -- PARAMETERS: [false]
execution time: 27049
DONE 1	[queue clean-remote-files]	All cached remote files has been deleted.
```

The remote files didn't delete, I still have 100GB of files and around 9GB of the info about them in DB. It would be very helpful if you could point what can I do to clear these files.

### 📝 Steps to Reproduce

- With you admin account go to /admin/files and press the trash icon or use API with POST request to /api/admin/drive/clean-remote-files with your admin credentials

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: Mozilla Firefox 131.0
* Server URL: https://shitpost.poridge.club
* Misskey:2024.9.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Docker Compose
* Misskey: 2024.9.0
* Node: v20.16.0
* PostgreSQL: 15.8
* Redis: 7.4.0
* OS and Architecture: Debian GNU/Linux 12 (bookworm)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Albirew** [comment]
i believe i have the same issue: 300gb of cached remote files.
i disabled remote caching more than 2 year before, and since then tried to clean cache any ways possible to no avail.

**Comment by vlnst** [comment]
I've migrated to Sharkey since then. And tried countless ways. Still no success. I think there is probably a way to distinguish user's files. But then there are system files like emojis which might not have ones category. Maybe doing a query in db and deleting files which are not considered local is a way to fix this issue. But I'm not sure. I don't have enough competence to fix it. So I now have to manage this enormous data when migrating. And I can't do backups of files since 100GB is a lot of space

**Comment by tassoman** [comment]
I also found this in the new Queue Jobs admin panel 2025.9.0

```json
{
	"id": "repeat:cleanRemoteNotes:1758340800000",
	"name": "cleanRemoteNotes",
	"data": {},
	"opts": {
		"attempts": 0,
		"prevMillis": 1758340800000,
		"removeOnFail": {
			"age": 604800
		},
		"removeOnComplete": {
			"age": 604800
		},
		"repeat": {
			"pattern": "0 4 * * *",
			"count": 2
		},
		"jobId": "repeat:cleanRemoteNotes:1758340800000",
		"timestamp": 1758254400021,
		"delay": 86399979
	},
	"timestamp": 1758254400021,
	"processedOn": 1758340800068,
	"finishedOn": 1758340858567,
	"progress": 79.5408956332715,
	"attempts": 1,
	"delay": 0,
	"failedReason": "canceling statement due to statement timeout",
	"stacktrace": [
		"QueryFailedError: canceling statement due to statement timeout\n    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2229:25)\n    at async SelectQueryBuilder.getRawMany (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)\n    at async CleanRemoteNotesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteNotesProcessorService.js:155:27)\n    at async /misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:498:32\n    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:776:24)"
	],
	"returnValue": null,
	"isFailed": true
}
```

I guess the job is going on, but slowly. Each day it does something like this

```logs
Deleted 762 notes; 6443ms
Deleted 395 notes; 3221ms
Deleted 614 notes; 4835ms
```

Unfortunately I can't understand nothing more about it  :|

**Comment by qwjyh** [comment]
I have the same error in 2025.9.0 and here's my job.
I found some differences from https://github.com/misskey-dev/misskey/issues/14715#issuecomment-3314575905
- `opts` doesn't have `repeat`
- `stacktrace` has more detailed log like [the original one](https://github.com/misskey-dev/misskey/issues/14715#issue-2568764027)
- I tried "promote" and it has two entries in `stacktrace`

I have 600GB of files so I really want to clear them.

```json
{
	"id": "12",
	"name": "cleanRemoteFiles",
	"data": {},
	"opts": {
		"attempts": 0,
		"removeOnComplete": {
			"age": 604800,
			"count": 30
		},
		"removeOnFail": {
			"age": 604800,
			"count": 100
		}
	},
	"timestamp": 1759370954958,
	"processedOn": 1759371447246,
	"finishedOn": 1759371457827,
	"progress": 0,
	"attempts": 2,
	"delay": 0,
	"failedReason": "canceling statement due to statement timeout",
	"stacktrace": [
		"QueryFailedError: canceling statement due to statement timeout\n    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2229:25)\n    at async SelectQueryBuilder.executeCountQuery (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1749:25)\n    at async SelectQueryBuilder.getCount (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:770:29)\n    at async CleanRemoteFilesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteFilesProcessorService.js:39:23)\n    at async /misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:498:32\n    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:776:24)",
		"QueryFailedError: canceling statement due to statement timeout\n    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2229:25)\n    at async SelectQueryBuilder.executeCountQuery (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1749:25)\n    at async SelectQueryBuilder.getCount (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:770:29)\n    at async CleanRemoteFilesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteFilesProcessorService.js:39:23)\n    at async /misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:498:32\n    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:776:24)"
	],
	"returnValue": null,
	"isFailed": true
}
```

Same one as this job detail, but here's one of the error log
```
QueryFailedError: canceling statement due to statement timeout
    at PostgresQueryRunner.query (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2229:25)
    at async SelectQueryBuilder.executeCountQuery (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1749:25)
    at async SelectQueryBuilder.getCount (/misskey/node_modules/.pnpm/typeorm@0.3.26_patch_hash=2677b97a423e157945c154e64183d3ae2eb44dfa9cb0e5ce731a7612f507b_d1087d1d73a3a5969f8019672207c335/node_modules/typeorm/query-builder/SelectQueryBuilder.js:770:29)
    at async CleanRemoteFilesProcessorService.process (file:///misskey/packages/backend/built/queue/processors/CleanRemoteFilesProcessorService.js:39:23)
    at async /misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:498:32
    at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.58.5/node_modules/bullmq/dist/cjs/classes/worker.js:776:24)
```

**Comment by qwjyh** [comment]
I was able to clean cached remote files by changing db.extra.statement_timeout to 0 in config file. The parameter is not documented.
https://github.com/misskey-dev/misskey-hub-next/issues/341

This is not so related to this issue but I thought it is nice to show the deletion progress in logs tab in job queue as remote notes cleaning does.

**Comment by vlnst** [comment]
I managed to clear all cached files by saving files returned by `select "accessKey","thumbnailAccessKey","webpublicAccessKey" from "drive_file" where "isLink"=false` and moving other files to another directory (so I left only those that the SQL query returned).
Everything seems to work fine.
Do this at your own risk.

I'll close this issue since I don't observe it anymore (and I won't turn caching on again). This cache was very annoying.

You can either increase statement_timeout and hope it helps, or just clear the files, as I did.
