### ISSUE TITLE
Unable to upload file using self-deployed minio as object storage

### ISSUE THREAD

**Issue by zhimibuwudn** [syuilo/Misskey#15077]
![Image](https://github.com/user-attachments/assets/8beb3b58-8fb3-4d94-a4ae-eb7eba9de863)
![Image](https://github.com/user-attachments/assets/0a07a4aa-0e2b-4a68-ae99-d7e0d6fe349b)

docker v2024.11.0
```{
  code: 'BRIEF_REQUEST_INTERVAL',
  info: { remaining: 0, reset: 1732972413, resetMs: 1732972413564, total: 1 }
}
INFO *	[drive register]	{"size":182250,"md5":"e58bd9172c3c5feb0700712b3d0622fc","type":{"mime":"image/webp","ext":"webp"},"width":1362,"height":912,"blurhash":"eADmEk%fD+t6?v?[eTe:k;Ef70ozt8Sz$%9ZnNodNxoz$+NGNGWV9a","sensitive":false,"porn":false,"warnings":[]}
INFO *	[drive register]	web image not created (original satisfies webpublic)
INFO *	[drive register]	uploading original: files/1f7416b1-4284-4a1e-b1a2-1f80dbc70a1a.webp
INFO *	[drive register]	uploading thumbnail: files/thumbnail-f6c3b6e2-56c0-4d37-be0c-417423b546c3.webp
ERR  *	[drive register]	Upload Failed: key = files/thumbnail-f6c3b6e2-56c0-4d37-be0c-417423b546c3.webp, filename = Snipaste_2024-11-30_15-43-47.webp.thumbnail Error: Blocked address: 192.168.1.118
    at Socket.<anonymous> (file:///misskey/packages/backend/built/core/HttpRequestService.js:42:40)
    at Socket.emit (node:events:530:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:10) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
ERR  *	[drive register]	Upload Failed: key = files/1f7416b1-4284-4a1e-b1a2-1f80dbc70a1a.webp, filename = Snipaste_2024-11-30_15-43-47.webp Error: Blocked address: 192.168.1.118
    at Socket.<anonymous> (file:///misskey/packages/backend/built/core/HttpRequestService.js:42:40)
    at Socket.emit (node:events:530:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:10) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
DONE *	[drive register]	drive file has been created a17p77xwoo
ERR  1	[remote ap]	Resolution failed: AbortError: The operation was aborted.
ERR  1	[queue inbox]	failed(AbortError: The operation was aborted.) id=14714 attempts=6/8 age=62m activity=https://ovo.st/club/board/activity#121103/announce {
  job: {
    name: undefined,
    info: 'id=14714 attempts=6/8 age=62m',
    failedReason: 'The operation was aborted.',
    data: { activity: [Object], signature: [Object] }
  },
  e: 'AbortError: The operation was aborted.'
}```

**Comment by zhimibuwudn** [comment]
object storage configuration
![Image](https://github.com/user-attachments/assets/3bf578b6-62f3-4585-8837-fd294e813b2d)

**Comment by AmaseCocoa** [comment]
Perhaps a duplication with #15038, #15040 ?
