### ISSUE TITLE
502 Bad Gateway after update to Misskey v12.98.0

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#8042]
## 💡 Summary

502 Bad Gateway after update to Misskey v12.98.0. I tried `npm rebuild` as I had to do once ( #7474 ) but it doesn't seem to work, I still have a 502 error.
## 🙂 Expected Behavior

Update 

## ☹️ Actual Behavior

```
Dec 06 09:04:58 Misskey misskey[11330]:  |     |_|___ ___| |_ ___ _ _
Dec 06 09:04:58 Misskey misskey[11330]:  | | | | |_ -|_ -| '_| -_| | |
Dec 06 09:04:58 Misskey misskey[11330]:  |_|_|_|_|___|___|_,_|___|_  |
Dec 06 09:04:58 Misskey misskey[11330]:  v12.98.0                |___|
Dec 06 09:04:58 Misskey misskey[11330]:  Misskey is an open-source decentralized microblogging platform.
Dec 06 09:04:58 Misskey misskey[11330]:  If you like Misskey, please donate to support development. https://www.patreon.com/syuilo
Dec 06 09:04:58 Misskey misskey[11330]: --- Misskey (PID: 11342) ---
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot]        Welcome to Misskey!
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot]        Misskey v12.98.0
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot env]        NODE_ENV: production
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot env]        You do not have root privileges
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot nodejs]        Version 16.13.0
Dec 06 09:04:58 Misskey misskey[11330]: DONE *        [core boot config]        Loaded
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot db]        Connecting...
Dec 06 09:04:58 Misskey misskey[11330]: DONE *        [core boot db]        Connected: v11.13 (Debian 11.13-0+deb10u1)
Dec 06 09:04:58 Misskey misskey[11330]: DONE *        [core boot]        Misskey initialized
Dec 06 09:04:58 Misskey misskey[11330]: INFO *        [core boot]        Starting 1 worker...
Dec 06 09:05:00 Misskey misskey[11330]: Error: Cannot find module './build/Release/re2'
Dec 06 09:05:00 Misskey misskey[11330]: Require stack:
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/node_modules/re2/re2.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/misc/check-word-mute.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/services/note/create.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/remote/activitypub/models/note.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/create/note.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/create/index.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/index.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/remote/activitypub/perform.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/queue/processors/inbox.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/queue/index.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/server/activitypub.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/server/index.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/boot/worker.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/boot/index.js
Dec 06 09:05:00 Misskey misskey[11330]: - /home/misskey/misskey/packages/backend/built/index.js
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/re2/re2.js:3:13)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/misc/check-word-mute.js:4:13)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/services/note/create.js:29:27)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/remote/activitypub/models/note.js:7:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/create/note.js:3:16)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/create/index.js:4:16)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/index.js:5:17)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/remote/activitypub/perform.js:3:17)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/queue/processors/inbox.js:5:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/queue/index.js:7:17)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/activitypub.js:16:17)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/index.js:16:23)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
Dec 06 09:05:00 Misskey misskey[11330]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Dec 06 09:05:00 Misskey misskey[11330]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 06 09:05:00 Misskey misskey[11330]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Dec 06 09:05:00 Misskey misskey[11330]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 06 09:05:00 Misskey misskey[11330]:     at workerMain (/home/misskey/misskey/packages/backend/built/boot/worker.js:12:11)
Dec 06 09:05:00 Misskey misskey[11330]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 06 09:05:00 Misskey misskey[11330]:     at async default_1 (/home/misskey/misskey/packages/backend/built/boot/index.js:27:9) {
Dec 06 09:05:00 Misskey misskey[11330]:   code: 'MODULE_NOT_FOUND',
Dec 06 09:05:00 Misskey misskey[11330]:   requireStack: [
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/node_modules/re2/re2.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/misc/check-word-mute.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/services/note/create.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/remote/activitypub/models/note.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/create/note.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/create/index.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/remote/activitypub/kernel/index.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/remote/activitypub/perform.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/queue/processors/inbox.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/queue/index.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/server/activitypub.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/server/index.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/boot/worker.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/boot/index.js',
Dec 06 09:05:00 Misskey misskey[11330]:     '/home/misskey/misskey/packages/backend/built/index.js'
Dec 06 09:05:00 Misskey misskey[11330]:   ]
Dec 06 09:05:00 Misskey misskey[11330]: }
```

**Comment by koyuawsmbrtn** [comment]
Same, https://misskey.koyu.space has been dead since

**Comment by mei23** [comment]
Please try the following 
```
cd packages/backend/
yarn --force install
cd -
```

**Comment by mei23** [comment]
もしかしたら clean script の方が (でも) いいかも

**Comment by mei23** [comment]
Or try `yarn clean` and then install and build as usual.

**Comment by kazukyakayashi** [comment]
Problem solved 👌

**Comment by syuilo** [comment]
@mei23 🙏

**Comment by mei23** [comment]
https://github.com/uhop/node-re2/wiki/Problem:-unusual-errors-with-yarn
