### ISSUE TITLE
Error occurred while `yarn build`

### ISSUE THREAD

**Issue by CHN-beta** [syuilo/Misskey#8224]
## 💡 Summary

A lot of errors occurred while `yarn build`. Try to continue, get no answer after `yarn start`. `sudo netstat -anp` shows misskey is not listening on the port, but misskey does not complain anything.

I install misskey following [Japanese guide](https://misskey-hub.net/docs/install/manual.html#misskey%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB), which is slightly different from the English one. I also tried the English one, but not help.

The full build log is very long (found 305 errors), so I just paste some of them.

```
$ yarn build                                                                                        ─╯
yarn run v1.22.17
$ node ./scripts/build.js
building packages/backend ...
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1643527710688-0.7883495340470981/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @ build /home/chn/misskey/packages/backend
> tsc -p tsconfig.json || echo done. && tsc-alias -p tsconfig.json

node_modules/@types/express-serve-static-core/index.d.ts:501:18 - error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'ServerResponse'.
  Types of property 'req' are incompatible.
    Type 'Request<ParamsDictionary, any, any, Query> | undefined' is not assignable to type 'IncomingMessage'.
      Type 'undefined' is not assignable to type 'IncomingMessage'.

501 export interface Response<ResBody = any> extends http.ServerResponse, Express.Response {
                     ~~~~~~~~

node_modules/@types/readable-stream/index.d.ts:19:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.
  The types of 'Stream.Readable.Duplex' are incompatible between these types.
    Property 'isDisturbed' is missing in type 'typeof _Readable.Duplex' but required in type 'typeof import("stream").Duplex'.

19 declare class _Readable extends stream.Readable {
                 ~~~~~~~~~

  node_modules/@types/node/stream.d.ts:59:20
    59             static isDisturbed(stream: Readable | NodeJS.ReadableStream): boolean;
                          ~~~~~~~~~~~
    'isDisturbed' is declared here.

node_modules/@types/readable-stream/index.d.ts:68:11 - error TS2720: Class 'Duplex' incorrectly implements class '_Readable'. Did you mean to extend '_Readable' and inherit its members as a subclass?
  Type 'Duplex' is missing the following properties from type '_Readable': readableAborted, readableDidRead

68     class Duplex extends Writable implements /*extends*/_Readable, stream.Duplex {
             ~~~~~~

node_modules/@types/readable-stream/index.d.ts:68:11 - error TS2720: Class '_Readable.Duplex' incorrectly implements class 'import("stream").Duplex'. Did you mean to extend 'import("stream").Duplex' and inherit its members as a subclass?
  Type 'Duplex' is missing the following properties from type 'Duplex': readableAborted, readableDidRead

68     class Duplex extends Writable implements /*extends*/_Readable, stream.Duplex {
             ~~~~~~

node_modules/@types/readable-stream/index.d.ts:111:11 - error TS2720: Class '_Readable.PassThrough' incorrectly implements class 'import("stream").PassThrough'. Did you mean to extend 'import("stream").PassThrough' and inherit its members as a subclass?
  Type 'PassThrough' is missing the following properties from type 'Transform': readableAborted, readableDidRead

111     class PassThrough extends Transform implements stream.PassThrough {
              ~~~~~~~~~~~

node_modules/@types/readable-stream/index.d.ts:173:11 - error TS2720: Class '_Readable.Transform' incorrectly implements class 'import("stream").Transform'. Did you mean to extend 'import("stream").Transform' and inherit its members as a subclass?
  Type 'Transform' is missing the following properties from type 'Transform': readableAborted, readableDidRead

173     class Transform extends Duplex implements stream.Transform {
              ~~~~~~~~~
```

Tried `npx node-gyp configure`, but it complains:

```
gyp: binding.gyp not found (cwd: /home/chn/misskey) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/chn/.npm/_npx/238509/lib64/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.15.16-xanmod1
gyp ERR! command "/usr/bin/node" "/home/chn/.npm/_npx/238509/bin/node-gyp" "configure"
gyp ERR! cwd /home/chn/misskey
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
```

## 🙂 Expected Behavior

Build success.

## ☹️ Actual Behavior

Build failed.

## 📝 Steps to Reproduce

1. `git clone https://github.com/misskey-dev/misskey.git && cd misskey && git checkout 12.102.1 &&  git submodule update --init`
2. Create `.config/default.yml`
3. `export NODE_ENV=production`
4. `yarn install && yarn build`

## 📌 Environment

I am using the last Gentoo Linux, with nodejs-14.17.6 and yarn-1.22.17.

**Comment by CyberRex0** [comment]
Since Misskey v12, it requires Node v16 or later, but you are using v14.
Please upgrade Node and try again.

**Comment by CHN-beta** [comment]
> Since Misskey v12, it requires Node v16 or later, but you are using v14. Please upgrade Node and try again.

Thanks for your response. I tried on my laptop with nodejs-16, it works, although errors are still occurred while `yarn build`.

I also created a PR to fix the document.
