### ISSUE TITLE
Upgrade leads to `TypeError: Cannot read properties of undefined (reading 'schema')`

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8256]
## 💡 Summary

Pulling the latest from dev, building, migrating, and running gives this error
```
NFO *  [core boot]     Starting 1 worker...
TypeError: Cannot read properties of undefined (reading 'schema')
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/api/endpoints/charts/network.js:23:54)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/misskey/misskey/packages/backend/built/server/api/endpoints.js:13:16
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/api/endpoints.js:12:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/api/index.js:11:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/index.js:19:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at workerMain (/home/misskey/misskey/packages/backend/built/boot/worker.js:12:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default_1 (/home/misskey/misskey/packages/backend/built/boot/index.js:27:9)
```

Version: latest pull from development

**Comment by u1-liquid** [comment]
FYI: Since #8253 (c1b264e4e9686804e1b8ea17ba39753c41bd205b) the network chart was removed.

**Comment by syuilo** [comment]
try `npm run clean` before build

**Comment by ThatOneCalculator** [comment]
> try `npm run clean` before build

I did, but now i get this
```
misskey git:(develop) ✗ yarn migrate
yarn run v1.22.11
$ cd packages/backend && npx typeorm migration:run
Error during migration run:
Error: Cannot find module './built/config'
Require stack:
- /home/misskey/misskey/packages/backend/ormconfig.js
- /home/misskey/misskey/packages/backend/node_modules/typeorm/connection/ConnectionOptionsReader.js
- /home/misskey/misskey/packages/backend/node_modules/typeorm/globals.js
- /home/misskey/misskey/packages/backend/node_modules/typeorm/commands/SchemaSyncCommand.js
- /home/misskey/misskey/packages/backend/node_modules/typeorm/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/ormconfig.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/misskey/misskey/packages/backend/ormconfig.js',
    '/home/misskey/misskey/packages/backend/node_modules/typeorm/connection/ConnectionOptionsReader.js',
    '/home/misskey/misskey/packages/backend/node_modules/typeorm/globals.js',
    '/home/misskey/misskey/packages/backend/node_modules/typeorm/commands/SchemaSyncCommand.js',
    '/home/misskey/misskey/packages/backend/node_modules/typeorm/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ThatOneCalculator** [comment]
I also tried recloning and rebuilding, and ***after*** the build i get this :(

```
mk git:(develop) NODE_ENV=production npm start                                                                                           > misskey@12.103.1 start                                              > cd packages/backend && node --experimental-json-modules ./built/index.js
                                                                      node:internal/modules/cjs/loader:936                                    throw err;                                                            ^                                                                                                                                         Error: Cannot find module '/home/misskey/mk/packages/backend/built/index.js'                                                                    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)                                                               at Function.Module._load (node:internal/modules/cjs/loader:778:27)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {                       code: 'MODULE_NOT_FOUND',                                             requireStack: []                                                    }
```

**Comment by Johann150** [comment]
I can't reproduce the issue. I tried  `yarn cleanall && yarn build && yarn migrate` and everything seemed to be working fine. Starting after that also seems to be working for me.

**Comment by ThatOneCalculator** [comment]
> I can't reproduce the issue. I tried  `yarn cleanall && yarn build && yarn migrate` and everything seemed to be working fine. Starting after that also seems to be working for me.

I tried that, then it said `execa` wasnt found. So i ran `yarn add execa` and it gave this

```
$ node ./scripts/install-packages.js
/home/misskey/mk/scripts/install-packages.js:1
const execa = require('execa');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/misskey/mk/node_modules/execa/index.js from /home/misskey/mk/scripts/install-packages.js not supported.
Instead change the require of index.js in /home/misskey/mk/scripts/install-packages.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/misskey/mk/scripts/install-packages.js:1:15) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```


This is on a ***fresh clone*** of misskey. Somethings really wrong here.

**Comment by Johann150** [comment]
well if you are on a fresh clone did you also `yarn install`? so all packages are installed?

**Comment by tamaina** [comment]
- You must run `yarn install` after `yarn cleanall`.
- Misskey requires Node.js v16. Check it.

**Comment by ThatOneCalculator** [comment]
> well if you are on a fresh clone did you also `yarn install`? so all packages are installed?

I did `yarn` before and it was fine, but `yarn install` shows

```
mk git:(develop) ✗ yarn install
yarn install v1.22.11
[1/4] Resolving packages...
success Already up-to-date.
$ node ./scripts/install-packages.js
/home/misskey/mk/scripts/install-packages.js:1
const execa = require('execa');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/misskey/mk/node_modules/execa/index.js from /home/misskey/mk/scripts/install-packages.js not supported.
Instead change the require of index.js in /home/misskey/mk/scripts/install-packages.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/misskey/mk/scripts/install-packages.js:1:15) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command
```

**Comment by tamaina** [comment]
try `yarn install --force`

**Comment by ThatOneCalculator** [comment]
> - You must run `yarn install` after `yarn cleanall`.
> - Misskey requires Node.js v16. Check it.

I have node 16, but ill try that again

**Comment by ThatOneCalculator** [comment]
> try `yarn install --force`

Worked, but now everything is broken

https://user-images.githubusercontent.com/44733677/152691886-6db73d7c-572b-400e-821b-6d6ebb59b229.mp4

**Comment by ThatOneCalculator** [comment]
And notifications led to this

<details>
<summary>screenshot</summary>

![Screenshot_20220206-090010.jpg](https://user-images.githubusercontent.com/44733677/152691972-b686b2fc-6c64-4918-8358-1ecfa140a164.jpg)
</details

**Comment by Johann150** [comment]
Please try clearing the cache in Misskey's settings.

**Comment by ThatOneCalculator** [comment]
> Please try clearing the cache in Misskey's settings.

I tried that and got this error i cant even read

<details>
<summary>screenshot <code>SOMETHING_HAPPENED_IN_PROMISE</code> error screen</summary>

![Screenshot_20220206-090513.jpg](https://user-images.githubusercontent.com/44733677/152692130-f3514724-8c5d-4043-949e-9938e6a6cd32.jpg)
</details>

**Comment by tamaina** [comment]
I didn't meet any errors

![image](https://user-images.githubusercontent.com/7973572/152692178-d6f55b69-b831-4d5a-b8d2-0ca9e9ad2a2a.png)

**Comment by u1-liquid** [comment]
It should be on your browser cache problem, I can confirm your instance is currently running fine.

**Comment by tamaina** [comment]
Try https://stop.voring.me/flush (wait until display it displays `Success Flush!`)

**Comment by ThatOneCalculator** [comment]
I tried clearing the data on my browser and it ***finally*** works again. Not sure why everything kinda exploded there.
