### ISSUE TITLE
Latest update leads to resync-charts error

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8274]
## 💡 Summary

After updating from yesterday to today on misskey development, starting the server gives this error:

```
INFO *  [core boot]     Starting 1 worker...
DONE *  [core boot]     All workers started
DONE *  [core boot]     Now listening on port 3939 on https://stop.voring.me
INFO 1  [queue resync-charts]   Resync charts...
INFO 1  [queue resync-charts]   Resync charts...
UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.
    at UpdateValuesMissingError.TypeORMError [as constructor] (/home/misskey/misskey/packages/backend/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new UpdateValuesMissingError (/home/misskey/misskey/packages/backend/node_modules/typeorm/error/UpdateValuesMissingError.js:9:23)
    at UpdateQueryBuilder.createUpdateExpression (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:408:19)
    at UpdateQueryBuilder.getQuery (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:41:21)
    at UpdateQueryBuilder.QueryBuilder.getQueryAndParameters (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/QueryBuilder.js:279:26)
    at UpdateQueryBuilder.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:103:55)
    at step (/home/misskey/misskey/packages/backend/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/misskey/misskey/packages/backend/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/misskey/misskey/packages/backend/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.
    at UpdateValuesMissingError.TypeORMError [as constructor] (/home/misskey/misskey/packages/backend/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new UpdateValuesMissingError (/home/misskey/misskey/packages/backend/node_modules/typeorm/error/UpdateValuesMissingError.js:9:23)
    at UpdateQueryBuilder.createUpdateExpression (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:408:19)
    at UpdateQueryBuilder.getQuery (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:41:21)
    at UpdateQueryBuilder.QueryBuilder.getQueryAndParameters (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/QueryBuilder.js:279:26)
    at UpdateQueryBuilder.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:103:55)
    at step (/home/misskey/misskey/packages/backend/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/misskey/misskey/packages/backend/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/misskey/misskey/packages/backend/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
INFO 1  [remote ap]     Create: https://mk.nixnet.social/notes/8whx2p2dgl/activity
INFO 1  [remote ap]     Creating the Note: https://mk.nixnet.social/notes/8whx2p2dgl
```

## 📝 Steps to Reproduce

1. `git pull` yesterday (fine) then `git pull` today
2. Build, Migrate, Run

## 📌 Environment

Misskey version: f4e28983a1355caf842825ec71037b956b7b98ac
Your OS: Linux

## 📓 Notice

Everything ***seems*** to work fine on the instance, but it definitely is because of the new commit.

**Comment by ThatOneCalculator** [comment]
@syuilo might also be related, but the new graph shows 0 for "With file" for ***all*** notes, which is incorrect.
![Screenshot_2022-02-08-08-52-53_2560x1440](https://user-images.githubusercontent.com/44733677/153035895-ea10742d-2e14-4dba-967b-f20e0ce974b1.png)

**Comment by syuilo** [comment]
> @syuilo might also be related, but the new graph shows 0 for "With file" for _**all**_ notes, which is incorrect.
> ![Screenshot_2022-02-08-08-52-53_2560x1440](https://user-images.githubusercontent.com/44733677/153035895-ea10742d-2e14-4dba-967b-f20e0ce974b1.png)

This is a limitation of the system, as it is not possible to go back and generate charts for past data.

**Comment by ThatOneCalculator** [comment]
> This is a limitation of the system, as it is not possible to go back and generate charts for past data.

Gotcha. But I'm guessing the error above is still a problem.

**Comment by ThatOneCalculator** [comment]
@syuilo should I pull and migrate?
