### ISSUE TITLE
12.104.0 will not start after chart migration

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8280]
## 💡 Summary

After upgrading Misskey to 12.104.0, the server fails to start.

## 🥰 Expected Behavior

:custard: 

## 🤬 Actual Behavior

```
INFO *        [core boot]        Welcome to Misskey!
INFO *        [core boot]        Misskey v12.104.0
INFO *        [core boot env]        NODE_ENV: production
INFO *        [core boot env]        You do not have root privileges
INFO *        [core boot nodejs]        Version 16.13.2
DONE *        [core boot config]        Loaded
INFO *        [core boot db]        Connecting...
DONE *        [core boot db]        Connected: v14.1
DONE *        [core boot]        Misskey initialized
INFO *        [core boot]        Starting 4 workers...
TypeError: Cannot read properties of undefined (reading 'schema')
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/api/endpoints/charts/network.js:23:54)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/misskey/misskey/packages/backend/built/server/api/endpoints.js:13:16
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/api/endpoints.js:12:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/api/index.js:11:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/misskey/misskey/packages/backend/built/server/index.js:19:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at workerMain (/home/misskey/misskey/packages/backend/built/boot/worker.js:12:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default_1 (/home/misskey/misskey/packages/backend/built/boot/index.js:27:9)
```

## 📝 Steps to Reproduce

1. Upgrade Misskey from 12.103.1 to 12.104.0
2. Attempt to restart Misskey

## 📌 Environment

Misskey version: 12.104.0
Your OS: openSUSE Tumbleweed, Node.js 16.13.2, PostgreSQL 12

**Comment by Johann150** [comment]
Have you tried `yarn clean` or `yarn cleanall` before building? (see also <https://misskey-hub.net/en/docs/install/manual.html#how-to-update-your-misskey-server-to-the-latest-version>)

**Comment by fotoente** [comment]
Had the same issue.

`yarn cleanall` worked and then to do every step beginning from `yarn install`

**Comment by ghost** [comment]
Yup that fixed it. Should have looked at the closed issues too :sweat_smile:

**Comment by absturztau-be** [comment]
fyi: this is actually mentioned in the change log

https://github.com/misskey-dev/misskey/blob/develop/CHANGELOG.md#note
