### ISSUE TITLE
Upgrade 12.103.1 to 12.105.0 fail

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#8284]
## 💡 Summary
Hey, I try upgrade Misskey but NPM fail 

## 🤬 Actual Behavior

```
Info: === tsc-alias starting ===
Info: 558 files were affected!
building packages/client ...

> build
> webpack

37% building 1/2 entries 4300/4311 dependencies 701/1968 modulesKilled
/home/misskey/misskey/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 137: npm run build
    at makeError (/home/misskey/misskey/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/misskey/misskey/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/misskey/misskey/scripts/build.js:14:2 {
  shortMessage: 'Command failed with exit code 137: npm run build',
  command: 'npm run build',
  escapedCommand: 'npm run build',
  exitCode: 137,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 📌 Environment

Misskey version: 12.103.1
OS: Debian 10 (Buster)
Nodejs: v16.14.0

**Comment by Johann150** [comment]
Did you do all the steps outlined in the [documentation for updating](https://misskey-hub.net/en/docs/install/manual.html#how-to-update-your-misskey-server-to-the-latest-version)? Please also try the troubleshooting steps in the 2nd list in that section.

**Comment by syuilo** [comment]
It is possible that you do not have enough memory.
How much memory is installed?

**Comment by kazukyakayashi** [comment]
Problem solved, I thought it was misskey but obviously it was the nodejs update that went wrong and was not working normally. Really sorry for the inconvenience ☹️ so I close this issue.
