### ISSUE TITLE
I can't start my Misskey instance

### ISSUE THREAD

**Issue by AruMoon** [syuilo/Misskey#8298]
I can't start my Misskey instance after updating

I use remote server for serving Postgres Database and my PC for running instance.
When I was updating from 12.103.1 to 12.105.0, remote server has exceeded storage when I was running migrations. I rerun migrate command again after freeing storage and it done then.
After that I can't start instance and receive this
```
PS C:\Users\anton\Servers\misskey> yarn start
yarn run v1.22.15
$ cd packages/backend && node --experimental-json-modules ./built/index.js
  _____ _         _
 |     |_|___ ___| |_ ___ _ _
 | | | | |_ -|_ -| '_| -_| | |
 |_|_|_|_|___|___|_,_|___|_  |
 v12.105.0               |___|

 Misskey is an open-source decentralized microblogging platform.
 If you like Misskey, please donate to support development. https://www.patreon.com/syuilo

--- arumoon-winpc (PID: 14184) ---
INFO *  [core boot]     Welcome to Misskey!
INFO *  [core boot]     Misskey v12.105.0
INFO *  [core boot env] NODE_ENV is not set
WARN *  [core boot env] The environment is not in production mode.
WARN *  [core boot env] DO NOT USE FOR PRODUCTION PURPOSE!
INFO *  [core boot env] You do not have root privileges
VERB *  [core boot machine]     Hostname: arumoon-winpc
VERB *  [core boot machine]     Platform: win32 Arch: x64
VERB *  [core boot machine]     CPU: 4 core MEM: 11.9GB (available: 2.6GB)
INFO *  [core boot nodejs]      Version 16.13.1
DONE *  [core boot config]      Loaded
INFO *  [core boot db]  Connecting...
DONE *  [core boot db]  Connected: v14.1 (Debian 14.1-1.pgdg110+1)
DONE *  [core boot]     Misskey initialized
INFO *  [core boot]     Starting 1 worker...
VERB *  [core cluster]  Process forked: [1]
VERB *  [core cluster]  Process is now online: [1]
TypeError: Cannot read properties of undefined (reading 'schema')
    at Object.<anonymous> (C:\Users\anton\Servers\misskey\packages\backend\built\server\api\endpoints\charts\network.js:23:54)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\anton\Servers\misskey\packages\backend\built\server\api\endpoints.js:13:16
    at Array.map (<anonymous>)
    at Object.<anonymous> (C:\Users\anton\Servers\misskey\packages\backend\built\server\api\endpoints.js:12:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\anton\Servers\misskey\packages\backend\built\server\api\index.js:11:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\anton\Servers\misskey\packages\backend\built\server\index.js:19:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at workerMain (C:\Users\anton\Servers\misskey\packages\backend\built\boot\worker.js:12:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default_1 (C:\Users\anton\Servers\misskey\packages\backend\built\boot\index.js:27:9)
```

## 📌 Environment

Misskey version: 12.105.0
Your OS: Windows 11

**Comment by AruMoon** [comment]
Full Rebuild helped to solve the issue
