### ISSUE TITLE
relation attestation_challenge does not exist

### ISSUE THREAD

**Issue by Cute-angel** [syuilo/Misskey#8468]
```
QueryFailedError: relation "attestation_challenge" does not exist
    at PostgresQueryRunner.query (/home/misskey/misskey/packages/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DeleteQueryBuilder.execute (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/DeleteQueryBuilder.js:52:33)
    at async tick (file:///home/misskey/misskey/packages/backend/built/daemons/janitor.js:10:9) {
  query: 'DELETE FROM "attestation_challenge" WHERE "createdAt" < $1',
  parameters: [ 2022-04-03T13:21:11.464Z ],
  driverError: error: relation "attestation_challenge" does not exist
      at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 120,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '13',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1180',
    routine: 'parserOpenTable'
  },
  length: 120,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable'
}
QueryFailedError: relation "meta" does not exist
    at PostgresQueryRunner.query (/home/misskey/misskey/packages/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SelectQueryBuilder.loadRawResults (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2007:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1867:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:638:29)
    at async SelectQueryBuilder.getMany (/home/misskey/misskey/packages/backend/node_modules/typeorm/query-builder/SelectQueryBuilder.js:704:25)
    at async file:///home/misskey/misskey/packages/backend/built/misc/fetch-meta.js:9:23
    at async EntityManager.transaction (/home/misskey/misskey/packages/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
    at async fetchMeta (file:///home/misskey/misskey/packages/backend/built/misc/fetch-meta.js:7:12) {
  query: 'SELECT "Meta"."id" AS "Meta_id", "Meta"."name" AS "Meta_name", "Meta"."description" AS "Meta_description", "Meta"."maintainerName" AS "Meta_maintainerName", "Meta"."maintainerEmail" AS "Meta_maintainerEmail", "Meta"."disableRegistration" AS "Meta_disableRegistration", "Meta"."disableLocalTimeline" AS "Meta_disableLocalTimeline", "Meta"."disableGlobalTimeline" AS "Meta_disableGlobalTimeline", "Meta"."useStarForReactionFallback" AS "Meta_useStarForReactionFallback", "Meta"."langs" AS "Meta_langs", "Meta"."pinnedUsers" AS "Meta_pinnedUsers", "Meta"."hiddenTags" AS "Meta_hiddenTags", "Meta"."blockedHosts" AS "Meta_blockedHosts", "Meta"."pinnedPages" AS "Meta_pinnedPages", "Meta"."pinnedClipId" AS "Meta_pinnedClipId", "Meta"."themeColor" AS "Meta_themeColor", "Meta"."mascotImageUrl" AS "Meta_mascotImageUrl", "Meta"."bannerUrl" AS "Meta_bannerUrl", "Meta"."backgroundImageUrl" AS "Meta_backgroundImageUrl", "Meta"."logoImageUrl" AS "Meta_logoImageUrl", "Meta"."errorImageUrl" AS "Meta_errorImageUrl", "Meta"."iconUrl" AS "Meta_iconUrl", "Meta"."cacheRemoteFiles" AS "Meta_cacheRemoteFiles", "Meta"."proxyAccountId" AS "Meta_proxyAccountId", "Meta"."emailRequiredForSignup" AS "Meta_emailRequiredForSignup", "Meta"."enableHcaptcha" AS "Meta_enableHcaptcha", "Meta"."hcaptchaSiteKey" AS "Meta_hcaptchaSiteKey", "Meta"."hcaptchaSecretKey" AS "Meta_hcaptchaSecretKey", "Meta"."enableRecaptcha" AS "Meta_enableRecaptcha", "Meta"."recaptchaSiteKey" AS "Meta_recaptchaSiteKey", "Meta"."recaptchaSecretKey" AS "Meta_recaptchaSecretKey", "Meta"."localDriveCapacityMb" AS "Meta_localDriveCapacityMb", "Meta"."remoteDriveCapacityMb" AS "Meta_remoteDriveCapacityMb", "Meta"."summalyProxy" AS "Meta_summalyProxy", "Meta"."enableEmail" AS "Meta_enableEmail", "Meta"."email" AS "Meta_email", "Meta"."smtpSecure" AS "Meta_smtpSecure", "Meta"."smtpHost" AS "Meta_smtpHost", "Meta"."smtpPort" AS "Meta_smtpPort", "Meta"."smtpUser" AS "Meta_smtpUser", "Meta"."smtpPass" AS "Meta_smtpPass", "Meta"."enableServiceWorker" AS "Meta_enableServiceWorker", "Meta"."swPublicKey" AS "Meta_swPublicKey", "Meta"."swPrivateKey" AS "Meta_swPrivateKey", "Meta"."enableTwitterIntegration" AS "Meta_enableTwitterIntegration", "Meta"."twitterConsumerKey" AS "Meta_twitterConsumerKey", "Meta"."twitterConsumerSecret" AS "Meta_twitterConsumerSecret", "Meta"."enableGithubIntegration" AS "Meta_enableGithubIntegration", "Meta"."githubClientId" AS "Meta_githubClientId", "Meta"."githubClientSecret" AS "Meta_githubClientSecret", "Meta"."enableDiscordIntegration" AS "Meta_enableDiscordIntegration", "Meta"."discordClientId" AS "Meta_discordClientId", "Meta"."discordClientSecret" AS "Meta_discordClientSecret", "Meta"."deeplAuthKey" AS "Meta_deeplAuthKey", "Meta"."deeplIsPro" AS "Meta_deeplIsPro", "Meta"."ToSUrl" AS "Meta_ToSUrl", "Meta"."repositoryUrl" AS "Meta_repositoryUrl", "Meta"."feedbackUrl" AS "Meta_feedbackUrl", "Meta"."defaultLightTheme" AS "Meta_defaultLightTheme", "Meta"."defaultDarkTheme" AS "Meta_defaultDarkTheme", "Meta"."useObjectStorage" AS "Meta_useObjectStorage", "Meta"."objectStorageBucket" AS "Meta_objectStorageBucket", "Meta"."objectStoragePrefix" AS "Meta_objectStoragePrefix", "Meta"."objectStorageBaseUrl" AS "Meta_objectStorageBaseUrl", "Meta"."objectStorageEndpoint" AS "Meta_objectStorageEndpoint", "Meta"."objectStorageRegion" AS "Meta_objectStorageRegion", "Meta"."objectStorageAccessKey" AS "Meta_objectStorageAccessKey", "Meta"."objectStorageSecretKey" AS "Meta_objectStorageSecretKey", "Meta"."objectStoragePort" AS "Meta_objectStoragePort", "Meta"."objectStorageUseSSL" AS "Meta_objectStorageUseSSL", "Meta"."objectStorageUseProxy" AS "Meta_objectStorageUseProxy", "Meta"."objectStorageSetPublicRead" AS "Meta_objectStorageSetPublicRead", "Meta"."objectStorageS3ForcePathStyle" AS "Meta_objectStorageS3ForcePathStyle" FROM "meta" "Meta" ORDER BY "Meta"."id" DESC',
```

**Comment by syuilo** [comment]
Did you perform the migrations?

**Comment by Cute-angel** [comment]
no ,this is my first time I built and run it 

and when i test it at localhost it shows 'Internal Server Error'

**Comment by Johann150** [comment]
please try running `yarn migrate` (or `npx yarn migrate` if you do not have yarn)
