### ISSUE TITLE
elasticsearch Transport.js errors

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8557]
## 💡 Summary
For a longer time I am getting errors like this in docker-compose logs output

> web_1    | ResponseError: cluster_block_exception
web_1    |     at onBody (/misskey/packages/backend/node_modules/@elastic/elasticsearch/lib/Transport.js:333:23)
web_1    |     at IncomingMessage.onEnd (/misskey/packages/backend/node_modules/@elastic/elasticsearch/lib/Transport.js:260:11)
web_1    |     at IncomingMessage.emit (node:events:532:35)
web_1    |     at IncomingMessage.emit (node:domain:475:12)
web_1    |     at endReadableNT (node:internal/streams/readable:1346:12)
web_1    |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
web_1    |   meta: {
web_1    |     body: { error: [Object], status: 403 },
web_1    |     statusCode: 403,
web_1    |     headers: {
web_1    |       'content-type': 'application/json; charset=UTF-8',
web_1    |       'content-length': '259'
web_1    |     },
web_1    |     meta: {
web_1    |       context: null,
web_1    |       request: [Object],
web_1    |       name: 'elasticsearch-js',
web_1    |       connection: [Connection],
web_1    |       attempts: 0,
web_1    |       aborted: false
web_1    |     }
web_1    |   }
web_1    | }

## 📌 Environment

Misskey version: 12.110.1
Your OS: Docker Container with docker-compose running on Ubuntu 20.04
Your browser: random

**Comment by ghost** [comment]
the solution was

>curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
