### ISSUE TITLE
Yarn run fail Misskey 12.111.1 (no docker)

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#8896]
## 💡 Summary

When Update my Misskey instance, yarn run fail.

## 🥰 Expected Behavior

Misskey up to 12.111.1 👍 

## 🤬 Actual Behavior

```
yarn run v1.22.19
$ cd packages/backend && npx typeorm migration:run -d ormconfig.js
query: SELECT * FROM current_schema()
query: SHOW server_version;
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
140 migrations are already loaded in the database.
142 migrations were found in the source code.
webhook21648816172177 is the last executed migration. It was executed on Fri Apr 01 2022 14:29:32 GMT+0200 (Central European Summer Time).
2 migrations are new migrations must be executed.
query: START TRANSACTION
query: ALTER INDEX "public"."IDX_seoignmeoprigmkpodgrjmkpormg" RENAME TO "IDX_c8cc87bd0f2f4487d17c651fbf"
query: DROP INDEX "public"."IDX_note_on_channelId_and_id_desc"
query: ALTER TABLE "user" ALTER COLUMN "followersUri" DROP DEFAULT
query: ALTER TABLE "access_token" ALTER COLUMN "session" DROP DEFAULT
query: ALTER TABLE "access_token" ALTER COLUMN "appId" DROP DEFAULT
query: ALTER TABLE "access_token" ALTER COLUMN "name" DROP DEFAULT
query: ALTER TABLE "access_token" ALTER COLUMN "description" DROP DEFAULT
query: ALTER TABLE "access_token" ALTER COLUMN "iconUrl" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "softwareName" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "softwareVersion" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "name" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "description" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "maintainerName" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "maintainerEmail" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "iconUrl" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "faviconUrl" DROP DEFAULT
query: ALTER TABLE "instance" ALTER COLUMN "themeColor" DROP DEFAULT
query: ALTER TABLE "clip" ALTER COLUMN "description" DROP DEFAULT
query: ALTER TABLE "note" ALTER COLUMN "channelId" DROP DEFAULT
query: ALTER TABLE "abuse_user_report" ALTER COLUMN "comment" DROP DEFAULT
query: CREATE INDEX "IDX_315c779174fe8247ab324f036e" ON "drive_file" ("isLink")
query: CREATE INDEX "IDX_f22169eb10657bded6d875ac8f" ON "note" ("channelId")
query: CREATE INDEX "IDX_a9021cc2e1feb5f72d3db6e9f5" ON "abuse_user_report" ("targetUserId")
query: DELETE FROM "abuse_user_report" WHERE "targetUserId" NOT IN (SELECT "id" FROM "user")
query: ALTER TABLE "poll" ADD CONSTRAINT "UQ_da851e06d0dfe2ef397d8b1bf1b" UNIQUE ("noteId")
query: ALTER TABLE "user_keypair" ADD CONSTRAINT "UQ_f4853eb41ab722fe05f81cedeb6" UNIQUE ("userId")
query: ALTER TABLE "user_profile" ADD CONSTRAINT "UQ_51cb79b5555effaf7d69ba1cff9" UNIQUE ("userId")
query: ALTER TABLE "user_publickey" ADD CONSTRAINT "UQ_10c146e4b39b443ede016f6736d" UNIQUE ("userId")
query: ALTER TABLE "promo_note" ADD CONSTRAINT "UQ_e263909ca4fe5d57f8d4230dd5c" UNIQUE ("noteId")
query: ALTER TABLE "page" RENAME CONSTRAINT "FK_3126dd7c502c9e4d7597ef7ef10" TO "FK_a9ca79ad939bf06066b81c9d3aa"
query: ALTER TYPE "public"."user_profile_mutingnotificationtypes_enum" ADD VALUE 'pollEnded' AFTER 'pollVote'
query failed: CREATE INDEX "IDX_a9021cc2e1feb5f72d3db6e9f5" ON "abuse_user_report" ("targetUserId")
error: error: relation "IDX_a9021cc2e1feb5f72d3db6e9f5" already exists
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 112,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '884',
  routine: 'index_create'
}
Migration "foreignKeyReports1651224615271" failed, error: relation "IDX_a9021cc2e1feb5f72d3db6e9f5" already exists
query: ROLLBACK
query failed: DELETE FROM "abuse_user_report" WHERE "targetUserId" NOT IN (SELECT "id" FROM "user")
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TABLE "poll" ADD CONSTRAINT "UQ_da851e06d0dfe2ef397d8b1bf1b" UNIQUE ("noteId")
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TABLE "user_keypair" ADD CONSTRAINT "UQ_f4853eb41ab722fe05f81cedeb6" UNIQUE ("userId")
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TABLE "user_profile" ADD CONSTRAINT "UQ_51cb79b5555effaf7d69ba1cff9" UNIQUE ("userId")
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TABLE "user_publickey" ADD CONSTRAINT "UQ_10c146e4b39b443ede016f6736d" UNIQUE ("userId")
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TABLE "promo_note" ADD CONSTRAINT "UQ_e263909ca4fe5d57f8d4230dd5c" UNIQUE ("noteId")
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TABLE "page" RENAME CONSTRAINT "FK_3126dd7c502c9e4d7597ef7ef10" TO "FK_a9ca79ad939bf06066b81c9d3aa"
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
query failed: ALTER TYPE "public"."user_profile_mutingnotificationtypes_enum" ADD VALUE 'pollEnded' AFTER 'pollVote'
error: error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1035',
  routine: 'exec_simple_query'
}
Error during migration run:
QueryFailedError: relation "IDX_a9021cc2e1feb5f72d3db6e9f5" already exists
    at PostgresQueryRunner.query (/home/misskey/misskey/packages/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 22)
    at async foreignKeyReports1651224615271.up (file:///home/misskey/misskey/packages/backend/migration/1651224615271-foreign-key.js:5:9)
    at async MigrationExecutor.executePendingMigrations (/home/misskey/misskey/packages/backend/node_modules/typeorm/migration/MigrationExecutor.js:178:17)
    at async DataSource.runMigrations (/home/misskey/misskey/packages/backend/node_modules/typeorm/data-source/DataSource.js:248:35)
    at async Object.handler (/home/misskey/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:60:13) {
  query: 'CREATE INDEX "IDX_a9021cc2e1feb5f72d3db6e9f5" ON "abuse_user_report" ("targetUserId")',
  parameters: undefined,
  driverError: error: relation "IDX_a9021cc2e1feb5f72d3db6e9f5" already exists
      at Parser.parseErrorMessage (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/misskey/misskey/packages/backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 112,
    severity: 'ERROR',
    code: '42P07',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'index.c',
    line: '884',
    routine: 'index_create'
  },
  length: 112,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '884',
  routine: 'index_create'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 📝 Steps to Reproduce

1. Upadate Misskey
2. Migrate fail

## 📌 Environment

Misskey version: 12.110.1 -> 12.111.1
Your OS: Debian
Yarn: 1.22.19
Node: 16.15.0

**Comment by mei23** [comment]
Dockerの違いはあるけどたぶん同事象
https://github.com/misskey-dev/misskey/issues/8852

**Comment by syuilo** [comment]
とりあえず該当箇所消すかしら

**Comment by tamaina** [comment]
catchでもみ消せばいいのでは

**Comment by tamaina** [comment]
Duplicate of #8852

**Comment by mei23** [comment]
> catchでもみ消せばいいのでは

クエリエラーが発生した時点でマイグレーションのトランザクションが使えなくなるので
catchでもみ消しても、Node.js 側にエラーが挙がって来なくなるだけで結局動かない。
だった気がするのだわ。
