### ISSUE TITLE
Latest version build produces warning

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8913]
```
vite v3.0.0-beta.5 building for production...
✓ 69 modules transformed.
[vite:build-import-analysis] Failed to resolve import "vue-marquee-text-component" from "src/widgets/rss-marquee.vue". Does the file exist?
file: /home/misskey/misskey-new/packages/client/src/widgets/rss-marquee.vue:26:13
24: import { useInterval } from '@/scripts/use-interval';
25: 
26: const name = 'rssMarquee';
                 ^
27: 
28: const widgetPropsDef = {
error during build:
Error: Failed to resolve import "vue-marquee-text-component" from "src/widgets/rss-marquee.vue". Does the file exist?
    at error (file:///home/misskey/misskey-new/packages/client/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///home/misskey/misskey-new/packages/client/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21807:12)
    at Object.error (file:///home/misskey/misskey-new/packages/client/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22530:20)
    at Object.error (file:///home/misskey/misskey-new/packages/client/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21984:42)
    at normalizeUrl (file:///home/misskey/misskey-new/packages/client/node_modules/vite/dist/node/chunks/dep-332aa27f.js:40436:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (file:///home/misskey/misskey-new/packages/client/node_modules/vite/dist/node/chunks/dep-332aa27f.js:40474:47)
    at async transform (file:///home/misskey/misskey-new/packages/client/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21954:16)
    at async ModuleLoader.addModuleSource (file:///home/misskey/misskey-new/packages/client/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22180:30)
```

## 💡 Info

OS: Linux
Node: 18.4.0
Version: 66b27bdc9765088468c216ff98015e1fadf77732 (upgrading from 12.112.0-beta.8)

**Comment by syuilo** [comment]
I can't reproduce it. have you done a yarn install?

**Comment by ThatOneCalculator** [comment]
I have. I'll try again on a fresh clone.

**Comment by ThatOneCalculator** [comment]
@syuilo On a fresh clone, I no longer get that error, but I get this warning:

```
transforming (418) node_modules/.vite/deps_build-bc2bcb67/throttle-debounce.js[plugin:vite:esbuild] This assignment will throw because "preview_mention" is a constant
212|                _createVNode(MkTextarea, {
213|                  modelValue: preview_mention,
214|                  "onUpdate:modelValue": _cache[0] || (_cache[0] = ($event: any) => ((preview_mention) = $event))
   |                                                                                      ^
215|                }, {
216|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_hashtag" is a constant
230|                _createVNode(MkTextarea, {
231|                  modelValue: preview_hashtag,
232|                  "onUpdate:modelValue": _cache[1] || (_cache[1] = ($event: any) => ((preview_hashtag) = $event))
   |                                                                                      ^
233|                }, {
234|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_url" is a constant
248|                _createVNode(MkTextarea, {
249|                  modelValue: preview_url,
250|                  "onUpdate:modelValue": _cache[2] || (_cache[2] = ($event: any) => ((preview_url) = $event))
   |                                                                                      ^
251|                }, {
252|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_link" is a constant
266|                _createVNode(MkTextarea, {
267|                  modelValue: preview_link,
268|                  "onUpdate:modelValue": _cache[3] || (_cache[3] = ($event: any) => ((preview_link) = $event))
   |                                                                                      ^
269|                }, {
270|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_bold" is a constant
302|                _createVNode(MkTextarea, {
303|                  modelValue: preview_bold,
304|                  "onUpdate:modelValue": _cache[5] || (_cache[5] = ($event: any) => ((preview_bold) = $event))
   |                                                                                      ^
305|                }, {
306|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_small" is a constant
320|                _createVNode(MkTextarea, {
321|                  modelValue: preview_small,
322|                  "onUpdate:modelValue": _cache[6] || (_cache[6] = ($event: any) => ((preview_small) = $event))
   |                                                                                      ^
323|                }, {
324|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_quote" is a constant
338|                _createVNode(MkTextarea, {
339|                  modelValue: preview_quote,
340|                  "onUpdate:modelValue": _cache[7] || (_cache[7] = ($event: any) => ((preview_quote) = $event))
   |                                                                                      ^
341|                }, {
342|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_center" is a constant
356|                _createVNode(MkTextarea, {
357|                  modelValue: preview_center,
358|                  "onUpdate:modelValue": _cache[8] || (_cache[8] = ($event: any) => ((preview_center) = $event))
   |                                                                                      ^
359|                }, {
360|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_inlineCode" is a constant
374|                _createVNode(MkTextarea, {
375|                  modelValue: preview_inlineCode,
376|                  "onUpdate:modelValue": _cache[9] || (_cache[9] = ($event: any) => ((preview_inlineCode) = $event))
   |                                                                                      ^
377|                }, {
378|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_blockCode" is a constant
392|                _createVNode(MkTextarea, {
393|                  modelValue: preview_blockCode,
394|                  "onUpdate:modelValue": _cache[10] || (_cache[10] = ($event: any) => ((preview_blockCode) = $event))
   |                                                                                        ^
395|                }, {
396|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_inlineMath" is a constant
410|                _createVNode(MkTextarea, {
411|                  modelValue: preview_inlineMath,
412|                  "onUpdate:modelValue": _cache[11] || (_cache[11] = ($event: any) => ((preview_inlineMath) = $event))
   |                                                                                        ^
413|                }, {
414|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_flip" is a constant
428|                _createVNode(MkTextarea, {
429|                  modelValue: preview_flip,
430|                  "onUpdate:modelValue": _cache[12] || (_cache[12] = ($event: any) => ((preview_flip) = $event))
   |                                                                                        ^
431|                }, {
432|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_font" is a constant
446|                _createVNode(MkTextarea, {
447|                  modelValue: preview_font,
448|                  "onUpdate:modelValue": _cache[13] || (_cache[13] = ($event: any) => ((preview_font) = $event))
   |                                                                                        ^
449|                }, {
450|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_x2" is a constant
464|                _createVNode(MkTextarea, {
465|                  modelValue: preview_x2,
466|                  "onUpdate:modelValue": _cache[14] || (_cache[14] = ($event: any) => ((preview_x2) = $event))
   |                                                                                        ^
467|                }, {
468|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_x3" is a constant
482|                _createVNode(MkTextarea, {
483|                  modelValue: preview_x3,
484|                  "onUpdate:modelValue": _cache[15] || (_cache[15] = ($event: any) => ((preview_x3) = $event))
   |                                                                                        ^
485|                }, {
486|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_x4" is a constant
500|                _createVNode(MkTextarea, {
501|                  modelValue: preview_x4,
502|                  "onUpdate:modelValue": _cache[16] || (_cache[16] = ($event: any) => ((preview_x4) = $event))
   |                                                                                        ^
503|                }, {
504|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_blur" is a constant
518|                _createVNode(MkTextarea, {
519|                  modelValue: preview_blur,
520|                  "onUpdate:modelValue": _cache[17] || (_cache[17] = ($event: any) => ((preview_blur) = $event))
   |                                                                                        ^
521|                }, {
522|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_jelly" is a constant
536|                _createVNode(MkTextarea, {
537|                  modelValue: preview_jelly,
538|                  "onUpdate:modelValue": _cache[18] || (_cache[18] = ($event: any) => ((preview_jelly) = $event))
   |                                                                                        ^
539|                }, {
540|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_tada" is a constant
554|                _createVNode(MkTextarea, {
555|                  modelValue: preview_tada,
556|                  "onUpdate:modelValue": _cache[19] || (_cache[19] = ($event: any) => ((preview_tada) = $event))
   |                                                                                        ^
557|                }, {
558|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_jump" is a constant
572|                _createVNode(MkTextarea, {
573|                  modelValue: preview_jump,
574|                  "onUpdate:modelValue": _cache[20] || (_cache[20] = ($event: any) => ((preview_jump) = $event))
   |                                                                                        ^
575|                }, {
576|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_bounce" is a constant
590|                _createVNode(MkTextarea, {
591|                  modelValue: preview_bounce,
592|                  "onUpdate:modelValue": _cache[21] || (_cache[21] = ($event: any) => ((preview_bounce) = $event))
   |                                                                                        ^
593|                }, {
594|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_spin" is a constant
608|                _createVNode(MkTextarea, {
609|                  modelValue: preview_spin,
610|                  "onUpdate:modelValue": _cache[22] || (_cache[22] = ($event: any) => ((preview_spin) = $event))
   |                                                                                        ^
611|                }, {
612|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_shake" is a constant
626|                _createVNode(MkTextarea, {
627|                  modelValue: preview_shake,
628|                  "onUpdate:modelValue": _cache[23] || (_cache[23] = ($event: any) => ((preview_shake) = $event))
   |                                                                                        ^
629|                }, {
630|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_twitch" is a constant
644|                _createVNode(MkTextarea, {
645|                  modelValue: preview_twitch,
646|                  "onUpdate:modelValue": _cache[24] || (_cache[24] = ($event: any) => ((preview_twitch) = $event))
   |                                                                                        ^
647|                }, {
648|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_rainbow" is a constant
662|                _createVNode(MkTextarea, {
663|                  modelValue: preview_rainbow,
664|                  "onUpdate:modelValue": _cache[25] || (_cache[25] = ($event: any) => ((preview_rainbow) = $event))
   |                                                                                        ^
665|                }, {
666|                  label: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_sparkle" is a constant
680|                _createVNode(MkTextarea, {
681|                  modelValue: preview_sparkle,
682|                  "onUpdate:modelValue": _cache[26] || (_cache[26] = ($event: any) => ((preview_sparkle) = $event))
   |                                                                                        ^
683|                }, {
684|                  default: _withCtx(() => [

[plugin:vite:esbuild] This assignment will throw because "preview_rotate" is a constant
698|                _createVNode(MkTextarea, {
699|                  modelValue: preview_rotate,
700|                  "onUpdate:modelValue": _cache[27] || (_cache[27] = ($event: any) => ((preview_rotate) = $event))
   |                                                                                        ^
701|                }, {
702|                  default: _withCtx(() => [

```

**Comment by tamaina** [comment]
Do you still have this problem?

**Comment by ThatOneCalculator** [comment]
No
