### ISSUE TITLE
Tensorflow requires glibc (ld-linux-x86-64.so.2), which is problematic on Alpine

### ISSUE THREAD

**Issue by outloudvi** [syuilo/Misskey#8961]
## 💡 Summary

Alpine doesn't contain `ld-linux-x86-64.so.2` by default, which is required by `tfjs-node`, since Alpine primarily uses `musl` instead of `glibc`.

## 🥰 Expected Behavior

No error spawned.

## 🤬 Actual Behavior

```
web_1    | Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /misskey/packages/backend/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
web_1    |     at Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
web_1    |     at Module.load (node:internal/modules/cjs/loader:981:32)
web_1    |     at Module._load (node:internal/modules/cjs/loader:827:12)
web_1    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
web_1    |     at require (node:internal/modules/cjs/helpers:102:18)
web_1    |     at Object.<anonymous> (/misskey/packages/backend/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
web_1    |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
web_1    |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
web_1    |     at Module.load (node:internal/modules/cjs/loader:981:32)
web_1    |     at Module._load (node:internal/modules/cjs/loader:827:12)
web_1    |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
web_1    |     at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
web_1    |     at async Promise.all (index 0)
web_1    |     at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
web_1    |     at async workerMain (file:///misskey/packages/backend/built/boot/worker.js:9:5)
web_1    |     at async default (file:///misskey/packages/backend/built/boot/index.js:25:9) {
web_1    |   code: 'ERR_DLOPEN_FAILED'
web_1    | }
```

After installing [`gcompat`](https://pkgs.alpinelinux.org/package/edge/community/x86_64/gcompat):

```
web_1    | Error: Error relocating /misskey/packages/backend/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2: __memcpy_chk: symbol not found
web_1    |     at Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
web_1    |     at Module.load (node:internal/modules/cjs/loader:981:32)
web_1    |     at Module._load (node:internal/modules/cjs/loader:827:12)
web_1    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
web_1    |     at require (node:internal/modules/cjs/helpers:102:18)
web_1    |     at Object.<anonymous> (/misskey/packages/backend/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
web_1    |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
web_1    |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
web_1    |     at Module.load (node:internal/modules/cjs/loader:981:32)
web_1    |     at Module._load (node:internal/modules/cjs/loader:827:12)
web_1    |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
web_1    |     at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
web_1    |     at async Promise.all (index 0)
web_1    |     at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
web_1    |     at async workerMain (file:///misskey/packages/backend/built/boot/worker.js:9:5)
web_1    |     at async default (file:///misskey/packages/backend/built/boot/index.js:25:9) {
web_1    |   code: 'ERR_DLOPEN_FAILED'
web_1    | }
```

## 📝 Steps to Reproduce

1. Build and run `12.112.1`.

## 📌 Environment

Misskey version: 12.112.1
Your OS: Debian 11
Your browser: (Unrelated)

**Comment by tamaina** [comment]
https://github.com/tensorflow/tfjs/issues/1425

**Comment by tamaina** [comment]
related? https://wiki.alpinelinux.org/wiki/Running_glibc_programs

**Comment by outloudvi** [comment]
> related? https://wiki.alpinelinux.org/wiki/Running_glibc_programs

Exactly. I think it's generally not recommended to run glibc stuffs on Alpine.

**Comment by outloudvi** [comment]
P.S. I've prepared [a patch](https://github.com/outloudvi/misskey/tree/feat/i-8961) for instance admins to temporarily update to a version that has runtime Tensorflow requirements removed.

**Comment by syuilo** [comment]
revertするか
