### ISSUE TITLE
mocha test broken after merging nsfw detection 

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8963]
I don't know too much about tests, but it seems like these should be fairly easy to fix.

```
  227 passing (3m)
  9 failing
  1) Get file info
       Empty file:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: undefined,
    md5: 'd41d8cd98f00b204e9800998ecf8427e',
    orientation: undefined,
+   porn: false,
    size: 0,
...
    },
    width: undefined
  }
      + expected - actual
       {
         "height": [undefined]
         "md5": "d41d8cd98f00b204e9800998ecf8427e"
         "orientation": [undefined]
      -  "porn": false
         "size": 0
         "type": {
           "ext": [null]
           "mime": "application/octet-stream"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:17:10
  2) Get file info
       Generic JPEG:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 512,
    md5: '091b3f259662aa31e2ffef4519951168',
    orientation: undefined,
+   porn: false,
    size: 25360,
...
    },
    width: 512
  }
      + expected - actual
       {
         "height": 512
         "md5": "091b3f259662aa31e2ffef4519951168"
         "orientation": [undefined]
      -  "porn": false
         "size": 25360
         "type": {
           "ext": "jpg"
           "mime": "image/jpeg"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:36:10
  3) Get file info
       Generic APNG:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 256,
    md5: '08189c607bea3b952704676bb3c979e0',
    orientation: undefined,
+   porn: false,
    size: 1868,
...
    },
    width: 256
  }
      + expected - actual
       {
         "height": 256
         "md5": "08189c607bea3b952704676bb3c979e0"
         "orientation": [undefined]
      -  "porn": false
         "size": 1868
         "type": {
           "ext": "apng"
           "mime": "image/apng"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:55:10
  4) Get file info
       Generic AGIF:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 256,
    md5: '32c47a11555675d9267aee1a86571e7e',
    orientation: undefined,
+   porn: false,
    size: 2248,
...
    },
    width: 256
  }
      + expected - actual
       {
         "height": 256
         "md5": "32c47a11555675d9267aee1a86571e7e"
         "orientation": [undefined]
      -  "porn": false
         "size": 2248
         "type": {
           "ext": "gif"
           "mime": "image/gif"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:74:10
  5) Get file info
       PNG with alpha:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 256,
    md5: 'f73535c3e1e27508885b69b10cf6e991',
    orientation: undefined,
+   porn: false,
    size: 3772,
...
    },
    width: 256
  }
      + expected - actual
       {
         "height": 256
         "md5": "f73535c3e1e27508885b69b10cf6e991"
         "orientation": [undefined]
      -  "porn": false
         "size": 3772
         "type": {
           "ext": "png"
           "mime": "image/png"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:93:10
  6) Get file info
       Generic SVG:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 256,
    md5: 'b6f52b4b021e7b92cdd04509c7267965',
    orientation: undefined,
+   porn: false,
    size: 505,
...
    },
    width: 256
  }
      + expected - actual
       {
         "height": 256
         "md5": "b6f52b4b021e7b92cdd04509c7267965"
         "orientation": [undefined]
      -  "porn": false
         "size": 505
         "type": {
           "ext": "svg"
           "mime": "image/svg+xml"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:112:10
  7) Get file info
       SVG with XML definition:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 256,
    md5: '4b7a346cde9ccbeb267e812567e33397',
    orientation: undefined,
+   porn: false,
    size: 544,
...
    },
    width: 256
  }
      + expected - actual
       {
         "height": 256
         "md5": "4b7a346cde9ccbeb267e812567e33397"
         "orientation": [undefined]
      -  "porn": false
         "size": 544
         "type": {
           "ext": "svg"
           "mime": "image/svg+xml"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:132:10
  8) Get file info
       Dimension limit:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 25000,
    md5: '268c5dde99e17cf8fe09f1ab3f97df56',
    orientation: undefined,
+   porn: false,
    size: 75933,
...
    },
    width: 25000
  }
      + expected - actual
       {
         "height": 25000
         "md5": "268c5dde99e17cf8fe09f1ab3f97df56"
         "orientation": [undefined]
      -  "porn": false
         "size": 75933
         "type": {
           "ext": [null]
           "mime": "application/octet-stream"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:151:10
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
  9) Get file info
       Rotate JPEG:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped
  {
    height: 256,
    md5: '68d5b2d8d1d1acbbce99203e3ec3857e',
    orientation: 8,
+   porn: false,
    size: 12624,
...
    },
    width: 512
  }
      + expected - actual
       {
         "height": 256
         "md5": "68d5b2d8d1d1acbbce99203e3ec3857e"
         "orientation": 8
      -  "porn": false
         "size": 12624
         "type": {
           "ext": "jpg"
           "mime": "image/jpeg"
      at file:///home/runner/work/misskey/misskey/packages/backend/test/get-file-info.ts:170:10
error Command failed with exit code 9.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 9.
```

**Comment by ThatOneCalculator** [comment]
Fixed by 207d7e04783cc20bfe26fbb8aed83be2ade6f797
