### ISSUE TITLE
Integrations causing internal server error

### ISSUE THREAD

**Issue by y4my4my4m** [syuilo/Misskey#8987]
## 💡 Summary

When trying to login via integration (all 3), an internal server error occurs.

## 🥰 Expected Behavior

Should login using the integration service

### Twitter
```
0|npm  |   TypeError: autwh is not a function
0|npm  |       at getTwAuth (file:///home/misskey/packages/backend/built/server/api/service/twitter.js:52:1
6)
0|npm  |       at runMicrotasks (<anonymous>)
0|npm  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|npm  |       at async file:///home/misskey/packages/backend/built/server/api/service/twitter.js:78:20
0|npm  |       at async bodyParser (/home/misskey/packages/backend/node_modules/koa-bodyparser/index.js:95:
5)
0|npm  |       at async file:///home/misskey/packages/backend/built/server/api/index.js:27:5
0|npm  |       at async cors (/home/misskey/packages/backend/node_modules/@koa/cors/index.js:56:32)
0|npm  |       at async /home/misskey/packages/backend/node_modules/koa-mount/index.js:58:5
0|npm  |       at async file:///home/misskey/packages/backend/built/server/index.js:49:9
```
### Github
```
|npm  |   Error: Cannot send secure cookie over unencrypted connection
0|npm  |       at Cookies.set (/home/misskey/packages/backend/node_modules/cookies/index.js:94:11)
0|npm  |       at file:////home/misskey/packages/backend/built/server/api/service/github.js:85:17
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/koa-compose/index.js:42:32)
0|npm  |       at /home/misskey/packages/backend/node_modules/@koa/router/lib/router.js:363:16
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/koa-compose/index.js:42:32)
0|npm  |       at /home/misskey/packages/backend/node_modules/koa-compose/index.js:34:12
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/@koa/router/lib/router.js:368:31)
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/koa-compose/index.js:42:32)
0|npm  |       at bodyParser (/home/misskey/packages/backend/node_modules/koa-bodyparser/index.js:95:11)
0|npm  |       at runMicrotasks (<anonymous>)
0|npm  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|npm  |       at async file:///home/misskey/packages/backend/built/server/api/index.js:27:5
0|npm  |       at async cors (/home/misskey/packages/backend/node_modules/@koa/cors/index.js:56:32)
0|npm  |       at async /home/misskey/packages/backend/node_modules/koa-mount/index.js:58:5
0|npm  |       at async file:///home/misskey/packages/backend/built/server/index.js:49:9
```
### Discord
```
|npm  |   Error: Cannot send secure cookie over unencrypted connection
0|npm  |       at Cookies.set (/home/misskey/packages/backend/node_modules/cookies/index.js:94:11)
0|npm  |       at file:////home/misskey/packages/backend/built/server/api/service/discord.js:87:17
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/koa-compose/index.js:42:32)
0|npm  |       at /home/misskey/packages/backend/node_modules/@koa/router/lib/router.js:363:16
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/koa-compose/index.js:42:32)
0|npm  |       at /home/misskey/packages/backend/node_modules/koa-compose/index.js:34:12
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/@koa/router/lib/router.js:368:31)
0|npm  |       at dispatch (/home/misskey/packages/backend/node_modules/koa-compose/index.js:42:32)
0|npm  |       at bodyParser (/home/misskey/packages/backend/node_modules/koa-bodyparser/index.js:95:11)
0|npm  |       at runMicrotasks (<anonymous>)
0|npm  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|npm  |       at async file:///home/misskey/packages/backend/built/server/api/index.js:27:5
0|npm  |       at async cors (/home/misskey/packages/backend/node_modules/@koa/cors/index.js:56:32)
0|npm  |       at async /home/misskey/packages/backend/node_modules/koa-mount/index.js:58:5
0|npm  |       at async file:///home/misskey/packages/backend/built/server/index.js:49:9
```

## 📝 Steps to Reproduce

1. Add integration key/secret
2. Attempt to login
3. Error occurs

## 📌 Environment

Misskey: 12.110.1
Node.js: v16.15.0
PostgreSQL: 13.4
Redis: 6.2.5
Vue: 3.2.31

Running on EC2 AWS, using pm2 to run Node process.

## 他

自分の環境の問題かもしれないですが、原因よく分からない。ホームページが正しくHTTPS認証されているけど、、

**Comment by y4my4my4m** [comment]
I tried setting `app.proxy = true` in other files, but it didnt seem to work.
Anyway it's set in the [server/index.ts](https://github.com/misskey-dev/misskey/blob/4550a4459bb9fc021211e438d135d464c018ce47/packages/backend/src/server/index.ts#L36)
参考書：https://github.com/koajs/koa/issues/974

**Comment by y4my4my4m** [comment]
I fixed the github and discord one.

I had to modify the `/etc/nginx/mysite.conf` and uncomment these:
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
```

Twitter still not working, somehow.

**Comment by y4my4my4m** [comment]
https://github.com/syuilo/autwh のバグかな？ 🤔 

```js
// index_test.js
const autwh = require('autwh');
const _a = autwh({
  consumerKey: 'XXX', //実際のキー
  consumerSecret: 'XXX',
  callbackUrl: 'https://mysite.com/api/tw/cb'
});

console.log(_a);
```

`node index_test.js`
にすると `TypeError: autwh is not a function`エラーがでます。

**Comment by y4my4my4m** [comment]
なんかおかしいけど、だめなworkaroundで解決できた。
- `yarn install oauth`
- `curl -O https://raw.githubusercontent.com/syuilo/autwh/master/src/index.ts > autwh.ts`
- 
  ```js
  // const OAuth = require('oauth').OAuth; // replace this
  import { OAuth } from 'oauth'; // with this
  ```
- 
  ```js
  //twitter.js
  import autwh from './autwh'
  ```
- `yarn build`

で想定通りに動いています

But of course that's a terrible way to go about it.

**Comment by tamaina** [comment]
@syuilo 直してたりする？

**Comment by syuilo** [comment]
> 

特にはまだ対応してない

**Comment by futchitwo** [comment]
外部連携は廃止されたのでcloseして良さそうです
