### ISSUE TITLE
npm run migrateに失敗する

### ISSUE THREAD

**Issue by ikuradon** [syuilo/Misskey#9079]
## 💡 Summary

`typeorm migration:run`がエラーで止まる
47b2e56967744fd9c09a853c8044e3a448783ec5 でアップデートされたtypeorm 0.3.8にバグがある(https://github.com/typeorm/typeorm/issues/9330)

## 🥰 Expected Behavior

データベース更新が正常に終わる

## 🤬 Actual Behavior

```
> misskey@12.118.1 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js

Error during migration run:
TypeError: dataSourceFileExports is not iterable
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:29:34)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.19.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.0>
npm notice Run `npm install -g npm@8.19.0` to update!
npm notice 
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.19.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.0>
npm notice Run `npm install -g npm@8.19.0` to update!
npm notice
```
## 📝 Steps to Reproduce

1. 47b2e56967744fd9c09a853c8044e3a448783ec5 以降のコミットへコードをアップデートする
2. `npm run migrate`する

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by ikuradon** [comment]
[Release 0.3.9 · typeorm/typeorm](https://github.com/typeorm/typeorm/releases/tag/0.3.9)で修正されているっぽい？

**Comment by rinsuki** [comment]
たぶん？
