### ISSUE TITLE
Yarn run init gives back Error during migration run: TypeError: dataSourceFileExports is not iterable on macOS 

### ISSUE THREAD

**Issue by S0ulf3re** [syuilo/Misskey#9082]
I'm trying to initalize the database for Misskey to run locally on my macbook. But I keep getting the following whenever I try to run ```yarn run init```

```
Error during migration run:
TypeError: dataSourceFileExports is not iterable
    at CommandUtils.loadDataSource (/Users/daniel/Developer/toonkey/node_modules/.store/typeorm-virtual-d5653af815/node_modules/typeorm/commands/CommandUtils.js:29:34)
    at async Object.handler (/Users/daniel/Developer/toonkey/node_modules/.store/typeorm-virtual-d5653af815/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
```

So far I've tried moving the Postgres database folder to a local directory in my home directory. I should also note that under my configuration, both Misskey and Postgres run under one user. Aside from this, Misskey compiles just fine and I was able to start it, aside from the errors from the lack of database. Looking in pgadmin, It seems that the script never actually sets up the database. I'm not sure if this is a problem with my Postgres configuration. Or if macOS is doing something odd.

This looks like It might be related to #9079

**Comment by S0ulf3re** [comment]
Ok so major breakthrough. I managed to fix this by upgrading Typeorm via Yarn. I'll leave this open in case anyone wants to discuss this further since It seems to be a running problem for some people
