### ISSUE TITLE
ユーザー一覧などを見れない

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#9101]
## 💡 Summary
ユーザーの一覧などが 問題が発生しました。
となり 読み込めない

## 🥰 Expected Behavior
ちゃんとユーザー一覧などを表示する

## 🤬 Actual Behavior
```
ERR 1 [api] Internal error occurred in admin/show-users: Cannot read properties of undefined (reading 'packMany') TypeError: Cannot read properties of undefined (reading 'packMany')

at file:///home/mattyatea/misskey/packages/backend/built/server/api/endpoints/admin/show-users.js:116:49

at runMicrotasks (<anonymous>>

at processTicksAndRejections (node: internal/process/task_queues:96:5)

at async ApicallService.call (file:///home/mattyatea/misskey/packages/backend/built/server/api/ApicallService.js:201:16)

INFO 1 [server]

-->POST /api/admin/show-users 500 72ms 701b
```

## 📝 Steps to Reproduce

1.コントロールパネルを開く
2.ユーザー を押す
3.問題が発生しました となる

## 📌 Environment

Misskey version:12.120.0-alpha.4
Your OS:android 11
Your browser:vivaldi 5.4.2760.36

**Comment by mattyatea** [comment]
![IMG_20220922_031937](https://user-images.githubusercontent.com/56515516/191581005-3991258d-20d6-43f8-a693-d6b9e0fdaba3.jpg)
このような感じ
