### ISSUE TITLE
解決済みの通報が見れない

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#9183]
## 💡 Summary
解決済みの通報が見れない

## 🥰 Expected Behavior
ちゃんと見れるようになる

## 🤬 Actual Behavior
エラーログ
`
EntityNotFoundError: Could not find any entity of type "User" matching: {
    "where": {
        "id": "95ebzgq377"
    },
    "relations": {
        "avatar": true,
        "banner": true
    }
}
    at /home/misskey/mattyatea-misskey/packages/backend/node_modules/typeorm/entity-manager/EntityManager.js:591:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UserEntityService.pack (file:///home/misskey/mattyatea-misskey/packages/backend/built/core/entities/UserEntityService.js:242:20)
    at async Promise.all (index 8)
    at async awaitAll (file:///home/misskey/mattyatea-misskey/packages/backend/built/misc/prelude/await-all.js:5:28)
    at async AbuseUserReportEntityService.pack (file:///home/misskey/mattyatea-misskey/packages/backend/built/core/entities/AbuseUserReportEntityService.js:24:16)
    at async Promise.all (index 3)
    at async file:///home/misskey/mattyatea-misskey/packages/backend/built/server/api/endpoints/admin/abuse-user-reports.js:126:20
    at async ApiCallService.call (file:///home/misskey/mattyatea-misskey/packages/backend/built/server/api/ApiCallService.js:201:16)
`

## 📝 Steps to Reproduce

1.通報のとこにいく
2.解決済みにする
3.えらー！！

## 📌 Environment

Misskey version: 12.120.0-alpha.7
Your OS: Windows 11
Your browser:  Floorp 10.7.0

**Comment by atsu1125** [comment]
`abuse_user_report`の`targetUserId`のアカウントが削除されている場合に読み込みに失敗している模様

**Comment by atsu1125** [comment]
ワークアラウンドとしてはSQLで`"user"`に存在しないアカウントが関係するものを`abuse_user_report`から削除することで解決することは可能であった

**Comment by atsu1125** [comment]
ここ ( https://github.com/misskey-dev/misskey/commit/bec2d9e3fafd721f116066f6a7e3ff0507b27de9 ) で通報の外部キー制約がコメントアウトされたかなーって感じはするけど
マイグレーション時にエラーになるインスタンスがあるのね
```
DELETE FROM "abuse_user_report" WHERE "targetUserId" NOT IN (SELECT "id" FROM "user")
```
して
```
ALTER TABLE "abuse_user_report" ADD CONSTRAINT "FK_a9021cc2e1feb5f72d3db6e9f5f" FOREIGN KEY ("targetUserId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
```
を手動で実行で解決？
