### ISSUE TITLE
server won't startup without @tensorflow/tfjs-node

### ISSUE THREAD

**Issue by grainrigi** [syuilo/Misskey#9202]
## 💡 Summary

With #8984 and #8986, tensorflow has been moved into optionalDependencies and the server should work fine without `@tensorflow/tfjs-node`. However, without the package, initial module resolution still fails since the server statically imports `nsfwjs`, which imports `@tensorflow/tfjs` statically.

## 🥰 Expected Behavior

Even if `@tensorflow/tfjs-node` is not installed at all, the server boots up without any problem.

## 🤬 Actual Behavior

Server fails to boot with the following error:

```
Error: Cannot find module '@tensorflow/tfjs'
Require stack:
- /misskey/packages/backend/node_modules/nsfwjs/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/misskey/packages/backend/node_modules/nsfwjs/dist/index.js:62:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async workerMain (file:///misskey/packages/backend/built/boot/worker.js:9:5)
    at async default (file:///misskey/packages/backend/built/boot/index.js:25:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/misskey/packages/backend/node_modules/nsfwjs/dist/index.js' ]
}
```

## 📝 Steps to Reproduce

1. edit `scripts/install-packages.js` and add `--ignore-optional` option to the yarn install of `packages/backend`
2. build the docker image
3. bring up with docker-compose

## 📌 Environment

Misskey version: 12.119.0
Your OS: [balenalib/i386-node:16.15.1-bullseye](https://hub.docker.com/layers/balenalib/i386-node/16.15.1-bullseye/images/sha256-410e853c3d948d726443e02a5e30bb2229f21b2566b9e94969a71193a9a3f9c5?context=explore)
Your browser: N/A

**Comment by grainrigi** [comment]
There are two options to resolve this problem.

1. Import `nsfwjs` dynamically

Patch the source like this:

```diff
diff --git a/packages/backend/src/services/detect-sensitive.ts b/packages/backend/src/services/detect-sensitive.ts
index 2ade39d52..4e5ffdee0 100644
--- a/packages/backend/src/services/detect-sensitive.ts
+++ b/packages/backend/src/services/detect-sensitive.ts
@@ -1,7 +1,7 @@
 import * as fs from 'node:fs';
 import { fileURLToPath } from 'node:url';
 import { dirname } from 'node:path';
-import * as nsfw from 'nsfwjs';
+import type * as nsfw from 'nsfwjs';
 import si from 'systeminformation';
 
 const _filename = fileURLToPath(import.meta.url);
@@ -25,6 +25,7 @@ export async function detectSensitive(path: string): Promise<nsfw.predictionType
                }
 
                const tf = await import('@tensorflow/tfjs-node');
+               const nsfw = await import('nsfwjs');
 
                if (model == null) model = await nsfw.load(`file://${_dirname}/../../nsfw-model/`, { size: 299 });

```

This will delay the import of nsfwjs until the first invocation of `detectSensitive`.
By disabling nsfw detection feature, we can avoid the problem completely.

2. Add `@tensorflow/tfjs` (not tfjs-node) to dependencies

Since `@tensorflow/tfjs` is a peer dependency of `nsfwjs`, we should install `@tensorflow/tfjs` ourselves. (at least in yarn, `peerDependencies` are not meant to be installed automatically)
Currently, `@tensorflow/tfjs-node` is optional, so we need to add `@tensorflow/tfjs` separately to the dependencies like this:

```diff
diff --git a/packages/backend/package.json b/packages/backend/package.json
index be8283e4a..c77386cce 100644
--- a/packages/backend/package.json
+++ b/packages/backend/package.json
@@ -26,6 +26,7 @@
                "@peertube/http-signature": "1.7.0",
                "@sinonjs/fake-timers": "9.1.2",
                "@syuilo/aiscript": "0.11.1",
+               "@tensorflow/tfjs": "3.20.0",
                "ajv": "8.11.0",
                "archiver": "5.3.1",
                "autobind-decorator": "2.4.0",
```

This won't be a problem because `@tensorflow/tfjs` does not require any prebuilt binaries to be installed.

---

If you tell me which option to choose, I'm willing to make a PR to fix it.

**Comment by grainrigi** [comment]
Closing for #9206.
Just don't use `--ignore-optional`.
