### ISSUE TITLE
Error during migration run:

### ISSUE THREAD

**Issue by Annnnh1010** [syuilo/Misskey#9231]
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
> misskey@12.119.0 migrateandstart
> npm run migrate && npm run start
> misskey@12.119.0 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot read properties of null (reading 'url')
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)

**Comment by KisaragiEffective** [comment]
triage: this issue needs more information from you, and 2024.5.0 does not have such issue.
Please re-open if this still happens after adding information.
