### ISSUE TITLE
The image cropping function cannot be used after changing the domain name

### ISSUE THREAD

**Issue by KormiMeiko** [syuilo/Misskey#9246]
## 🥰 Expected Behavior
Upload the image, click crop, and the cropping is complete.

## 🤬 Actual Behavior
Upload the picture, and then click the crop button, but the pop-up cropping window is always loading.
---
Browser console error:
GET https://www.MyDomain.com/proxy/image.webp?url=https%3A%2F%2Fwww.MyDomain.com%2Ffiles%2F2b03a934-583b-480e-aa2f-3fc00d41e462 500
---
cropper-dialog.6fe325e6.js:1 
Uncaught (in promise) Error: Failed to load the image source
    at cropper-dialog.6fe325e6.js:1:14508
    at new Promise (<anonymous>)
    at HTMLElement.$ready (cropper-dialog.6fe325e6.js:1:14480)
    at HTMLElement.connectedCallback (cropper-dialog.6fe325e6.js:1:12658)
    at new ee (cropper-dialog.6fe325e6.js:1:35823)
    at cropper-dialog.6fe325e6.js:1:36969
    at Ie (vue.17211afe.js:4:653)
    at xe (vue.17211afe.js:4:731)
    at t.__weh.t.__weh (vue.17211afe.js:4:18582)
    at Mn (vue.17211afe.js:4:2174)
---
Uncaught (in promise) Error: Failed to load the image source
    at cropper-dialog.6fe325e6.js:1:14508
    at new Promise (<anonymous>)
    at HTMLElement.$ready (cropper-dialog.6fe325e6.js:1:14480)
    at HTMLElement.connectedCallback (cropper-dialog.6fe325e6.js:1:12848)
    at new ee (cropper-dialog.6fe325e6.js:1:35823)
    at cropper-dialog.6fe325e6.js:1:36969
    at Ie (vue.17211afe.js:4:653)
    at xe (vue.17211afe.js:4:731)
    at t.__weh.t.__weh (vue.17211afe.js:4:18582)
    at Mn (vue.17211afe.js:4:2174)

## 📝 Steps to Reproduce

1.Upload image
2.Click the crop button
3.The cropping window pops up, (always loading)

## 📌 Environment

Misskey version: v12.117.1
Your OS: Windows 11
Your browser: Microsoft Edge 107.0.1418.56

**Comment by Candinya** [comment]
Run 

``` SQL
SELECT "url" FROM drive_file WHERE "accessKey" = '2b03a934-583b-480e-aa2f-3fc00d41e462' LIMIT 1;
```

in your instance's postgres' query console. (started by `psql`)

Is it still pointing to the old domain (which is inaccessible now)?

**Comment by KormiMeiko** [comment]
> 

it shows: (by psql)
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist

**Comment by KormiMeiko** [comment]
> > 
> 
> it shows: (by psql) psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: role "root" does not exist

And I logged into the database through Navicat and checked the "url" in "drive_file", the link inside is correct and accessible

**Comment by KormiMeiko** [comment]
> 

I ran a query in Navicat and it shows:

SELECT "url" FROM drive_file WHERE "accessKey" = '2b03a934-583b-480e-aa2f-3fc00d41e462' LIMIT 1
> OK
> 0.271s
