### ISSUE TITLE
The image cropping function cannot be used after changing the domain name

### ISSUE THREAD

**Issue by KormiMeiko** [syuilo/Misskey#9248]
## 💡 Summary

The image cropping function cannot be used after changing the domain name

Before these operations, I replaced the domain name of the instance in the database (global replacement). And the address of the resource is recorded correctly in the database (including those uploaded later). But the window for the image cropping function keeps loading.
## 🥰 Expected Behavior
Upload the image, click crop, and the cropping is complete.

## 🤬 Actual Behavior
Upload the picture, and then click the crop button, but the pop-up cropping window is always loading.

Browser console error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'focus') at app.da56189f.js:53:8202

GET https://www.MyDomain.com/proxy/image.webp?url=https%3A%2F%2Fwww.MyDomain.com%2Ffiles%2F2b03a934-583b-480e-aa2f-3fc00d41e462 500

Uncaught (in promise) Error: Failed to load the image source
    at MkCropperDialog.b0765928.js:1:14525
    at new Promise (<anonymous>)
    at HTMLElement.$ready (MkCropperDialog.b0765928.js:1:14497)
    at HTMLElement.connectedCallback (MkCropperDialog.b0765928.js:1:12675)
    at new ee (MkCropperDialog.b0765928.js:1:35840)
    at MkCropperDialog.b0765928.js:1:36987
    at Se (vue.8d31fef4.js:4:653)
    at xe (vue.8d31fef4.js:4:731)
    at t.__weh.t.__weh (vue.8d31fef4.js:4:18542)
    at vn (vue.8d31fef4.js:4:2024)

Uncaught (in promise) Error: Failed to load the image source
    at MkCropperDialog.b0765928.js:1:14525
    at new Promise (<anonymous>)
    at HTMLElement.$ready (MkCropperDialog.b0765928.js:1:14497)
    at HTMLElement.connectedCallback (MkCropperDialog.b0765928.js:1:12865)
    at new ee (MkCropperDialog.b0765928.js:1:35840)
    at MkCropperDialog.b0765928.js:1:36987
    at Se (vue.8d31fef4.js:4:653)
    at xe (vue.8d31fef4.js:4:731)
    at t.__weh.t.__weh (vue.8d31fef4.js:4:18542)
    at vn (vue.8d31fef4.js:4:2024)
## 📝 Steps to Reproduce

1.Upload image
2.Click the crop button
3.The cropping window pops up, (always loading)

## 📌 Environment

Misskey version: v12.119.0
Your OS: Windows 11
Your browser: Microsoft Edge 107.0.1418.56

**Comment by tamaina** [comment]
Do not change the domain name
