### ISSUE TITLE
トークン再生成などによりAuthentication Failedになった場合、ログアウトするように

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9322]
## Summary
自動的にログアウト or ログアウトを促すメッセージを表示

**Comment by tamaina** [comment]
api/iの応答って、

トークン再生成→403 Authentication failed

アカウント削除（admin, ユーザーによる閉鎖）→ 

```
{"error":{"message":"Internal error occurred. Please contact us if the error persists.","code":"INTERNAL_ERROR","id":"5d37dbcb-891e-41ca-a3d6-e690c97775ac","kind":"server","info":{"e":{"message":"Could not find any entity of type \"UserProfile\" matching: {\n    \"where\": {\n        \"userId\": \"9bf3pj3yug\"\n    },\n    \"relations\": [\n        \"user\"\n    ]\n}","code":"EntityNotFoundError","stack":"EntityNotFoundError: Could not find any entity of type \"UserProfile\" matching: {\n    \"where\": {\n        \"userId\": \"9bf3pj3yug\"\n    },\n    \"relations\": [\n        \"user\"\n    ]\n}\n    at /home/aqz/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.9.0/node_modules/typeorm/entity-manager/EntityManager.js:604:39\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///home/aqz/misskey/packages/backend/built/server/api/endpoints/i.js:39:33\n    at async ApiCallService.call (file:///home/aqz/misskey/packages/backend/built/server/api/ApiCallService.js:275:16)"}}}}
```

みたいになっておかしいなと思ったんだけど、アカウント削除が正常に終了していないだけだったっぽいな

**Comment by tamaina** [comment]
ユーザーを完全に消せていないのではなくクエリキャッシュのせいであることにコードをいじってようやく理解した
