### ISSUE TITLE
高確率でService Workerがビルドできない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9328]
## 💡 Summary

`yarn build` でbackend, client, swのビルド中、swのビルドで高確率モジュール解決エラーが発生する

## 🥰 Expected Behavior
エラーなしでビルドできる

## 🤬 Actual Behavior

高い確率でエラーが発生する。
何回かinstallを繰り返すと解決する。

```
➤ YN0000: Starting SW building...
➤ YN0000: ✘ [ERROR] Could not resolve "misskey-js/built/acct"
➤ YN0000:
➤ YN0000:     src/filters/user.ts:2:22:
➤ YN0000:       2 │ import * as Acct from 'misskey-js/built/acct';
➤ YN0000:         ╵                       ~~~~~~~~~~~~~~~~~~~~~~~
➤ YN0000:
➤ YN0000:   You can mark the path "misskey-js/built/acct" as external to exclude it from the bundle, which will remove this error.
➤ YN0000:
➤ YN0000: ✘ [ERROR] Could not resolve "idb-keyval"
➤ YN0000:
➤ YN0000:     src/scripts/notification-read.ts:1:20:
➤ YN0000:       1 │ import { get } from 'idb-keyval';
➤ YN0000:         ╵                     ~~~~~~~~~~~~
➤ YN0000:
➤ YN0000:   You can mark the path "idb-keyval" as external to exclude it from the bundle, which will remove this error.
➤ YN0000:
➤ YN0000: ✘ [ERROR] Could not resolve "idb-keyval"
➤ YN0000:
➤ YN0000:     src/scripts/get-account-from-id.ts:1:20:
➤ YN0000:       1 │ import { get } from 'idb-keyval';
➤ YN0000:         ╵                     ~~~~~~~~~~~~
➤ YN0000:
➤ YN0000:   You can mark the path "idb-keyval" as external to exclude it from the bundle, which will remove this error.
➤ YN0000:
➤ YN0000: ✘ [ERROR] Could not resolve "idb-keyval"
➤ YN0000:
➤ YN0000:     src/scripts/lang.ts:4:25:
➤ YN0000:       4 │ import { get, set } from 'idb-keyval';
➤ YN0000:         ╵                          ~~~~~~~~~~~~
➤ YN0000:
➤ YN0000:   You can mark the path "idb-keyval" as external to exclude it from the bundle, which will remove this error.
➤ YN0000:
➤ YN0000: ✘ [ERROR] Could not resolve "misskey-js"
➤ YN0000:
➤ YN0000:     src/scripts/operations.ts:5:25:
➤ YN0000:       5 │ import * as Misskey from 'misskey-js';
➤ YN0000:         ╵                          ~~~~~~~~~~~~
➤ YN0000:
➤ YN0000:   You can mark the path "misskey-js" as external to exclude it from the bundle, which will remove this error.
➤ YN0000:
➤ YN0000: /home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:1624
➤ YN0000:   let error = new Error(`${text}${summary}`);
➤ YN0000:               ^
➤ YN0000:
➤ YN0000: Error: Build failed with 5 errors:
➤ YN0000: src/filters/user.ts:2:22: ERROR: Could not resolve "misskey-js/built/acct"
➤ YN0000: src/scripts/get-account-from-id.ts:1:20: ERROR: Could not resolve "idb-keyval"
➤ YN0000: src/scripts/lang.ts:4:25: ERROR: Could not resolve "idb-keyval"
➤ YN0000: src/scripts/notification-read.ts:1:20: ERROR: Could not resolve "idb-keyval"
➤ YN0000: src/scripts/operations.ts:5:25: ERROR: Could not resolve "misskey-js"
➤ YN0000:     at failureErrorWithLog (/home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:1624:15)
➤ YN0000:     at /home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:1266:28
➤ YN0000:     at runOnEndCallbacks (/home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:1179:65)
➤ YN0000:     at buildResponseToResult (/home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:1264:7)
➤ YN0000:     at /home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:1377:14
➤ YN0000:     at /home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:678:9
➤ YN0000:     at handleIncomingPacket (/home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:775:9)
➤ YN0000:     at Socket.readFromStdout (/home/cyberrex/misskey/.yarn/unplugged/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/lib/main.js:644:7)
➤ YN0000:     at Socket.emit (node:events:513:28)
➤ YN0000:     at addChunk (node:internal/streams/readable:324:12) {
➤ YN0000:   errors: [
➤ YN0000:     {
➤ YN0000:       detail: undefined,
➤ YN0000:       id: '',
➤ YN0000:       location: {
➤ YN0000:         column: 22,
➤ YN0000:         file: 'src/filters/user.ts',
➤ YN0000:         length: 23,
➤ YN0000:         line: 2,
➤ YN0000:         lineText: "import * as Acct from 'misskey-js/built/acct';",
➤ YN0000:         namespace: '',
➤ YN0000:         suggestion: ''
➤ YN0000:       },
➤ YN0000:       notes: [
➤ YN0000:         {
➤ YN0000:           location: null,
➤ YN0000:           text: 'You can mark the path "misskey-js/built/acct" as external to exclude it from the bundle, which will remove this error.'
➤ YN0000:         }
➤ YN0000:       ],
➤ YN0000:       pluginName: '',
➤ YN0000:       text: 'Could not resolve "misskey-js/built/acct"'
➤ YN0000:     },
➤ YN0000:     {
➤ YN0000:       detail: undefined,
➤ YN0000:       id: '',
➤ YN0000:       location: {
➤ YN0000:         column: 20,
➤ YN0000:         file: 'src/scripts/get-account-from-id.ts',
➤ YN0000:         length: 12,
➤ YN0000:         line: 1,
➤ YN0000:         lineText: "import { get } from 'idb-keyval';",
➤ YN0000:         namespace: '',
➤ YN0000:         suggestion: ''
➤ YN0000:       },
➤ YN0000:       notes: [
➤ YN0000:         {
➤ YN0000:           location: null,
➤ YN0000:           text: 'You can mark the path "idb-keyval" as external to exclude it from the bundle, which will remove this error.'
➤ YN0000:         }
➤ YN0000:       ],
➤ YN0000:       pluginName: '',
➤ YN0000:       text: 'Could not resolve "idb-keyval"'
➤ YN0000:     },
➤ YN0000:     {
➤ YN0000:       detail: undefined,
➤ YN0000:       id: '',
➤ YN0000:       location: {
➤ YN0000:         column: 25,
➤ YN0000:         file: 'src/scripts/lang.ts',
➤ YN0000:         length: 12,
➤ YN0000:         line: 4,
➤ YN0000:         lineText: "import { get, set } from 'idb-keyval';",
➤ YN0000:         namespace: '',
➤ YN0000:         suggestion: ''
➤ YN0000:       },
➤ YN0000:       notes: [
➤ YN0000:         {
➤ YN0000:           location: null,
➤ YN0000:           text: 'You can mark the path "idb-keyval" as external to exclude it from the bundle, which will remove this error.'
➤ YN0000:         }
➤ YN0000:       ],
➤ YN0000:       pluginName: '',
➤ YN0000:       text: 'Could not resolve "idb-keyval"'
➤ YN0000:     },
➤ YN0000:     {
➤ YN0000:       detail: undefined,
➤ YN0000:       id: '',
➤ YN0000:       location: {
➤ YN0000:         column: 20,
➤ YN0000:         file: 'src/scripts/notification-read.ts',
➤ YN0000:         length: 12,
➤ YN0000:         line: 1,
➤ YN0000:         lineText: "import { get } from 'idb-keyval';",
➤ YN0000:         namespace: '',
➤ YN0000:         suggestion: ''
➤ YN0000:       },
➤ YN0000:       notes: [
➤ YN0000:         {
➤ YN0000:           location: null,
➤ YN0000:           text: 'You can mark the path "idb-keyval" as external to exclude it from the bundle, which will remove this error.'
➤ YN0000:         }
➤ YN0000:       ],
➤ YN0000:       pluginName: '',
➤ YN0000:       text: 'Could not resolve "idb-keyval"'
➤ YN0000:     },
➤ YN0000:     {
➤ YN0000:       detail: undefined,
➤ YN0000:       id: '',
➤ YN0000:       location: {
➤ YN0000:         column: 25,
➤ YN0000:         file: 'src/scripts/operations.ts',
➤ YN0000:         length: 12,
➤ YN0000:         line: 5,
➤ YN0000:         lineText: "import * as Misskey from 'misskey-js';",
➤ YN0000:         namespace: '',
➤ YN0000:         suggestion: ''
➤ YN0000:       },
➤ YN0000:       notes: [
➤ YN0000:         {
➤ YN0000:           location: null,
➤ YN0000:           text: 'You can mark the path "misskey-js" as external to exclude it from the bundle, which will remove this error.'
➤ YN0000:         }
➤ YN0000:       ],
➤ YN0000:       pluginName: '',
➤ YN0000:       text: 'Could not resolve "misskey-js"'
➤ YN0000:     }
➤ YN0000:   ],
➤ YN0000:   warnings: []
➤ YN0000: }
➤ YN0000:
➤ YN0000: Node.js v18.12.1
```

## 📝 Steps to Reproduce

1. `yarn install`
2. `yarn build`

発生する条件は調査中

## 📌 Environment

Misskey version: 12.120.0-alpha.15
Your OS: Ubuntu 20.04
Node: v18.12.1
Yarn: v3.3.0

**Comment by tamaina** [comment]
経験したことないけど、yarn installがぶっ壊れてるのは確実

**Comment by CyberRex0** [comment]
yarn v3からnode_modulesがなくなってcacheからの都度展開が使われるようになったのが原因？どうみてもnode_modulesを探してるように見える

**Comment by tamaina** [comment]
yarn installはシンボリックリンクを張るような？

**Comment by CyberRex0** [comment]
> yarn installはシンボリックリンクを張るような？

かも(

**Comment by CyberRex0** [comment]
nodeLinkerをnode-modulesにしたらエラー消えたんだけど

**Comment by CyberRex0** [comment]
swのエラーはなくなったけど今度はclientがビルドできなくなった
従来のパッケージの重複インストールにも戻るしメリットないな
いじらずエラーを解消する方法を探さないと

**Comment by CyberRex0** [comment]
なんかVite 4になってから発生しなくなった気がするので再発するまではclose

**Comment by yitsushi** [comment]
With 13.11.2 I had the same (or at least very similar) error message today when I tried to update Misskey. I issued both `pnpm run clean` and `pnpm run clean-all` (and then `pnpm install`), but I still have this issue when I try to run `pnpm run build`.

> I wrote this down here, because when I tried to figure out what's the problem I couldn't find much helpful information, only this issue and #9624 that's similar to mine. Others may end up with this issue and it can be useful to them.

I don't know what created/generated the file earlier, but after I removed the `~/.pnp.cjs` file, it worked. Found this while I tried to debug and figure out what's the problem.

```
cd packages/sw
pnpm run build
```

and the error[^1] (similar to posted one) mentioned that file

```javascript
        {
          location: {
            column: 33,
            file: '../../../.pnp.cjs',
            length: 66,
            line: 45,
            lineText: '          "packageDependencies": [',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "misskey-js" here because it's not listed as a dependency of this package:`
        },
```

I opened the file to check what's inside and realized it's outside the misskey repository, first just renamed the file `mv ~/.pnp.cjs  ~/.pnp.cjs.bck` (later deleted completely) and that's resolved the issue, after that I could build and restart the service.

I did not have any similar issues before.

[^1]: https://bin.efertone.me/?dd4bd460bb37e41b#7ujK66HixKt7jM5YZsEw7sweRAyCvR1GvkHRZix6VEZ
