### ISSUE TITLE
Database problems after upgrading v13.0.0-beta.18 from v13.0.0-beta.17

### ISSUE THREAD

**Issue by creamlike1024** [syuilo/Misskey#9475]
## 💡 Summary

After upgrade to v13.0.0-beta.18 from v13.0.0-beta.17, The Timeline cannot be loaded, and errors in logs

beta.18 seems drop some columns. The log shows that the migration have been executed, but still encountered database problems.

Everything works OK in v13.0.0-beta.17

The postgresql version is 12.2-alpine(docker). Same problem applies to postgresql 15

## 🥰 Expected Behavior

No error message

## 🤬 Actual Behavior

web container log:
```
misskey-web-1  | query: SELECT * FROM current_schema()
misskey-web-1  | query: SELECT version();
misskey-web-1  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
misskey-web-1  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
misskey-web-1  | 159 migrations are already loaded in the database.
misskey-web-1  | 162 migrations were found in the source code.
misskey-web-1  | PerUserPvChart1672562400597 is the last executed migration. It was executed on Sun Jan 01 2023 08:40:00 GMT+0000 (Coordinated Universal Time).
misskey-web-1  | 3 migrations are new migrations must be executed.
misskey-web-1  | query: START TRANSACTION
misskey-web-1  | query: ALTER TABLE "instance" DROP COLUMN "latestRequestSentAt"
misskey-web-1  | query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1672703171386,"removeLatestRequestSentAt1672703171386"]
misskey-web-1  | Migration removeLatestRequestSentAt1672703171386 has been  executed successfully.
misskey-web-1  | query: ALTER TABLE "instance" DROP COLUMN "lastCommunicatedAt"
misskey-web-1  | query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1672704017999,"removeLastCommunicatedAt1672704017999"]
misskey-web-1  | Migration removeLastCommunicatedAt1672704017999 has been  executed successfully.
misskey-web-1  | query: ALTER TABLE "instance" DROP COLUMN "latestStatus"
misskey-web-1  | query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1672704136584,"removeLatestStatus1672704136584"]
misskey-web-1  | Migration removeLatestStatus1672704136584 has been  executed successfully.
misskey-web-1  | query: COMMIT
misskey-web-1  | (node:90) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
misskey-web-1  | (Use `node --trace-warnings ...` to show where the warning was created)
misskey-web-1  |   _____ _         _           
misskey-web-1  |  |     |_|___ ___| |_ ___ _ _ 
misskey-web-1  |  | | | | |_ -|_ -| '_| -_| | |
misskey-web-1  |  |_|_|_|_|___|___|_,_|___|_  |
misskey-web-1  |  v13.0.0-beta.18         |___|
misskey-web-1  | 
misskey-web-1  |  Misskey is an open-source decentralized microblogging platform.
misskey-web-1  |  If you like Misskey, please donate to support development. https://www.patreon.com/syuilo
misskey-web-1  | 
misskey-web-1  | --- 86b7098272ef (PID: 90) ---
misskey-web-1  | INFO *	[core boot]	Welcome to Misskey!
misskey-web-1  | INFO *	[core boot]	Misskey v13.0.0-beta.18
misskey-web-1  | INFO *	[core boot env]	NODE_ENV: production
misskey-web-1  | INFO *	[core boot nodejs]	Version v18.12.1 detected.
misskey-web-1  | DONE *	[core boot config]	Loaded
misskey-web-1  | DONE *	[core boot]	Misskey initialized
misskey-web-1  | INFO *	[core boot]	Starting 2 workers...
misskey-web-1  | (node:107) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
misskey-web-1  | (Use `node --trace-warnings ...` to show where the warning was created)
misskey-web-1  | (node:101) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
misskey-web-1  | (Use `node --trace-warnings ...` to show where the warning was created)
misskey-web-1  | INFO 2	[core nest]	NestFactory: Starting Nest application...
misskey-web-1  | INFO 1	[core nest]	NestFactory: Starting Nest application...
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: RootModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: QueueModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: RootModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: QueueModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: GlobalModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: RepositoryModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: GlobalModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: RepositoryModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: CoreModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: EndpointsModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: ServerModule dependencies initialized
misskey-web-1  | INFO 2	[core nest]	InstanceLoader: QueueProcessorModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: CoreModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: EndpointsModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: ServerModule dependencies initialized
misskey-web-1  | INFO 1	[core nest]	InstanceLoader: QueueProcessorModule dependencies initialized
misskey-web-1  | DONE *	[core boot]	All workers started
misskey-web-1  | DONE *	[core boot]	Now listening on port 3000 on https://m.isle.moe
misskey-web-1  | INFO *	[core nest]	NestFactory: Starting Nest application...
misskey-web-1  | INFO *	[core nest]	InstanceLoader: QueueModule dependencies initialized
misskey-web-1  | INFO *	[core nest]	InstanceLoader: GlobalModule dependencies initialized
misskey-web-1  | INFO *	[core nest]	InstanceLoader: RepositoryModule dependencies initialized
misskey-web-1  | INFO *	[core nest]	InstanceLoader: DaemonModule dependencies initialized
misskey-web-1  | INFO *	[core nest]	InstanceLoader: CoreModule dependencies initialized
misskey-web-1  | [ioredis] Unhandled error event: Error: connect ETIMEDOUT
misskey-web-1  |     at Socket.<anonymous> (/misskey/node_modules/.store/ioredis-npm-4.28.5-74671f2fa3/node_modules/ioredis/built/redis/index.js:327:37)
misskey-web-1  |     at Object.onceWrapper (node:events:627:28)
misskey-web-1  |     at Socket.emit (node:events:513:28)
misskey-web-1  |     at Socket.emit (node:domain:489:12)
misskey-web-1  |     at Socket._onTimeout (node:net:562:8)
misskey-web-1  |     at listOnTimeout (node:internal/timers:564:17)
misskey-web-1  |     at process.processTimers (node:internal/timers:507:7)
misskey-web-1  | ERR  2	[queue system]	error undefined
misskey-web-1  | ERR  2	[queue deliver]	error undefined
misskey-web-1  | ERR  2	[queue inbox]	error undefined
misskey-web-1  | ERR  2	[queue db]	error undefined
misskey-web-1  | ERR  2	[queue objectStorage]	error undefined
misskey-web-1  | ERR  2	[queue webhook]	error undefined
misskey-web-1  | ERR  2	[queue deliver]	error undefined
misskey-web-1  | ERR  2	[queue inbox]	error undefined
misskey-web-1  | ERR  2	[queue webhook]	error undefined
misskey-web-1  | ERR  2	[queue db]	error undefined
misskey-web-1  | ERR  2	[queue objectStorage]	error undefined
misskey-web-1  | ERR  2	[queue system]	error undefined
misskey-web-1  | [ioredis] Unhandled error event: Error: connect ETIMEDOUT
misskey-web-1  |     at Socket.<anonymous> (/misskey/node_modules/.store/ioredis-npm-4.28.5-74671f2fa3/node_modules/ioredis/built/redis/index.js:327:37)
misskey-web-1  |     at Object.onceWrapper (node:events:627:28)
misskey-web-1  |     at Socket.emit (node:events:513:28)
misskey-web-1  |     at Socket.emit (node:domain:489:12)
misskey-web-1  |     at Socket._onTimeout (node:net:562:8)
misskey-web-1  |     at listOnTimeout (node:internal/timers:564:17)
misskey-web-1  |     at process.processTimers (node:internal/timers:507:7)
misskey-web-1  | ERR  1	[queue system]	error undefined
misskey-web-1  | ERR  1	[queue deliver]	error undefined
misskey-web-1  | ERR  1	[queue inbox]	error undefined
misskey-web-1  | ERR  1	[queue db]	error undefined
misskey-web-1  | ERR  1	[queue objectStorage]	error undefined
misskey-web-1  | ERR  1	[queue webhook]	error undefined
misskey-web-1  | ERR  1	[queue deliver]	error undefined
misskey-web-1  | ERR  1	[queue inbox]	error undefined
misskey-web-1  | ERR  1	[queue webhook]	error undefined
misskey-web-1  | ERR  1	[queue db]	error undefined
misskey-web-1  | ERR  1	[queue objectStorage]	error undefined
misskey-web-1  | ERR  1	[queue system]	error undefined
misskey-web-1  | ERR  2	[api]	Internal error occurred in notes/timeline: column Instance.latestRequestSentAt does not exist
misskey-web-1  | QueryFailedError: column Instance.latestRequestSentAt does not exist
misskey-web-1  |     at PostgresQueryRunner.query (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
misskey-web-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
misskey-web-1  |     at async SelectQueryBuilder.loadRawResults (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2132:25)
misskey-web-1  |     at async SelectQueryBuilder.executeEntitiesAndRawResults (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1992:26)
misskey-web-1  |     at async SelectQueryBuilder.getRawAndEntities (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/query-builder/SelectQueryBuilder.js:667:29)
misskey-web-1  |     at async SelectQueryBuilder.getOne (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/query-builder/SelectQueryBuilder.js:694:25)
misskey-web-1  |     at async Cache.fetch (file:///misskey/packages/backend/built/misc/cache.js:54:23)
misskey-web-1  |     at async Promise.all (index 10)
misskey-web-1  |     at async awaitAll (file:///misskey/packages/backend/built/misc/prelude/await-all.js:5:28)
misskey-web-1  |     at async UserEntityService.pack (file:///misskey/packages/backend/built/core/entities/UserEntityService.js:387:16)
misskey-web-1  |     at async Promise.all (index 3)
misskey-web-1  |     at async awaitAll (file:///misskey/packages/backend/built/misc/prelude/await-all.js:5:28)
misskey-web-1  |     at async NoteEntityService.pack (file:///misskey/packages/backend/built/core/entities/NoteEntityService.js:229:24)
misskey-web-1  |     at async Promise.all (index 0)
misskey-web-1  |     at async NoteEntityService.packMany (file:///misskey/packages/backend/built/core/entities/NoteEntityService.js:312:16)
misskey-web-1  |     at async file:///misskey/packages/backend/built/server/api/endpoints/notes/timeline.js:127:20
misskey-web-1  |     at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:247:16) {
misskey-web-1  |   query: 'SELECT "Instance"."id" AS "Instance_id", "Instance"."caughtAt" AS "Instance_caughtAt", "Instance"."host" AS "Instance_host", "Instance"."usersCount" AS "Instance_usersCount", "Instance"."notesCount" AS "Instance_notesCount", "Instance"."followingCount" AS "Instance_followingCount", "Instance"."followersCount" AS "Instance_followersCount", "Instance"."latestRequestSentAt" AS "Instance_latestRequestSentAt", "Instance"."latestStatus" AS "Instance_latestStatus", "Instance"."latestRequestReceivedAt" AS "Instance_latestRequestReceivedAt", "Instance"."lastCommunicatedAt" AS "Instance_lastCommunicatedAt", "Instance"."isNotResponding" AS "Instance_isNotResponding", "Instance"."isSuspended" AS "Instance_isSuspended", "Instance"."softwareName" AS "Instance_softwareName", "Instance"."softwareVersion" AS "Instance_softwareVersion", "Instance"."openRegistrations" AS "Instance_openRegistrations", "Instance"."name" AS "Instance_name", "Instance"."description" AS "Instance_description", "Instance"."maintainerName" AS "Instance_maintainerName", "Instance"."maintainerEmail" AS "Instance_maintainerEmail", "Instance"."iconUrl" AS "Instance_iconUrl", "Instance"."faviconUrl" AS "Instance_faviconUrl", "Instance"."themeColor" AS "Instance_themeColor", "Instance"."infoUpdatedAt" AS "Instance_infoUpdatedAt" FROM "instance" "Instance" WHERE ("Instance"."host" = $1) LIMIT 1',
```

## 📝 Steps to Reproduce

There are sites upgraded successfully, I don't know the cause of the problem and whether it can be reproduced.

1. No problem deployment of Misskey v13.0.0-beta.17
2. Upgraded to v13.0.0-beta.18

## 📌 Environment

Misskey version: v13.0.0-beta18 (docker)
Postgresql version: 12.2-alpine
Your OS: Debian 11
Your browser: Firefox 108

**Comment by creamlike1024** [comment]
Solved. It may be that the source code of different versions is mixed
