### ISSUE TITLE
Cannot run `yarn install`

### ISSUE THREAD

**Issue by paring-chan** [syuilo/Misskey#9501]
## 💡 Summary

esbuild doesn't build on install

## 🥰 Expected Behavior

The `yarn` command should be done successfully

## 🤬 Actual Behavior

```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @bull-board/fastify@npm:4.10.0 doesn't provide fastify (p26781), requested by @fastify/static
➤ YN0002: │ @bull-board/fastify@npm:4.10.0 doesn't provide fastify (p1220b), requested by @fastify/view
➤ YN0002: │ @tensorflow/tfjs@npm:4.1.0 doesn't provide seedrandom (p34793), requested by @tensorflow/tfjs-data
➤ YN0060: │ backend@workspace:packages/backend provides @tensorflow/tfjs (pd0e11) with version 4.1.0, which doesn't satisfy what nsfwjs requests
➤ YN0060: │ backend@workspace:packages/backend provides ioredis (p06edb) with version 4.28.5, which doesn't satisfy what typeorm requests
➤ YN0002: │ backend@workspace:packages/backend doesn't provide webpack (p029b1), requested by json5-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 310ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0068: │ consolidate ➤ dependencies ➤ ejs: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0069: │ chartjs-adapter-date-fns ➤ peerDependencies ➤ date-fns: This rule seems redundant when applied on the original package; the extension may have been applied upstream.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 672ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.16.9 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.54 must be built because it never has been before or the last one failed
➤ YN0009: │ esbuild@npm:0.16.9 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-46ac0d91/build.log)
➤ YN0009: │ esbuild@npm:0.14.54 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2e419948/build.log)
➤ YN0000: └ Completed in 4s 36ms
➤ YN0000: Failed with errors in 5s 297ms
```

build.log:

```
# This file contains the result of Yarn building a package (esbuild@npm:0.14.54)
# Script name: postinstall

/home/paring/Documents/misskey/node_modules/.store/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/install.js:93
    throw new Error(`Expected ${JSON.stringify("0.14.54")} but got ${JSON.stringify(stdout)}`);
          ^

Error: Expected "0.14.54" but got "0.16.15"
    at validateBinaryVersion (/home/paring/Documents/misskey/node_modules/.store/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/install.js:93:11)
    at /home/paring/Documents/misskey/node_modules/.store/esbuild-npm-0.14.54-b3dcd8a41e/node_modules/esbuild/install.js:240:5

Node.js v19.3.0
```

## 📝 Steps to Reproduce

1. clone misskey
2. run `yarn`

## 📌 Environment

Misskey version: 13.0.0-beta.32
Your OS: Arch Linux
Your browser: Chrome 110

**Comment by zyoshoka** [comment]
It seems to be fixed, so I will close this issue.
