### ISSUE TITLE
[V13] pnpm build fail

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#9622]
## 💡 Summary

Everything goes well for the migration except from the moment you have to build with pnpm: 
`NODE_ENV=production pnpm run build`

## 🤬 Actual Behavior

```python
NODE_ENV=production pnpm run build

> misskey@13.0.0 build /home/misskey/misskey
> pnpm build-pre && pnpm -r build && pnpm gulp


> misskey@13.0.0 build-pre /home/misskey/misskey
> node ./scripts/build-pre.js

Scope: 3 of 4 workspace projects
packages/frontend build$ vite build
│ sh: 1: vite: not found
└─ Running...
packages/backend build$ tsc -p tsconfig.json || echo done. && tsc-alias -p tsconfig.json
└─ Running...
packages/sw build$ node build.js
└─ Running...
/home/misskey/misskey/packages/frontend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  frontend@ build: `vite build`
spawn ENOENT
 ELIFECYCLE  Command failed with exit code 1.
```
## 📌 Environment

Misskey version: last v12.x Update to v13
Your OS: Debian Buster (10)
Nodejs: v18.13.0
npm: v9.3.0
pnpm: v7.25.0

**Comment by CyberRex0** [comment]
Perhaps pnpm killed with out of memory during install.
Write `child-concurrency=1` to .npmrc and try pnpm install.

**Comment by tamaina** [comment]
メモリが貧弱なサーバーが多いのでchild-concurrency=1は標準でつけておいた方がいいかもしれない

**Comment by tamaina** [comment]
（swcにすればある程度解消すると思うんだけど）

**Comment by kazukyakayashi** [comment]
I added `child-concurrency=1` in the .npmrc, but still the same problem, that said I just saw while doing everything by hand (I used my script at the beginning) that there is an error at the first command pnpm install
(with or without `child-concurrency=1`).

```python
pnpm install
Scope: all 4 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1729
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1729, reused 1727, downloaded 0, added 0, done
node_modules/.pnpm/@tensorflow+tfjs-node@4.1.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install scrinode_modules/.pnpm/@tensorflow+tfjs-node@4.1.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install script, done in 357ms
 WARN  An error occurred while uploading /home/misskey/misskey/node_modules/.pnpm/@tensorflow+tfjs-node@4.1.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node
node_modules/.pnpm/re2@1.18.0/node_modules/re2: Running install script...
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at spawn (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:80344:19)
    at runCmd_ (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:96493:20)
    at runCmd (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:96434:9)
    at runPackageLifecycle (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:96401:7)
    at Array.<anonymous> (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:95807:13)
    at LOOP (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:95834:18)
    at chain (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:95841:9)
    at lifecycle_ (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:96375:7) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}

Node.js v18.13.0
```

**Comment by CyberRex0** [comment]
It seems to be not enough memory to build.
Increase system memory if possible or you have to use swap.

**Comment by kazukyakayashi** [comment]
I have 2go of RAM and 2go of swap, I just tested directly with `NODE_OPTIONS=--max_old_space_size=3072` and it's ok for now.

**Comment by kazukyakayashi** [comment]
Done, Thank you for your help and (for the speed of the latter as always) 😘
