### ISSUE TITLE
Error: Your application tried to access is-core-module, but it isn't declared in your dependencies

### ISSUE THREAD

**Issue by okpierre** [syuilo/Misskey#9626]
## 💡 Summary
```

Scope: 3 of 4 workspace projects
packages/backend build$ tsc -p tsconfig.json || echo done. && tsc-alias -p tsconfig.json
└─ Running...
packages/frontend build$ vite build
│ /misskey/.pnp.cjs:29840
│       Error.captureStackTrace(firstError);
│             ^
│ Error: Your application tried to access is-core-module, but it isn't declared in your dependencies; 
this makes the require call ambiguous and unsound.
```

<details>
  <summary>read full details</summary>
  
```
Scope: 3 of 4 workspace projects
packages/backend build$ tsc -p tsconfig.json || echo done. && tsc-alias -p tsconfig.json
└─ Running...
packages/frontend build$ vite build
│ /misskey/.pnp.cjs:29840
│       Error.captureStackTrace(firstError);
│             ^
│ Error: Your application tried to access is-core-module, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
│ Required package: is-core-module
│ Required by: /misskey/node_modules/.pnpm/resolve@1.22.1/node_modules/resolve/lib/
│ Require stack:
│ - /misskey/node_modules/.pnpm/resolve@1.22.1/node_modules/resolve/lib/async.js
│ - /misskey/node_modules/.pnpm/resolve@1.22.1/node_modules/resolve/index.js
│     at Function.require$$0.Module._resolveFilename (/misskey/.pnp.cjs:29840:13)
│     at Function.require$$0.Module._load (/misskey/.pnp.cjs:29690:42)
│     at Module.require (node:internal/modules/cjs/loader:1067:19)
│     at require (node:internal/modules/cjs/helpers:103:18)
│     at Object.<anonymous> (/misskey/node_modules/.pnpm/resolve@1.22.1/node_modules/resolve/lib/async.js:7:14)
│     at Module._compile (node:internal/modules/cjs/loader:1165:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
│     at Object.require$$0.Module._extensions..js (/misskey/.pnp.cjs:29884:33)
│     at Object.require$$0.Module._extensions..js (/misskey/.pnp.cjs:29884:33)
│     at Module.load (node:internal/modules/cjs/loader:1043:32)
└─ Failed in 1.3s at /misskey/packages/frontend
packages/sw build$ node build.js
└─ Running...
/misskey/packages/frontend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  frontend@ build: `vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

</details>

## 📌 Environment

Misskey version: v13 https://github.com/misskey-dev/misskey/commit/9d64ac6d6f4050b260d1a3ff39efbd932f4a523f
Your OS: Ubuntu Linux VPS 2GB memory

**Comment by zyoshoka** [comment]
Closing this issue since yarn is no longer used.
