### ISSUE TITLE
Upgrade from 12.119.2 to 13.0.0 fails `Error: Cannot find module './build/Release/re2'`

### ISSUE THREAD

**Issue by Sakrecoer** [syuilo/Misskey#9635]
## 💡 Summary

Upgrade failed, porbably due to outdated nodejs (16.19.0) Will try to upgrade node and run again, but figured i could mention that it could be usefull to mention the changes in the release notes.

## 🥰 Expected Behavior

smooth and easy upgrade, as per documentation page

## 🤬 Actual Behavior

Migration fails.

```
~/misskey$ pnpm run migrate

> misskey@13.0.0 migrate /home/misskey/misskey
> cd packages/backend && pnpm typeorm migration:run -d ormconfig.js

query: SELECT * FROM current_schema()
Error during migration run:
Error: Cannot find module './build/Release/re2'
Require stack:
- /home/misskey/misskey/node_modules/.pnpm/re2@1.18.0/node_modules/re2/re2.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/misskey/misskey/node_modules/.pnpm/re2@1.18.0/node_modules/re2/re2.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/misskey/misskey/node_modules/.pnpm/re2@1.18.0/node_modules/re2/re2.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.

```

## 📝 Steps to Reproduce

1. go to release page! rejoice over delicious new major upgrade \o/ thank you kind developers :purple_heart: 
2. see no indication that dependency have changed.
3. follow [upgrade procedure](https://misskey-hub.net/en/docs/install/manual.html#how-to-update-your-misskey-server-to-the-latest-version), notice `pnpm` is needed. Address that and go on with steps
4. migration fails

## 📌 Environment

Misskey version: 12.119.2 -> 13.0.0
Your OS: Ubuntu 20.04

**Comment by Sakrecoer** [comment]
oh... 12.119.2 has no version tag :grimacing: rollback is going to be a tough one

**Comment by Sakrecoer** [comment]
migration fails with nodejs 18.13 too :'( still complaining about re2... i guess i will try to install it manually

```
~/misskey$ pnpm run migrate

> misskey@13.0.0 migrate /home/misskey/misskey
> cd packages/backend && pnpm typeorm migration:run -d ormconfig.js

query: SELECT * FROM current_schema()
Error during migration run:
Error: Cannot find module './build/Release/re2'
Require stack:
- /home/misskey/misskey/node_modules/.pnpm/re2@1.18.0/node_modules/re2/re2.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/misskey/misskey/node_modules/.pnpm/re2@1.18.0/node_modules/re2/re2.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/misskey/misskey/node_modules/.pnpm/re2@1.18.0/node_modules/re2/re2.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Sakrecoer** [comment]
i guess i'm too much of a node n00b... cleared my node_modules folder, and now `NODE_ENV=production pnpm run build` is failing instead.

```
/home/misskey/misskey/packages/backend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  backend@ build: `tsc -p tsconfig.json || echo done. && tsc-alias -p tsconfig.json`
spawn ENOENT
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Sakrecoer** [comment]
turns out i was just out of ram and `NODE_ENV=production pnpm install --frozen-lockfile` was failing! I didn't pick up the part where it said "killed" 

So I freed some ram up and tada! \o/ 

Sorry for the noise, Hopefully this issue can help someone else :purple_heart: but i think i can close it since it is resolved.

Many many thanks for this awesome piece of software!

**Comment by Sakrecoer** [comment]
:bow: i'm sorry, the migration was successful, but it fails at boot.

```
--- gandibass2 (PID: 3255615) ---
INFO *  [core boot]     Welcome to Misskey!
INFO *  [core boot]     Misskey v13.0.0
INFO *  [core boot env] NODE_ENV: production
INFO *  [core boot nodejs]      Version v18.13.0 detected.
ERR  *  [core boot]     Fatal error occurred during initialization
INFO *  [core]  The process is going to exit with code 1
 ELIFECYCLE  Command failed with exit code 1.
```

Realized i don't know where the logs end up so i can figure out what that means. Definitely enough ram this time

**Comment by Sakrecoer** [comment]
closing because my current problem is not the on listed in the issue
