### ISSUE TITLE
Error: Question is not registered

### ISSUE THREAD

**Issue by ikuradon** [syuilo/Misskey#9656]
## 💡 Summary

pollイベントをAP経由で受信時にエラーが出る
もしかしたら投票終了イベント？
## 🥰 Expected Behavior

No error

## 🤬 Actual Behavior

```
Error: Question is not registed
    at ApQuestionService.updateQuestion (file:///misskey/packages/backend/built/core/activitypub/models/ApQuestionService.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApInboxService.update (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:625:13)
    at async ApInboxService.performOneActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:112:13)
    at async ApInboxService.performActivity (file:///misskey/packages/backend/built/core/activitypub/ApInboxService.js:91:13)
    at async InboxProcessorService.process (file:///misskey/packages/backend/built/queue/processors/InboxProcessorService.js:163:9)
    at async /misskey/node_modules/.pnpm/bull@4.10.2/node_modules/bull/lib/p-timeout.js:69:17
```

## 📝 Steps to Reproduce

1. 85f3df4c0ebb179fe9446f29deb7b4ebbb87a85f
2. Receive poll event

## 📌 Environment

Misskey version: 85f3df4c0ebb179fe9446f29deb7b4ebbb87a85f
Your OS: 
Your browser:

**Comment by syuilo** [comment]
謎

**Comment by ikuradon** [comment]
inboxキューは壊れていないので謎…ちょっと検証するか
(オフトピ：registedではなくregisteredでは…？)

**Comment by KisaragiEffective** [comment]
> (オフトピ：registedではなくregisteredでは…？)

直しました

**Comment by zyoshoka** [comment]
> > (オフトピ：registedではなくregisteredでは…？)
> 
> 直しました

元のエラーメッセージに対しての話だと思います

**Comment by KisaragiEffective** [comment]
> > > (オフトピ：registedではなくregisteredでは…？)
> > 
> > 
> > 直しました
> 
> 元のエラーメッセージに対しての話だと思います

🙇🏻 #14213 にて修正見込み

**Comment by KisaragiEffective** [comment]
コメントのリンクを与えたつもりがdevelopmentと勘違いされて閉じられたのでre-open
