### ISSUE TITLE
Misskeyについてのページが正しく表示されない

### ISSUE THREAD

**Issue by xianonn** [syuilo/Misskey#9738]
## 💡 Summary

よく使うリアクション絵文字リストを全て削除してMisskeyについてのページ(about-misskey)を表示しようとしても正しく表示されません。

https://github.com/misskey-dev/misskey/blob/7190bd00c9dec5e0054cd52be05cc9f294485158/packages/frontend/src/pages/about-misskey.vue#L191-L200
`defaultStore.state.reactions` が空のため `emoji` が `undefined` になっているのだと思われます。

## 🥰 Expected Behavior

Misskeyについてのページが表示される。

## 🤬 Actual Behavior

Misskeyについてのページが正しく表示されない。

ブラウザのエラーログ
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at about-misskey-a39f37da.js:27:84923
    at yc (vue-5dd5ade4.js:1:33070)
    at about-misskey-a39f37da.js:27:84838
    at s (vue-5dd5ade4.js:1:17090)
    at Cc (vue-5dd5ade4.js:1:33809)
    at Proxy.<anonymous> (app-29bd167d.js:13:16850)
    at Tn (vue-5dd5ade4.js:1:17402)
    at on.v [as fn] (vue-5dd5ade4.js:1:51209)
    at on.run (vue-5dd5ade4.js:1:4936)
    at X.f.update (vue-5dd5ade4.js:1:51936)
```

## 📝 Steps to Reproduce

1. 設定→リアクション の一番上の絵文字を全て削除する
2. Misskeyについて のページを表示する

## 📌 Environment

Misskey version: 13.1.8
Your OS: Windows10
Your browser: Brave

**Comment by KisaragiEffective** [comment]
triage: 2024.5.0でも再現。
