### ISSUE TITLE
アカウント情報の取得に失敗しましたと出てmisskeyを使用できないユーザーが1名いる

### ISSUE THREAD

**Issue by mendakon** [syuilo/Misskey#9768]
## 💡 Summary
すしすきーアップデート後にとあるユーザーがログイン不能になった
アップデート 12.118→13.2.0
現状報告されているユーザーが1名だけ

## 🤬 Actual Behavior

`アカウント情報の取得に失敗しました
{"message":"Internal error occurred. Please contact us if the error persists.","code":"INTERNAL_ERROR","id":"5d37dbcb-891e-41ca-a3d6-e690c97775ac","kind":"server","info":{"e":{"message":"canceling statement due to statement timeout","code":"QueryFailedError","stack":"QueryFailedError: canceling statement due to statement timeout\n    at PostgresQueryRunner.query (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SelectQueryBuilder.loadRawResults (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2132:25)\n    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1992:26)\n    at async SelectQueryBuilder.getRawAndEntities (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:667:29)\n    at async SelectQueryBuilder.getOne (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:694:25)\n    at async UserEntityService.getHasUnreadAntenna (file:///home/misskey/misskey/packages/backend/built/core/entities/UserEntityService.js:162:48)\n    at async Promise.all (index 56)\n    at async awaitAll (file:///home/misskey/misskey/packages/backend/built/misc/prelude/await-all.js:5:28)\n    at async UserEntityService.pack (file:///home/misskey/misskey/packages/backend/built/core/entities/UserEntityService.js:399:16)\n    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/i.js:51:20\n    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:273:16)"}}}`

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by MomentQYC** [comment]
A very small number of users are experiencing timeline unavailability issues, with errors reported as :
```
	"QueryFailedError: canceling statement due to statement timeout\n    at PostgresQueryRunner.query (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.12_ioredis@4.28.5+pg@8.9.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SelectQueryBuilder.loadRawResults (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.12_ioredis@4.28.5+pg@8.9.0/node_modules/typeorm/query-builder/SelectQueryBuilder…oredis@4.28.5+pg@8.9.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:681:29)\n    at async SelectQueryBuilder.getMany (/home/misskey/misskey/node_modules/.pnpm/typeorm@0.3.12_ioredis@4.28.5+pg@8.9.0/node_modules/typeorm/query-builder/SelectQueryBuilder.js:747:25)\n    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/notes/timeline.js:123:30\n    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:273:16)"', $7 = NULL, $8 = '9ay9z45zm4', $9 = 'f', $10 = 'public', $11 = '{}', $12 = '{}', $13 = '{}', $14 = '{8y54obpbh8}', $15 = '[]', $16 = '{}', $17 = '{}', $18 = 'f', $19 = NULL, $20 = NULL, $21 = '8y54obpbh8', $22 = NULL, $23 = NULL, $24 = NULL
```
I don't know if it's the same situation.
There is currently an unknown principle solution to this problem, which is to unfollow a specific user (everyone is different).
