### ISSUE TITLE
再試行ボタンが機能していない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9922]
## 💡 Summary

再試行ボタンを押しても何も起きない時がある。

## 🥰 Expected Behavior

再試行される

## 🤬 Actual Behavior

画面上では何も変化がなく、コンソールにエラーが表示される。

```plaintext
TypeError: c.fetch is not a function
    at e.value.C.value.o.onRetry.s.<computed>.s.<computed> (note-6cbf6368.js:1:4074)
    at De (vue-d931045c.js:1:14136)
    at we (vue-d931045c.js:1:14214)
    at Zl (vue-d931045c.js:1:16623)
    at Pt.onClick.n.<computed>.n.<computed> (app-974842e4.js:13:11878)
    at De (vue-d931045c.js:1:14136)
    at we (vue-d931045c.js:1:14214)
    at Zl (vue-d931045c.js:1:16623)
    at e.link.E.onClick.d.<computed>.d.<computed> (os-74973299.js:39:10038)
    at De (vue-d931045c.js:1:14136)
```

## 📝 Steps to Reproduce

1. ノートの詳細ページを開き、何らかの方法でエラーを発生させる
2. 再試行ボタンを押す
(これ以外にも機能しない箇所がある可能性あり)

## 📌 Environment

Misskey version: 13.5.3
Your OS: macOS Monterey
Your browser: 110.0.5481.77 (Official Build) （arm64）

**Comment by syuilo** [comment]
最新版では修正済み 🙏🏻

**Comment by CyberRex0** [comment]
あっ
